### ISSUE TITLE
Exception Invalid filter element: test

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1013]
When I run tests using NUnit console 3 beta 5 with the arg --testlist I get the following exception in the case when I my tests referenced to nunit.framework, Version 2.6.4.14350.

-- Create a list of tests

System.ArgumentException: Invalid filter element: test
arameter name: xmlNode

erver stack trace:
  at NUnit.Engine.Drivers.NUnit2FrameworkDriver.FromXml(XmlNode xmlNode)
  at NUnit.Engine.Drivers.NUnit2FrameworkDriver.FromXml(XmlNode xmlNode)
  at NUnit.Engine.Drivers.NUnit2FrameworkDriver.CountTestCases(String filter)
  at NUnit.Engine.Runners.DirectTestRunner.CountTests(TestFilter filter)
  at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
  at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

xception rethrown at [0]:
  at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
  at NUnit.Engine.ITestEngineRunner.CountTestCases(TestFilter filter)
  at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
  at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
  at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
  at NUnit.ConsoleRunner.Program.Main(String[] args)

**Comment by CharliePoole** [comment]
This looks like it duplicates #990, which we fixed in RC2. Issue #990 didn't relate to --testlist, but the root cause is probably the same. Would you try this with RC2 and confirm?

**Comment by NikolayPianikov** [comment]
I've checked, it is working fine for rc2
