### ISSUE TITLE
TestCaseData - Test method has non-void return type, but no result is expected

### ISSUE THREAD

**Issue by replaysMike** [nunit/nunit#1273]
I've seen this reported several times over the years, and I seem to be seeing it in v3.0.1.

The example setup is pretty identical to the one that appears in the docs:

```
[Test, TestCaseSource(typeof(SchemaFactory),"SchemaTestCases")]
[Category("JsonValidation")]
public bool TestShouldValidate(string schemaYaml, string requestUrl, HttpMethod method, string responseJson)
{
//... do stuff
return true;
}

private class SchemaFactory
{
    public static IEnumerable SchemaTestCases
    {
        get
        {
            yield return new TestCaseData("ObjectSchema.yaml", "/test/object", HttpMethod.Get, "ObjectResponse.json").Returns(true);
        }
    }
}
```
Is there a specific setup that is known to cause this?

**Comment by CharliePoole** [comment]
It's a mystery to me! What happens if you change the method to return `IEnumerable<TestCaseData>`

**Comment by replaysMike** [comment]
Nope same result. What's interesting is the test shows up twice in the Test Explorer (VS2015). One with no parameters and one with a single parameter called TestCaseData.

When running the one with no parameters shown I get the reported error. When running the one with a TestCaseData parameter it simply says No arguments were provided.

Perhaps a unit test is needed for this feature? /s

**Comment by replaysMike** [comment]
I should also note that I tried adding the attribute `TestCase(ExpectedResult = true)` however this did not change the error message from showing up.

**Comment by CharliePoole** [comment]
@replaysMike Responding to several different comments of yours...

1. I'm suspicious of the extra `Test` attribute. What happens if you remove it?

2. Adding the `TestCase` attribute to this mix should cause an additional error. I'm surprised it didn't. That leads me to wonder if you have another overload of the `TestShouldValidate` method in the same assembly.

3. Do you get the error even with the code as shown? That is, with no actual body in the test method except for returning true?

**Comment by replaysMike** [comment]
Hi Charlie,

1. Interesting to note, when I removed the [Test] attribute the VS2015 Test Explorer now shows a parameter on the TestShouldValidate() test. However when running it, for each TestData object it returns the same error "Test method has non-void return type, but no result is expected".

2. It didn't in my case, but it didn't change the outcome either.

3. Yes that is correct. Even without the body being empty.

I spent some time looking through the nUnit source and noticed all the internal tests also use the syntax "[Test, TestCaseSource(...)]" which is what I based my original attempts on. What is worth noting is I only get these issues when using the VS2015 Test Explorer - everything works fine using the nUnit console.

**Comment by replaysMike** [comment]
I'm going to show my current code, which works fine using the nUnit console:

```
public class SchemaTestData
{
  public SchemaTestData() { }

  public static IEnumerable SchemaTestCases
  {
      get
      {
          /*
              Build specific test cases here
          */
          yield return new TestCaseData("Object.yaml", "/test/case", HttpMethod.Get, "ObjectResponse.json").Returns(true).SetName("Object");
          yield return new TestCaseData("Reference.yaml", "/test/case", HttpMethod.Get, "ReferenceResponse.json").Returns(true).SetName("Reference");
          yield return new TestCaseData("Array.yaml", "/test/case", HttpMethod.Get, "ArrayResponse.json").Returns(true).SetName("Array");

          yield return new TestCaseData("Required.yaml", "/test/case", HttpMethod.Get, "RequiredFailureResponse.json").Returns(false).SetName("Required");
          yield return new TestCaseData("Required.yaml", "/test/case", HttpMethod.Get, "RequiredSuccessResponse.json").Returns(true).SetName("Required");

          yield return new TestCaseData("RootArray.yaml", "/test/case", HttpMethod.Get, "RootArrayResponse.json").Returns(true).Ignore("Not currently supported.");

          yield return new TestCaseData("NestedObject.yaml", "/test/case", HttpMethod.Get, "NestedObjectResponse.json").Returns(true).SetName("NestedObject");

          yield return new TestCaseData("MinimumMaximumValue.yaml", "/test/case", HttpMethod.Get, "MinimumValueFailureResponse.json").Returns(false).SetName("MinimumValue");
          yield return new TestCaseData("MinimumMaximumValue.yaml", "/test/case", HttpMethod.Get, "MinimumValueSuccessResponse.json").Returns(true).SetName("MinimumValue");
          yield return new TestCaseData("MinimumMaximumValue.yaml", "/test/case", HttpMethod.Get, "MaximumValueFailureResponse.json").Returns(false).SetName("MaximumValue");
          yield return new TestCaseData("MinimumMaximumValue.yaml", "/test/case", HttpMethod.Get, "MaximumValueSuccessResponse.json").Returns(true).SetName("MaximumValue");

          yield return new TestCaseData("MinItemsMaxItems.yaml", "/test/case", HttpMethod.Get, "MinItemsFailureResponse.json").Returns(false).SetName("MinItems");
          yield return new TestCaseData("MinItemsMaxItems.yaml", "/test/case", HttpMethod.Get, "MinItemsSuccessResponse.json").Returns(true).SetName("MinItems");
          yield return new TestCaseData("MinItemsMaxItems.yaml", "/test/case", HttpMethod.Get, "MaxItemsFailureResponse.json").Returns(false).SetName("MaxItems");
          yield return new TestCaseData("MinItemsMaxItems.yaml", "/test/case", HttpMethod.Get, "MaxItemsSuccessResponse.json").Returns(true).SetName("MaxItems");

          yield return new TestCaseData("PatternNumberFormat.yaml", "/test/case", HttpMethod.Get, "PatternNumberFormatFailureResponse.json").Returns(false).SetName("NumberPattern");
          yield return new TestCaseData("PatternNumberFormat.yaml", "/test/case", HttpMethod.Get, "PatternNumberFormatSuccessResponse.json").Returns(true).SetName("NumberPattern");

          yield return new TestCaseData("PatternGuidFormat.yaml", "/test/case", HttpMethod.Get, "PatternGuidFormatFailureResponse.json").Returns(false).SetName("GuidPattern");
          yield return new TestCaseData("PatternGuidFormat.yaml", "/test/case", HttpMethod.Get, "PatternGuidFormatSuccessResponse.json").Returns(true).SetName("GuidPattern");

          yield return new TestCaseData("PatternEmailFormat.yaml", "/test/case", HttpMethod.Get, "PatternEmailFormatFailureResponse.json").Returns(false).SetName("EmailPattern");
          yield return new TestCaseData("PatternEmailFormat.yaml", "/test/case", HttpMethod.Get, "PatternEmailFormatSuccessResponse.json").Returns(true).SetName("EmailPattern");

          yield return new TestCaseData("ComplexDefinition.yaml", "/test/case", HttpMethod.Get, "ComplexDefinitionFailureResponse.json").Returns(false).SetName("ComplexDefinition");
          yield return new TestCaseData("ComplexDefinition.yaml", "/test/case", HttpMethod.Get, "ComplexDefinitionSuccessResponse.json").Returns(true).SetName("ComplexDefinition");
      }

      
  }
}
```


```
[TestFixture]
    public class JsonValidatorTests
{
    Assembly assembly;
    JsonSchemaManager manager;

    [TestCaseSource(typeof(SchemaTestData), "SchemaTestCases")]
    [Category("JsonValidation")]
    public bool ExecuteAllTests(string schemaYamlResource, string requestUrl, HttpMethod method, string responseJsonResource)
    {
        bool isValid = TestShouldValidate(schemaYamlResource, requestUrl, method, responseJsonResource);
        return isValid;
    }

    private bool TestShouldValidate(string schemaYamlResource, string requestUrl, HttpMethod method, string responseJsonResource)
    {
        var schemaYaml = LoadTestSchema(schemaYamlResource);
        JsonSchema jsonSchema = manager.Parse(schemaYaml);
        
        string responseJson = LoadTestData(responseJsonResource);
        if (!JsonParserV4.IsValid(responseJson))
            throw new InvalidDataException("Unit test failure - input json is invalid.");

        JsonSchemaValidator validator = new JsonSchemaValidator(jsonSchema);
        List<string> validationErrors;
        //bool isValidResponse = validator.IsValidResponse(JsonSchemaVersion.Swagger_2_0, "/test/object", "get", responseJson, out validationErrors);
        bool isValidResponse = validator.IsValidResponse(JsonSchemaVersion.Swagger_2_0, requestUrl, method.Method.ToLower(), responseJson, out validationErrors);

        // check validation errors for debugging
        OutputValidationErrors(validationErrors);

        return isValidResponse;
    }

    private void OutputValidationErrors(List<string> validationErrors)
    {
        if (validationErrors != null && validationErrors.Count > 0)
        {
            foreach (var error in validationErrors)
                Console.WriteLine(String.Format("{0}", error));
        }
    }

    private string LoadTestData(string name)
    {
        return LoadResource(".Data." + name);
    }

    private string LoadTestSchema(string name)
    {
        return LoadResource(".Schemas." + name);
    }

    private string LoadResource(string resourceName)
    {
        string txt = "";
        try {
            using (var stream = assembly.GetManifestResourceStream(assembly.GetName().Name + resourceName))
            {
                using (var reader = new StreamReader(stream))
                {
                    txt = reader.ReadToEnd();
                }
            }
        }
        catch (ArgumentNullException ex)
        {
            // invalid resource filename specified
            throw new Exception(String.Format("The resource name '{1}{0}' was not found.", resourceName, assembly.GetName().Name));
        }
        return txt;
    }


    [SetUp]
    public void SetupValidators()
    {
        manager = new JsonSchemaManager();
        assembly = Assembly.GetExecutingAssembly();
    }

    [TearDown]
    public void TeardownValidators()
    {
        
    }

}
```

**Comment by Green-Bug** [comment]
I've tried to repro this and I can't. Visual Studion 2015, NUnit v 3.0.1, NUnit3 Test Adapter v3.0.8.
For the first example this is what I get in Visual Studio test Explorer - in other words I get what I would expect:
```
Test Name:	TestShouldValidate("ObjectSchema.yaml","/test/object",GET,"ObjectResponse.json")
Test FullName:	NUnit.TestsFactory.TestClass.TestShouldValidate("ObjectSchema.yaml","/test/object",GET,"ObjectResponse.json")
Test Source:	d:\Projects\Temp\NUnit.TestsFactory\NUnit.TestsFactory\TestClass.cs : line 25
Test Outcome:	Failed
Test Duration:	0:00:00.0000001

Result StackTrace:	
at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
Result Message:	
Expected: True
  But was:  False
```
Related: You set the names manually in your full example, but multiple tests have the same name so they will not show up in Test Explorer and I get this in the Tests output window of Visual Studio:
```
A test with the same name 'NUnit.TestsFactory.JsonValidatorTests.Required' already exists. This test is not added to the test window.
```

**Comment by replaysMike** [comment]
Adding the name is something I did at the very end when testing the nUnit cli, if it caused any problems it wasn't the ones reported. I had not been setting the names manually before.

I'm also using VS2015 Update 1, nUnit 3.0.1.... **aha**! 

The NUnit3 Test Adapter was not installed at all. That is the source of this error. After installing the extension and restarting visual studio, building.. they all showed up after that. Interesting that all of the tests still worked without the adapter, except when using TestSourceCase!

Thanks for the hint, that did the trick. Hopefully this will help others that come across this error.

**Comment by CharliePoole** [comment]
@replaysMike Glad you figured it out! I can only guess that you had an older version of the NUnit Adapter (for V2) installed, which didn't know about 3.0 and therefore didn't give an error when trying to run 3.0 tests.

**Comment by replaysMike** [comment]
Actually I didn't have any nUnit test adapter installed - not sure how that happened but I was surprised the tests were working at all without it. I didn't even think to check it until I was confirming which version was installed.

**Comment by CharliePoole** [comment]
Remember that you can have an adapter installed globally via a vsix file as well as locally using nuget.

**Comment by replaysMike** [comment]
ah right - the v2 adapter was installed as a Nuget package. My fix was to install it as a VS extension. The better solution will be to upgrade the nuget package (it's a large project) for all developers to use - I didn't realize it was available as a package as well as extension.

**Comment by replaysMike** [comment]
oh wait - there is no v3 test adapter via nuget?

**Comment by replaysMike** [comment]
pre-release I guess - found it :) That little "include prerelease" checkbox I didn't seem to know existed. It's one of those days.

**Comment by CharliePoole** [comment]
Monday!
