### ISSUE TITLE
Nunit 3 Console causes file load exception when running against 2.6.2 unit tests.

### ISSUE THREAD

**Issue by JamieClayton** [nunit/nunit#1291]
I'm working on migrating from Nunit 2.6.2 to 3.x for our codebase. While testing the new command line arguments for nunit3-console.exe I found it difficult to resolve the path to the nunit.framework.dll 2.6.2 files that are stored in our code repository (rather than installed via MSI or nuget etc).

I was trying to determine how the .\addins\nunit.v2.driver.dll interacted with a particular edition of nunit 2.x. Do I need to

1. copy that edition of nunit into the addin's folder or
2. is there a console argument or
3. do I modify a *.config file setting for a relative path from the nunit3-console.exe to Nunit.Framework.dll (2.6.2) in our source control repository?
4. should we migrate the current v2.6.2 unit tests to v.2.6.4 as debugging the current github nunit.sln in Visual Studio highlighted that v2.6.4 gets copied to the addins folder.

I've added a similar post in the nunit/docs area, because it wasn't clear if Nunit 3 had the ability to resolve this without resorting to a code change. A.k.a, previous edition of Nunit used the *.config files to help address binding style problems. I've attached a debug build with the exceptions so you can see the exact lines in files involved with this console error.

**Console Exception**

```
`System.IO.FileLoadException: Could not load file or assembly 'nunit.framework, Version=2.6.2.12296, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.
(Exception from HRESULT: 0x80131040)
File name: 'nunit.framework, Version=2.6.2.12296, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77'

Server stack trace:

   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustB
eInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTrans
parent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at NUnit.Core.CoreExtensions.InstallAdhocExtensions(Assembly assembly)
   at NUnit.Core.Builders.TestAssemblyBuilder.Load(String path)
<snip />
System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Core.TestRunner.Load(TestPackage package)
   at NUnit.Engine.Drivers.NUnit2FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings) in D:\Code\Git\nunit\src\NUnitEngine\Addins\nunit.v2.driver\NUnit2FrameworkDriver.cs:line 88
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage() in D:\Code\Git\nunit\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 109
<snip />
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Load()
   at NUnit.Engine.Runners.ProcessRunner.LoadPackage() in D:\Code\Git\nunit\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 111
   at NUnit.Engine.Runners.AbstractTestRunner.Load() in D:\Code\Git\nunit\src\NUnitEngine\nunit.engine\Runners\AbstractTestRunner.cs:line 183
   at NUnit.Engine.Runners.AggregatingTestRunner.LoadPackage() in D:\Code\Git\nunit\src\NUnitEngine\nunit.engine\Runners\AggregatingTestRunner.cs:line 77
<snip />
   at NUnit.ConsoleRunner.Program.Main(String[] args) in D:\Code\Git\nunit\src\NUnitConsole\nunit3-console\Program.cs:line 121`
```

**Comment by rprouse** [comment]
I have updated your comment for formatting and readability.

You should not have to change the location of the v2 engine addin, nor should you have to copy the 2.6.2 framework dll into the addin directory, it should just work. You should be able to run 2.6.2 tests with nunit3-console without any special command line options. You should just be able to pass your test assembly on the command line.

We have seen some path related bugs running from Visual Studio solution files or  nunit project files, so if you are doing that, let's get it running on using one of your test assemblies first.

With a clean install of NUnit 3 (just in case something got messed up with your experiments), try running `nunit3-console.exe path\to\yourTestAssembly.dll` and report back. This assumes that the NUnit 2.6.2 DLL is in the same directory as your test assembly.

If that doesn't work, let's eliminate path issues, CD into your test directory and run `nunit3-console.exe yourTestAssembly.dll`.

**Comment by JamieClayton** [comment]
@rprouse Thanks for the prompt reply. We have 20,454 unit tests across 54 unit test projects for an enterprise application which all get compiled to the same directory (including Nunit.Framework.dll).  The ability to upgrade all those projects from v2 -> v3 in one step is unlikely.  In this case I had a single unit test project upgraded to v3 which seemed to be problem with the v2.6.2 Nunit.Framework.dll reference, because the v3 edition just so happened to be in the directory.  I'll have to think about how this might impact our TeamCity and software deployment build processes.

**Comment by CharliePoole** [comment]
At a minimum, you would have to put your 3.0 tests in a separate directory in order to give each set of tests a copy of the correct framework version. You can still run them together if that's your preference.

Based on your comment, this doesn't appear to be a bug. Can we close it?

**Comment by JamieClayton** [comment]
I tend to agree that it's not a bug, but I'm thinking that an improvement to the error message to include the path where the expected assembly is worth thinking about.
