### ISSUE TITLE
TestCaseSource in NUnit 3 converts an argument declared as String[] to String

### ISSUE THREAD

**Issue by ConPac** [nunit/nunit#1327]
A TestCaseSource worked fine with NUnit 2 defined as
`public static readonly string[][] WrongArgs =
        {
            null,
            new string[0],
            new[] {"1"},
        };`
in a test like this
`  [TestCaseSource (typeof (TestData), "WrongArgs")]
        public void Test (string[] args) {...}`

But with NUnit 3.0 and NUnit 3.2 (from NuGet, and executed via ReSharper 10.2), the 3rd case is passed to the test as a string (`"1"`) instead of using the string array (`new[] {"1"}`), causing the test not being executed because of an ArgumentException on invokation.
The previous cases are passing the test as expected.

Any ideas?

**Comment by rprouse** [comment]
So that we can determine if this is an NUnit or a Resharper bug, can you run the tests using `nunit3-console.exe` and see if you get the same error?

**Comment by CharliePoole** [comment]
What happens if you express the type explicitly as `new string[] {"1"}`? I realize that it should be the same - but let's check.

**Comment by ConPac** [comment]
Hi, quick reverting to NUnit 2.6.4.14350 and executing with R# 10.2, the test passes with success. I'll install nunit3-console.exe to give it a try and let you know.
Also, I tried before to express the type as `new string[] {"1"}`, as Charlie suggested, and `new string[1] {"1"}`, but the result was the same.
Besides that, other TestCaseSource using `new string[] {"1", "2"}` gets passed OK.

**Comment by ConPac** [comment]
Well, running under nunit3-console.exe gives the same error.

**Comment by CharliePoole** [comment]
In the processing of test case source data, the argument list may be presented as a TestCaseData item, an object[] or a single item - if the method takes a single argument. A single item, which is an array, is a special case, so there's no surprise if an error crept in here. In this case, NUnit should be able to see that your method takes a single string[] argument and that a string[] argument has been provided. Instead, it seems to be handling it as if you had written `new object[] {"1"} - in which case the object[] would represent the set of arguments and "1" would properly be taken as the first argument. 

While we look at this, your you might try using `new TestCaseData(new [] {"1"})` as a workaround.

**Comment by ConPac** [comment]
Thanks for that quick workaround and A BIG THANKS to all of you for your good work.

**Comment by ConPac** [comment]
Sorry for not testing before my previous comment, but the workaround you suggested didn't worked.

**Comment by constructor-igor** [comment]
I try to reproduce the issue and find unexpected behavior: test class contains 5 tests, but nunit console v3.2 shows 7 tests (see details below):

![image](https://cloud.githubusercontent.com/assets/1849690/13727607/73e9f6ac-e901-11e5-82d2-1c19c71bc700.png)

NUnit console (v3.2) shows 7 tests
```
total="7" passed="3" failed="4"
```

More details:
```
    <test-suite type="TestSuite" id="0-1174" name="NUnit_v3_samples" fullname="NUnit_v3_samples" runstate="Runnable" testcasecount="103" result="Failed" site="Child" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.070792" total="7" passed="3" failed="4" inconclusive="0" skipped="0" asserts="0">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="0-1059" name="NUnitIssue1327" fullname="NUnit_v3_samples.NUnitIssue1327" classname="NUnit_v3_samples.NUnitIssue1327" runstate="Runnable" testcasecount="7" result="Failed" site="Child" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.068125" total="7" passed="3" failed="4" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-case id="0-1060" name="NullArgs" fullname="NUnit_v3_samples.NUnitIssue1327.NullArgs" methodname="NullArgs" classname="NUnit_v3_samples.NUnitIssue1327" runstate="NotRunnable" seed="980176457" result="Failed" label="Invalid" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.002249" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="No arguments were provided" />
          </properties>
          <failure>
            <message><![CDATA[No arguments were provided]]></message>
          </failure>
        </test-case>
        <test-suite type="ParameterizedMethod" id="0-1062" name="SingleArg" fullname="NUnit_v3_samples.NUnitIssue1327.SingleArg" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.015606" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1061" name="SingleArg(&quot;1&quot;)" fullname="NUnit_v3_samples.NUnitIssue1327.SingleArg(&quot;1&quot;)" methodname="SingleArg" classname="NUnit_v3_samples.NUnitIssue1327" runstate="Runnable" seed="1567116626" result="Failed" label="Error" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.011470" asserts="0">
            <failure>
              <message><![CDATA[System.ArgumentException : Object of type 'System.String' cannot be converted to type 'System.String[]'.]]></message>
              <stack-trace><![CDATA[   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1064" name="TwoArgs" fullname="NUnit_v3_samples.NUnitIssue1327.TwoArgs" runstate="Runnable" testcasecount="1" result="Passed" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.021888" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
          <test-case id="0-1063" name="TwoArgs(System.String[])" fullname="NUnit_v3_samples.NUnitIssue1327.TwoArgs(System.String[])" methodname="TwoArgs" classname="NUnit_v3_samples.NUnitIssue1327" runstate="Runnable" seed="976149245" result="Passed" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.020696" asserts="0">
            <reason>
              <message><![CDATA[]]></message>
            </reason>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1070" name="WorkaroundArg" fullname="NUnit_v3_samples.NUnitIssue1327.WorkaroundArg" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.006258" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1069" name="WorkaroundArg(&quot;1&quot;)" fullname="NUnit_v3_samples.NUnitIssue1327.WorkaroundArg(&quot;1&quot;)" methodname="WorkaroundArg" classname="NUnit_v3_samples.NUnitIssue1327" runstate="Runnable" seed="1061146939" result="Failed" label="Error" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.006087" asserts="0">
            <failure>
              <message><![CDATA[System.ArgumentException : Object of type 'System.String' cannot be converted to type 'System.String[]'.]]></message>
              <stack-trace><![CDATA[   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1068" name="WrongArgs" fullname="NUnit_v3_samples.NUnitIssue1327.WrongArgs" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.009058" total="3" passed="2" failed="1" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1065" name="WrongArgs(null)" fullname="NUnit_v3_samples.NUnitIssue1327.WrongArgs(null)" methodname="WrongArgs" classname="NUnit_v3_samples.NUnitIssue1327" runstate="Runnable" seed="609475020" result="Passed" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.002213" asserts="0">
            <reason>
              <message><![CDATA[]]></message>
            </reason>
          </test-case>
          <test-case id="0-1066" name="WrongArgs(System.String[])" fullname="NUnit_v3_samples.NUnitIssue1327.WrongArgs(System.String[])" methodname="WrongArgs" classname="NUnit_v3_samples.NUnitIssue1327" runstate="Runnable" seed="1154843673" result="Passed" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.002119" asserts="0">
            <reason>
              <message><![CDATA[]]></message>
            </reason>
          </test-case>
          <test-case id="0-1067" name="WrongArgs(&quot;1&quot;)" fullname="NUnit_v3_samples.NUnitIssue1327.WrongArgs(&quot;1&quot;)" methodname="WrongArgs" classname="NUnit_v3_samples.NUnitIssue1327" runstate="Runnable" seed="195284356" result="Failed" label="Error" start-time="2016-03-13 07:51:18Z" end-time="2016-03-13 07:51:18Z" duration="0.000325" asserts="0">
            <failure>
              <message><![CDATA[System.ArgumentException : Object of type 'System.String' cannot be converted to type 'System.String[]'.]]></message>
              <stack-trace><![CDATA[   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
```
file can be download from https://github.com/constructor-igor/TechSugar/blob/master/TestingLab/NUnitSamples/NUnit_v3_samples/NUnitIssue1327.cs

**Comment by CharliePoole** [comment]
Thanks @constructor-igor 

Looks as if WrongArgs is generating three cases and NullArgs is showing up as a simple test rather than a parameterized suite. Both are odd. Probably the null should be causing an error, since the enumerable itself is null.
