### ISSUE TITLE
NUnit crashes when Explicit test has no reason.

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#1370]
I have the following attribute. Please don't question it's existence.

```
	[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Method, Inherited = true, AllowMultiple = true)]
	sealed class DoNotRunOnComputerAttribute : Attribute, IApplyToTest
	{
		public DoNotRunOnComputerAttribute(string computerName)
		{
			this.computerName = computerName;
		}

		readonly string computerName;

		void IApplyToTest.ApplyToTest(NUnit.Framework.Internal.Test test)
		{
			if (test.RunState == RunState.NotRunnable || test.RunState == RunState.Ignored)
			{
				return;
			}

			if (!string.Equals(Environment.MachineName, computerName, StringComparison.OrdinalIgnoreCase))
			{
				return;
			}

			test.RunState = RunState.Explicit;
			test.Properties.Set(PropertyNames.SkipReason, "Skipped on this computer.");
		}
	}
```

If I omit the `test.Properties.Set(...)` line, `nunit3-console` 3.0.1 crashes when attempting to pass a `null` string to `Regex.Replace`.

Runner output:
```
1) Error :
Exception has been thrown by the target of an invocation.

Server stack trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

```

Runner output, when run with `--inprocess`:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at NUnit.Framework.Interfaces.TNode.AddElementWithCDATA(String name, String value)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Api.FrameworkController.RunTests(ICallbackEventHandler handler, String filter)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

**Comment by CharliePoole** [comment]
Since the exception is actually thrown by the framework, can you tell us what version that is? This sounds a bit like something I've worked on.

**Comment by yaakov-h** [comment]
Also 3.0.1 (3.0.5813.39031).

**Comment by CharliePoole** [comment]
@yaakov-h I think it's possible that this is affected by an error that we fixed in 3.2, so you might give that a try.

Setting the runstate to explicit is a bit strange. Normally, I'd expect you to use skipped. Is it Explicit because you want to be able to run it by selecting on the command line, even though it's on the wrong machine?

Anyway, if you have looked at ExplicitAttribute, you'll see that it only sets the property if a non-null reason has been provided, and it doesn't seem to cause any crashes.

**Comment by yaakov-h** [comment]
I didn't think of using Skipped, but I do want to be able to run it by hand on that machine, just not when running everything in a CI build.

This works when using nunit-console 3.0.1 with nunit.framework 3.2.

ExplicitAttribute only sets it if a non-null reason is provided, but prior to 3.2 (b4cf0f65) it set the property every time.

I'd suggest that the additional null-check [here](https://github.com/nunit/nunit/commit/b4cf0f6516d2edb2b2628d838a67c702e40ffbd0#diff-579ce5bf37a84f3b75b49aa2d09c6a24R164) is what is allowing this to work now in 3.2.

Looks like mixing and matching 3.2 behaviour (current ExplicitAttribute code) with 3.0.1 (no null-check) is not a good idea :smile:

**Comment by CharliePoole** [comment]
That extra check was one of the fixes of course. Downstream programs were having a problem with empty elements in the XML.
