### ISSUE TITLE
Explore silently ignores an ITestBuilder that throws an exception

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#1381]
With a custom ITestBuilder that throws an exception, e.g.:

```
using System;
using System.Collections.Generic;
using NUnit.Framework.Interfaces;
using NUnit.Framework.Internal;

namespace NUnitCustomTestBuilder
{
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
	public sealed class MyTestCaseAttribute : Attribute, ITestBuilder
	{
		public IEnumerable<TestMethod> BuildFrom(IMethodInfo method, Test suite)
		{
			throw new InvalidOperationException("This is intentionally broken.");
		}
	}
}
```

**Test exploration silently ignores all tests in the fixture that this is applied within.**

For example, given an assembly with two test fixtures as follows:

```
using NUnit.Framework;

namespace NUnitCustomTestBuilder
{
	public class MyFixture
    {
		[Test]
		public void Foo()
		{
		}

		[TestCase("bar")]
		public void Bar(string bar)
		{
			Assert.That(bar, Is.EqualTo("bar"));
		}

		[MyTestCase]
		public void Baz(string baz)
		{
			Assert.That(baz, Is.EqualTo("baz"));
		}

    }
}
```

```
using NUnit.Framework;

namespace NUnitCustomTestBuilder
{
	class MyOtherFixture
	{
		[Test]
		public void Another()
		{
		}
	}
}
```

The only test reported by `nunit3-console --explore` is `NUnitCustomTestBuilder.MyOtherFixture.Another`. All of the `NUnitCustomTestBuilder.MyFixture` tests are nowhere to be seen.

They do not appear in the Visual Studio test adapter, either, and no error is printed to the Tests output dialog:

```
------ Discover test started ------
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering test is finished
========== Discover test finished: 1 found (0:00:00.1514981) ==========
```

The only way to discover this failure is to run `nunit3-console` across the entire assembly (without `--explore`). Only then does the error surface:

```
NUnit Console Runner 3.0.5813
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10240.0
  CLR Version: 4.0.30319.42000

Test Files
    NUnitCustomTestBuilder.dll


Errors and Failures

1) Invalid : NUnitCustomTestBuilder.MyFixture
An exception was thrown while loading the test.
System.InvalidOperationException: This is intentionally broken.
   at NUnitCustomTestBuilder.MyTestCaseAttribute.BuildFrom(IMethodInfo method, Test suite) in C:\Temp\NUnitCustomTestBuilder\NUnitCustomTestBuilder\MyTestCaseAttribute.cs:line 13
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)

Run Settings
    WorkDirectory: C:\temp\NUnitCustomTestBuilder\NUnitCustomTestBuilder\bin\Debug
    NumberOfTestWorkers: 12

Test Run Summary
    Overall result: Failed
   Tests run: 1, Passed: 1, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-03-29 03:04:14Z
    End time: 2016-03-29 03:04:14Z
    Duration: 0.085 seconds

Results (nunit3) saved as TestResult.xml
```

This ought to be reported as an error when using test exploration.

**Comment by CharliePoole** [comment]
Are you saying the fixture does not show up in the XML output from the command with --explore or only that it is not displayed in the default listing of test cases.

**Comment by yaakov-h** [comment]
It shows up in XML output as not-runnable, but does not show up in the VS test adapter or in plaintext Explore output (`--explore` only, not `--explore=blah.xml`).

```
     <test-suite type="TestFixture" id="0-1004" name="MyFixture" fullname="NUnitCustomTestBuilder.MyFixture" classname="NUnitCustomTestBuilder.MyFixture" runstate="NotRunnable" testcasecount="0">
        <properties>
          <property name="_SKIPREASON" value="An exception was thrown while loading the test.&#xD;&#xA;System.InvalidOperationException: This is intentionally broken.&#xD;&#xA;   at NUnitCustomTestBuilder.MyTestCaseAttribute.BuildFrom(IMethodInfo method, Test suite) in C:\Temp\NUnitCustomTestBuilder\NUnitCustomTestBuilder\MyTestCaseAttribute.cs:line 13&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)" />
        </properties>
      </test-suite>
```

What's the "default listing of test cases"?

**Comment by CharliePoole** [comment]
The default listing is what you see on the console if you specify just --explore. It's intended to only list test cases and is created from the XML. Because it only lists test cases, it doesn't give any indication that an invalid fixture was found.

What I'm seeing is that the console test execution does the right thing while the explore does something that could arguably be correct - it lists the test casees that were found, but not those that were not found. It's also possible we might want to give some error message with the explore. What do others think about this?

WRT the nunit adapter, it receives the information that is shown in the XML. Visual Studio only wants to get the test cases, so that's what the adapter reports. The only thing more it could do would be to display some error message in the Output window.

**Comment by yaakov-h** [comment]
WRT the adapter, I think an error message would be useful. It would have definitely saved me half an hour trying to figure out why my custom attribute causes all those tests to disappear (ended up being a NullReferenceException).

**Comment by CharliePoole** [comment]
Please add an issue to the NUnit3 adapter repo. It can refer to this one for details.

**Comment by ChrisMaddock** [comment]
> It's also possible we might want to give some error message with the explore. What do others think about this?

I'd agree we should have an error message - if any part of what you're trying to explore is invalid, you've not really got back what you've asked for. =)

**Comment by CharliePoole** [comment]
What about other ways were an exception is thrown? What if a TestCaseSource method throws?

**Comment by CharliePoole** [comment]
I upped the priority since it's blocking nunit/nunit3-vs-adapter#144

**Comment by CharliePoole** [comment]
Assigned to 3.4 in hopes we will fit it in! Also putting the adapter issue in it's 3.4 milestone.

**Comment by rprouse** [comment]
@CharliePoole I am pretty busy this weekend, so I won't get a chance to look at this for the release. I could delay to early next week if you feel we should get this in and you have time to do it.

**Comment by rprouse** [comment]
Moving out of the 3.4 release.

**Comment by OsirisTerje** [comment]
@rprouse @CharliePoole  This one is dormant.  And the corresponding https://github.com/nunit/nunit3-vs-adapter/issues/144  in the adapter is then dormant too.  Are we anywhere near being able to do something here?

**Comment by CharliePoole** [comment]
Some @nunit/framework-team member needs to assign it to themselves and work on it.

I take this issue to be making `--explore` show an error of some kind. Maybe with an extra option. However, that won't do anything for the adapter unless the error is then displayed somewhere. The key problem in the adapter is that it's a test fixture error and test fixtures don't have any good place to be displayed in the adapter.
