### ISSUE TITLE
NUnitLite fails to execute using .net core 

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [nunit/nunit#1404]
When attempting to run tests on .net core under NUnitLite 3.2.0 I get the following exception.  NUnitLite 3.0.1 does not have this issue. 

```
➜ dnx test
NUnitLite 3.2.0 (Portable)
Copyright (C) 2016 Charlie Poole

System.ArgumentException: Absolute path information is required.
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Reflection.RuntimeModule.get_FullyQualifiedName()
   at NUnitLite.TextRunner.Execute(TextUI textUI, NUnitLiteOptions options)
```

Program.cs
```cs
 new  NUnitLite.AutoRun(typeof(Program).GetTypeInfo().Assembly)
                .Execute(
                    args,
                    new ExtendedTextWrapper(Console.Out), 
                    Console.In 
                );
```

package.json
```
{
  "dependencies": {
    "app": "",
    "nunit": "3.2.0",
    "NUnitLite": "3.2.0"
  },

  "commands": {
    "test": "tests"
  },

  "frameworks": {
    "dnxcore50": {
    }  
  }
}

```

Environment info
```
OS X 10.11.4
DNVM 1.0.0-rc1-update1 coreclr  x64      ~/.dnx/runtimes default
```

**Comment by rprouse** [comment]
@chris-smith-zocdoc I cannot reproduce this. Maybe it is an OSX specific problem?

I have reports of other people using DNX successfully with 3.2 and it works for me. Since this doesn't look like a major regression, I am going to move out of the 3.2.1 milestone. If you can provide more details to help reproduce, it would be appreciated.

**Comment by chris-smith-zocdoc** [comment]
Quite possible, I'm going to close this out since we have rc2 now. I'll test out https://github.com/nunit/dotnet-test-nunit and see if the issue persists.

**Comment by chris-smith-zocdoc** [comment]
My tests successfully passed using https://github.com/nunit/dotnet-test-nunit with rc2 on osx 10.11
