### ISSUE TITLE
NUnit.Runner `AccessDenied` error while writing to test output directory

### ISSUE THREAD

**Issue by Aaronontheweb** [nunit/nunit#1424]
Using NUnit 3.latest in combination with FAKE, and I ran into the following issue:

```
System.UnauthorizedAccessException: Access to the path 'D:\Repositories\XPRD\Commons\TestResults' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at NUnit.ConsoleRunner.ConsoleRunner.CreateOutputWriter()
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
Running build failed.
Error:
Fake.UnitTestCommon+FailedTestsException: NUnit test failed. Process finished with exit code UnexpectedError (-100).
   at Fake.Testing.NUnit3.NUnit3(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\FAKE\src\app\FakeLib\UnitTest\NUnit\NUnit3.fs:line 280
   at FSI_0005.Build.clo@116-9.Invoke(Unit _arg6) in D:\Repositories\XPRD\Commons\build.fsx:line 121
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 484
```

There are no other processes on my end attempting to access this directory, and I do not have this issue with the NUnit 2.0 or XUnit 2.0 runners while also using a similar setup with FAKE. Any ideas as to what the issue might be and how I can work around it?

relevant FAKE configuration:

```fsharp
open Fake.Testing.NUnit3
Target "RunTests" <| fun _ ->
    let nunitTestAssemblies = !! "**/bin/Release/*Tests.dll"

    mkdir testOutput
    nunitTestAssemblies
    |> NUnit3 (fun p -> 
        {p with
            OutputDir = testOutput;
            ShadowCopy = false;
            ProcessModel = SingleProcessModel;
            TeamCity = true})
```

**Comment by Aaronontheweb** [comment]
Nevermind, we can close this - the `OutputDir` property is a misnomer. It's an output file.
