### ISSUE TITLE
Nunit exits saying Failed to start RemoteTestAgent

### ISSUE THREAD

**Issue by Karthikys6** [nunit/nunit#1431]
Hi there,

We are currently hit by the below problem when we pass .nunit file to nunit3-console.exe

Enviroment: NUnit.3.0.1 on WIndows Server 2012 R2

Failed to start RemoteTestAgent
System.Exception: Unable to acquire remote process agent
   at NUnit.Engine.Runners.ProcessRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Load()
   at NUnit.Engine.Runners.MasterTestRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEv
entListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter
 filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)

Could you please us to troubleshoot this problem.

Thanks,

**Comment by rprouse** [comment]
Can you tell us how you installed the nunit3 console, what version you are using and what command line you are using?

It sounds like you might have a bad install, or something in your tests is causing the agent to crash before it reports back to the runner. If it is crashing, you might be able to diagnose by running nunit console with the `--inprocess` command line to take the agent out of the picture.

**Comment by Karthikys6** [comment]
We are at: NUnit.3.0.1 and running via command line(Windows). 
I tired reinstalling but still it exits with the same error. Will try to diagnose as suggested.

Thanks for responding.

**Comment by rprouse** [comment]
@Karthikys6 I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
