### ISSUE TITLE
TestCase with generic return type causes NullReferenceException 

### ISSUE THREAD

**Issue by mbcrawfo** [nunit/nunit#1481]
NUnit v3.2.1, VS 2015 Update 2, Resharper 10.0.2 test runner.

The documentation isn't explicit, but from what I can find via googling `TestCase` does support generic test methods, though I haven't found anything yet mentioning generic return types.  Either way, I'm assuming a NRE is not desired/intended behavior.

Minimal reproduction:

    [TestFixture]
    public class MyTests
    {
      [TestCase(1, ExpectedResult = 1)]
      public T MyTest<T>(T arg1)
      {
        return arg1;
      }
    }

Output of running test:

    An exception was thrown while loading the test.
    System.NullReferenceException: Object reference not set to an instance of an object.
       at NUnit.Framework.Internal.AsyncInvocationRegion.IsAsyncOperation(MethodInfo method)
       at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature(TestMethod testMethod, TestCaseParameters parms)
       at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(IMethodInfo method, Test parentSuite, TestCaseParameters parms)
       at NUnit.Framework.TestCaseAttribute.<BuildFrom>d__63.MoveNext()
       at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
       at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture)
       at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
       at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext()
       at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)

**Comment by CharliePoole** [comment]
That's neat - a very good catch

**Comment by mbcrawfo** [comment]
Had a chance to tinker some this morning - the issue is that `MethodInfo.ReturnType.FullName` is null for a generic return type.  Since it's a one line fix I'm not not going to bother with a PR - see diff below (assuming C# 6 support :grinning: ).

    diff --git a/src/NUnitFramework/framework/Internal/AsyncInvocationRegion.cs b/src/NUnitFramework/framework/Internal/AsyncInvocationRegion.cs
    index f78f859..6503192 100644
    --- a/src/NUnitFramework/framework/Internal/AsyncInvocationRegion.cs
    +++ b/src/NUnitFramework/framework/Internal/AsyncInvocationRegion.cs
    @@ -67,7 +67,7 @@ at wrapping a non-async method invocation in an async region was done");
    
             public static bool IsAsyncOperation(MethodInfo method)
             {
    -            return method.ReturnType.FullName.StartsWith(TaskTypeName) ||
    +            return method.ReturnType.FullName?.StartsWith(TaskTypeName) ?? false ||
                        method.GetCustomAttributes(false).Any(attr => AsyncAttributeTypeName == attr.GetType().FullName);
             }

**Comment by rprouse** [comment]
Thanks, I will take a look.
