### ISSUE TITLE
NullReferenceException when null arguments are used in TestFixtureAttribute

### ISSUE THREAD

**Issue by danlyons-softek** [nunit/nunit#1507]
My team is in the process of trying to convert our unit tests from 2.6.4 to 3, and we ran into several errors while running the console runner (just using `nunit3-console.exe tests.dll`), similar to the following:

```
13) Invalid : Tests.Controls.Query.when_execute_is_clicked
An exception was thrown while loading the test.

System.NullReferenceException: Object reference not set to an instance of an object.
 at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.CheckTestFixtureIsValid(TestFixture fixture)
 at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
 at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext()
 at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)
```

This corresponds to the following test fixture and its constructor:
```
[TestFixture(null, "foo", "foo")]
[TestFixture("", "foo", "foo")]
[TestFixture("bar", "foo", "bar")]
public class when_execute_is_clicked : RefreshTestBase
{
    private string _selectedText;
    private string _query;
    private string _issuedQuery;

    public when_execute_is_clicked(string selectedText, string query, string issuedQuery)
    {
        _selectedText = selectedText;
        _query = query;
        _issuedQuery = issuedQuery;
    }
```

Judging by the code I see in master, it would appear the NRE is coming from [NUnitTestFixtureBuilder, line 229](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs#L229).

**Comment by rprouse** [comment]
Good catch, thanks for the pointer. We will get this fixed asap.
