### ISSUE TITLE
intermittent Failure on long running selenium tests

### ISSUE THREAD

**Issue by tanvirhussain** [nunit/nunit#1569]
Hi ,

We are facing some issue with our long running selenium tests. This is the command we are running 

```
nunit3-console.exe' 'Ve.Config.Tests.Acceptance.dll' --where "cat == SmokeTest" --verbose --result=TestResult.xml
```

I have checked the console output and none of the tests are failing but at the end we are reviving the following error and our TestResult.xml don't produce any result of the passed tests just the error. 

```
1) Error : 
15:27:27Info
Exception has been thrown by the target of an invocation.
15:27:27Info
Server stack trace: 
15:27:27Info
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
15:27:27Info
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
15:27:27Info
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
15:27:27Info
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
15:27:27Info
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
15:27:27Info
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
15:27:27Info
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
15:27:27Info
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
15:27:27Info
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
15:27:27Info
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
15:27:27Info
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
15:27:27Info
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
15:27:27Info
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
15:27:27Info
Exception rethrown at [0]: 
15:27:27Info
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
15:27:27Info
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
15:27:27Info
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
15:27:27Info
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
15:27:27Info
Test Run Summary
15:27:27Info
  Overall result: Failed
15:27:27Info
  Test Count: 0, Passed: 0, Failed: 0, Inconclusive: 0, Skipped: 0
```

We are capturing some screen shot on the   [AfterFeature("")] and  [AfterScenario("", Order = 0)] selenium attribute which is kind of same as TearDown attribute.

This is happening intermittently and as we don't have enough info it's hard to debug. 

Regards.

**Comment by bjharo** [comment]
I've seen this issue as well and I'm fairly certain that it is related to [this](https://github.com/nunit/nunit/issues/1509).

**Comment by tanvirhussain** [comment]
Thanks @bjharo 
Will have a look.

**Comment by rprouse** [comment]
The related issue is closed, so I am closing this as a duplicate. Please comment and reopen if I am incorrect.
