### ISSUE TITLE
Exception when using Ignore without IgnoreReason

### ISSUE THREAD

**Issue by MartinBannert** [nunit/nunit#1608]
nUnit 2.6.4:
When using the TestCase attribute together with the Ignore parameter, the report will not be created and an Exception is shown on the console:

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Util.XmlResultWriter.WriteCData(String text)
   at NUnit.Util.XmlResultWriter.WriteReasonElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
   at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
   at NUnit.Util.XmlResultWriter.SaveTestResult(TestResult result)
   at NUnit.ConsoleRunner.ConsoleUi.CreateXmlOutput(TestResult result)
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

The Testcase looks like this:
`[TestCase("foo", "bar", Ignore = true)]`

When adding the IgnoreReason attribute, the Exception does not occur
`[TestCase("foo", "bar", Ignore = true, IgnoreReason="whatever")]`

This behaviour is new in 2.6.4 but was working properly in 2.6.3  (without the need of the IgnoreReason).

Yours
Martin

**Comment by rprouse** [comment]
Thanks for the report. I don't think that we will be releasing a new version of 2.6 since we are now several releases into the 3.x stream, but we should confirm that this does not happen in 3.x.

As an aside, the reason that you ignore a test is now mandatory in NUnit 3. It is generally considered bad practice to ignore tests without explaining why, so this might be an opportunity for you to start getting your tests ready for NUnit 3 :wink:

**Comment by ChrisMaddock** [comment]
This is caught at compile time in v3.4 - Ignore and IgnoreReason both require a string parameter, and function as expected.

Based on your comment re: v2.6 @rprouse - I'll close.
