### ISSUE TITLE
Nunit 3.4.1 NUnit.Engine.Runners

### ISSUE THREAD

**Issue by elinato** [nunit/nunit#1671]
I run into problems, Nunit 3.4.1 sometimes doesn't terminate nunit-agent-x86.exe, using TeamCity

I get this from TeamCity:

`[Step 6/6] Unhandled Exception: System.InvalidOperationException: LocalDataStoreSlot storage has been freed.
[10:38:55][Step 6/6]    at System.LocalDataStore.SetData(LocalDataStoreSlot slot, Object data)
[10:38:55][Step 6/6]    at System.Threading.Thread.SetData(LocalDataStoreSlot slot, Object data)
[10:38:55][Step 6/6]    at System.Windows.Interop.ComponentDispatcher.get_CurrentThreadData()
[10:38:55][Step 6/6]    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
[10:38:55][Step 6/6]    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
[10:38:55][Step 6/6]    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
[10:38:55][Step 6/6]    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
[10:38:55][Step 6/6]    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[10:38:55][Step 6/6]    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
[10:38:55][Step 6/6]    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
[10:38:58][Step 6/6] System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
[10:38:58][Step 6/6] 
[10:38:58][Step 6/6] Server stack trace: 
[10:38:58][Step 6/6]    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
[10:38:58][Step 6/6] 
[10:38:58][Step 6/6] Exception rethrown at [0]: 
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
[10:38:58][Step 6/6]    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
[10:38:58][Step 6/6]    at NUnit.Engine.ITestEngineRunner.Unload()
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.ProcessRunner.UnloadPackage()
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.AbstractTestRunner.Unload()
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.AggregatingTestRunner.UnloadPackage()
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.AbstractTestRunner.Unload()
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.MasterTestRunner.UnloadPackage()
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.AbstractTestRunner.Dispose(Boolean disposing)
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing)
[10:38:58][Step 6/6]    at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
[10:38:58][Step 6/6]    at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
[10:38:58][Step 6/6]    at NUnit.ConsoleRunner.Program.Main(String[] args)
[10:38:58][Step 6/6] Process exited with code -100
[10:38:58][Step 6/6] Step Run tests (NUnit) failed`

**Comment by CharliePoole** [comment]
Based on the stacktrace, it does not seem to be the case that the agent process fails to terminate. In fact there is a SocketException with the message "An existing connection was forcibly closed by the remote host" which would usually indicate that the agent had already terminated.

That's a normal situation after a run has terminated so I'm uncertain why it causes a problem with Teamcity. Are you absolutely sure that TC is using NUnit 3.4.1?

**Comment by elinato** [comment]
In TeamCity I use this command line: packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe 

![image](https://cloud.githubusercontent.com/assets/20473726/16906726/b67d662e-4cbc-11e6-84b3-92194359f366.png)

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #31](https://github.com/nunit/nunit-console/issues/31) via [**ZenHub**](https://www.zenhub.com/)
