### ISSUE TITLE
NUnit failing after tests run under TeamCity

### ISSUE THREAD

**Issue by tomspilman** [nunit/nunit#1706]
I'm not sure what to make of this error:
```
NUnit error running tests in 'C:\BuildAgents\MonoGameWin1\work\b90cbe25f4aab321\Test\bin\Windows\AnyCPU\Debug\MonoGameTests.exe' assembly
Loading assembly is compiled for v4.0.30319, MSIL
NUnit runner runtime is v4.0.30319, x64
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Core.TestResult.AddResult(TestResult result)
   at JetBrains.TeamCity.NUnitLauncher.NUnitRunner.MergeResults(TestResult[] results) in c:\BuildAgent\work\ad31cec0a1b0f083\src\NUnitLauncher\src\NUnit-2.6\NUnitRunner.cs:line 124
   at JetBrains.TeamCity.NUnitLauncher.AssemblyTest.get_TestResults() in c:\BuildAgent\work\ad31cec0a1b0f083\src\NUnitLauncher\src\AssemblyTest.cs:line 98
   at JetBrains.TeamCity.NUnitLauncher.ProcessResultAction.Action(AssemblyTest test) in c:\BuildAgent\work\ad31cec0a1b0f083\src\NUnitLauncher\src\ProcessResultAction.cs:line 26
   at JetBrains.TeamCity.NUnitLauncher.TryOneAssemblyTest.Action() in c:\BuildAgent\work\ad31cec0a1b0f083\src\NUnitLauncher\src\TryOneAssemblyTest.cs:line 18
   at JetBrains.TeamCity.NUnitLauncher.TryOneAssembly.Do() in c:\BuildAgent\work\ad31cec0a1b0f083\src\NUnitLauncher\src\TryOneAssembly.cs:line 36
Check correct .NET Framework version and process platform (x64, x86, MSIL) are used both in the test runner settings and involved assemblies on this machine.
```
It just looks like a failure of some sort in TeamCity when gathering results.

**Comment by CharliePoole** [comment]
Me either. :-)

Apparently, TeamCity is trying to add a null result to the result of a test suite.  Where it gets that result from is the question.

Have you checked what it suggests? What happens if you run the same tests at the command-line, without using TeamCity?

**Comment by tomspilman** [comment]
> What happens if you run the same tests at the command-line, without using TeamCity?

I'll give that a try... but my guess is that this is just a TeamCity issue of some sort.

I'll follow up with them on it.

Thanks @CharliePoole !

**Comment by NikolayPianikov** [comment]
@tomspilman could you create issue in our bug tracker: https://youtrack.jetbrains.com/
Also if you would added a snapshot of your build step, build log file and a sample to reproduce it would be good.

**Comment by tomspilman** [comment]
@NikolayPianikov - I'll see what I can do... pretty busy right now.  The issue seems to occur at other places too.  I've put an issue up on our own GitHub repo to investigate it further:

https://github.com/mono/MonoGame/issues/5042
