### ISSUE TITLE
Serialization Security Exception: System.Runtime.Remoting.ObjRef cannot be accessed (since v2.6.2 to v3.4.1)

### ISSUE THREAD

**Issue by gabrielpalacios** [nunit/nunit#1817]
In top level integration tests i'm experiencing remoting security exceptions.
2.6.1 no problem, 2.6.2 to 3.4.1 has this exception -- no other changes in the source.

Exception thrown when attempting a request:
**System.Runtime.Serialization.SerializationException : Because of security restrictions, the type System.Runtime.Remoting.ObjRef cannot be accessed.**

**There are old good entries about it:**
https://bugs.launchpad.net/nunitv2/+bug/1086975
http://osdir.com/ml/nunit-discuss/2012-11/msg00061.html

It seems as though it affects accessing any object byRef over the remoting channel. Unfortunately, we don't own the server side of our .NET Remoting and I'm not sure how our vendor is going to feel about applying the config based fix on their end.

app or web.config:

```xml
 <system.runtime.remoting>
    <application>
      <service>
        <wellknown mode="SingleCall"  type="Pro.ServiFacade, Pro.Security" objectUri="SecurityFacade.rem"/>
      </service>
      <channels>
        <channel ref="http" port="0">
          <clientProviders>
            <formatter ref="binary" typeFilterLevel="Full" />
            <formatter ref="soap" typeFilterLevel="Full" />
          </clientProviders>
          <serverProviders>
            <formatter ref="binary" typeFilterLevel="Full" />
            <formatter ref="soap" typeFilterLevel="Full" />
          </serverProviders>
         </channel>
      </channels>
    </application>
  </system.runtime.remoting>
```

**System.Runtime.Serialization.SerializationException - Details Follow:**

```
System.Runtime.Serialization.SerializationException: Because of security restrictions, the type System.Runtime.Remoting.ObjRef cannot be accessed. ---> System.Security.SecurityException: Request failed.
   at System.Runtime.Serialization.FormatterServices.nativeGetSafeUninitializedObject(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(Type type)
The action that failed was:
Demand
The type of the first permission that failed was:
System.Security.Permissions.SecurityPermission
The first permission that failed was:
<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
version="1"
Flags="Infrastructure"/>

The demand was for:
<PermissionSet class="System.Security.PermissionSet"
version="1">
<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
version="1"
Flags="Infrastructure"/>
</PermissionSet>

The only permitted permissions were:
<PermissionSet class="System.Security.PermissionSet"
version="1">
<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
version="1"
Flags="SerializationFormatter"/>
</PermissionSet>

The method that caused the failure was:
System.Runtime.Remoting.Channels.ServerProcessing ProcessMessage(System.Runtime.Remoting.Channels.IServerChannelSinkStack, System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Channels.ITransportHeaders, System.IO.Stream, System.Runtime.Remoting.Messaging.IMessage ByRef, System.Runtime.Remoting.Channels.ITransportHeaders ByRef, System.IO.Stream ByRef)
   --- End of inner exception stack trace ---
```

Server stack trace:

```
   at System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(Type type)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)
   
```

**Comment by rprouse** [comment]
@gabrielpalacios does adding the suggested configuration changes to `nunit-agent.exe.config` work?

**Comment by rprouse** [comment]
This is also likely an NUnit Console bug, we will likely move it to that repository once we evaluate it.

**Comment by rprouse** [comment]
@gabrielpalacios I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Comment by rprouse** [comment]
If you can provide us with code that we can use to reproduce the problem, I will reopen.
