### ISSUE TITLE
Creation of TestExecutionContext should be explicit

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2050]
Originally, in V2,  it seemed to make sense to set `CurrentContext` lazily to a new context in the getter, whenever it was found to be null.

Now, with parallel dispatching, things are more complicated. The context is  changed as different tests begin to execute and the current work item both controls and depends upon it's content. When the context is discovered to be null, it's an error that we should not be masking.

The basic refactoring here is
* Make the getter function as a simple getter, returning null if that's what is found.
* Remove the `GetTestExecutionContext()` method, replacing all calls with use of the property.
* Discover all points in the code where the context is found to be null, and fix them.

Obviously, the last point is going to be difficult.

**Comment by CharliePoole** [comment]
The following issues relate to this refactoring and - even if not dependent on it - may need to be delayed until this one is done: #2035, #2025, #1965, #1952 

What they all share in common is that when there is no `CurrentContext` a sort of "dummy" context is created, in which none of the properties are initialized properly.

**Comment by CharliePoole** [comment]
Commenting out the lines that create a new context when `TestExecutionContext.CurrentContext` would otherwise return null gives me five errors and failures in the framework tests (.NET 4.5).

```
1) Invalid : NUnit.Framework.Tests.TestContextTests.TestCaseSourceCanAccessTestDirectory
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.TestContext.get_TestDirectory() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\TestContext.cs:line 131
   at NUnit.Framework.Tests.TestContextTests.<MySource>d__8.MoveNext() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\tests\TestContextTests.cs:line 80
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 177

2) Error : NUnit.Framework.Tests.TestContextTests.TestExecutionContext_ShouldFlowWithAsyncExecution_ExecutedInParallel
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.Assert.IncrementAssertCount() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.cs:line 407
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.That.cs:line 244
   at NUnit.Framework.Assert.AreSame(Object expected, Object actual) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.Equality.cs:line 194
   at NUnit.Framework.Tests.TestContextTests.<<TestExecutionContext_ShouldFlowWithAsyncExecution_ExecutedInParallel>b__33_0>d.MoveNext() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\tests\TestContextTests.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Tests.TestContextTests.<TestExecutionContext_ShouldFlowWithAsyncExecution_ExecutedInParallel>d__33.MoveNext() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\tests\TestContextTests.cs:line 294
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Internal\ExceptionHelper.cs:line 64
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Internal\AsyncInvocationRegion.cs:line 114
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 92

3) Error : NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.Assert.IncrementAssertCount() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.cs:line 407
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.That.cs:line 244
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.That.cs:line 228
   at NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\tests\Api\FrameworkControllerTests.cs:line 263

4) Error : NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.Assert.IncrementAssertCount() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.cs:line 407
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.That.cs:line 244
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.That.cs:line 228
   at NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\tests\Api\FrameworkControllerTests.cs:line 312

5) Error : NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.Assert.IncrementAssertCount() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.cs:line 407
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.That.cs:line 244
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression) in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\framework\Assert.That.cs:line 228
   at NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite() in C:\Dev\NUnit\nunit-3.0\src\NUnitFramework\tests\Api\FrameworkControllerTests.cs:line 295
```

Here are notes on each error

1) This is due to accessing the `TestContext` when loading tests, specifically the `TestDirectory` property. We need a better solution to access to the context at load time, with support for properties like `TestDirectory` that make sense and explicit errors for those that are not supported, like `CurrentTest` and `CurrentResult`.

2) This is due to the context failing to flow across the threads in an async test. The creation of a dummy context was hiding most errors in this case, but not all and made it harder to detect the problem in the first place. This is the same issue as #1965

3) This is due to calling the `FrameworkController` within a test to run second-level tests. It's the same problem pointed out by #2035.

4) Same as 3

5) Same as 3
