### ISSUE TITLE
Exception in LaunchAgentProcess when running under TeamCity

### ISSUE THREAD

**Issue by sliddington** [nunit/nunit#2053]
Any ideas what this might be. Seems to be a problem in the test runner itself. Command line options are nunit3-console.exe 'assemblies' --teamcity --x86 --workers=0 --process=Multiple --where cat=UnitTest (I added --workers=0 --process=Multiple to try to fix the issue).

The odd thing is this has not happened when I run the same command line from a command prompt.

Teamcity version is 9.1 (build 36973), Nuget Package versions are:

```
<package id="NUnit.Console" version="3.6.0" />
<package id="NUnit.ConsoleRunner" version="3.6.0" />
<package id="NUnit.Extension.NUnitProjectLoader" version="3.5.0" />
<package id="NUnit.Extension.NUnitV2Driver" version="3.6.0" />
<package id="NUnit.Extension.NUnitV2ResultWriter" version="3.5.0" />
<package id="NUnit.Extension.TeamCityEventListener" version="1.0.2" />
<package id="NUnit.Extension.VSProjectLoader" version="3.5.0" />
<package id="NUnit3TestAdapter" version="3.7.0" />

  <package id="AutoFixture" version="3.50.2" targetFramework="net462" />
  <package id="AutoFixture.AutoFakeItEasy" version="3.50.2" targetFramework="net462" />
  <package id="AutoFixture.NUnit3" version="3.50.2" targetFramework="net462" />
  <package id="FakeItEasy" version="2.3.3" targetFramework="net462" />
  <package id="log4net" version="2.0.3" targetFramework="net45" />
  <package id="NUnit" version="3.6.0" targetFramework="net462" />
```

This is the output in the error summary (some of them, there were more of the same exception)...
```
[01:19:20][Exec] EXEC D:\work\BLINDS-v16.4.2.0_NUnit3\Shared\Core\NonWeb.UnitTests\bin\Release\Accent.Core.NonWeb.UnitTests.dll
[01:19:20][Exec] Object reference not set to an instance of an object.
[01:19:20][Exec] at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
[01:19:20][Exec] at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
[01:19:20][Exec] at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
[01:19:20][Exec] at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
[01:19:20][Exec] at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
[01:19:20][Exec]
[01:19:20][Exec] EXEC D:\work\BLINDS-v16.4.2.0_NUnit3\Shared\Core\Service.Contracts.UnitTests\bin\Release\Accent.Core.Service.Contracts.UnitTests.dll
[01:19:20][Exec] Object reference not set to an instance of an object.
[01:19:20][Exec] at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
[01:19:20][Exec] at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
[01:19:20][Exec] at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
[01:19:20][Exec] at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
[01:19:20][Exec] at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
[01:19:20][Exec]
```

Another slightly different example:
```
`[12:42:03][Exec] EXEC D:\work\BLINDS-v16.4.2.0_NUnit3\Shared\Core\Service.Contracts.UnitTests\bin\Release\Accent.Core.Service.Contracts.UnitTests.dll
[12:42:03][Exec] Index was outside the bounds of the array.
[12:42:03][Exec] at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
[12:42:03][Exec] at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
[12:42:03][Exec] at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
[12:42:03][Exec] at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
[12:42:03][Exec] at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
[12:42:03][Exec]
[12:42:03][Exec] EXEC D:\work\BLINDS-v16.4.2.0_NUnit3\Shared\Core\Service.UnitTests\bin\Release\Accent.Core.Service.UnitTests.dll
[12:42:03][Exec] Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
[12:42:03][Exec] at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
[12:42:03][Exec] at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
[12:42:03][Exec] at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
[12:42:03][Exec] at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
[12:42:03][Exec] at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
[12:42:03][Exec] at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
[12:42:03][Exec] at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)`
```

**Comment by ChrisMaddock** [comment]
This looks to be the same issue as https://github.com/nunit/nunit-console/issues/168.

@sliddington - I'm going to close as a duplicate - if the workaround on the above issue doesn't work, let us know and we can reopen and investigate further.

**Comment by sliddington** [comment]
Yes, the workaround seems to have done the trick.
I'll keep an eye out for the fix.
Thanks!

**Comment by sliddington** [comment]
Is there a way to specify --agents=1 programmatically or tell the VS test adapter to use this setting?

**Comment by ChrisMaddock** [comment]
Yes - the VS adapter shouldn't have this problem, it runs tests in-process, i.e. with no agents. So there's no need to override.
