### ISSUE TITLE
NullReferenceException when using Assert in TestCaseSource

### ISSUE THREAD

**Issue by LiyueWang** [nunit/nunit#2267]
I have upgraded NUnit from 3.6.1 to 3.7.1, and tests with the below structure now throw an `NullReferenceException` , caused by the `Assert.That` in the static `TestCasesMethod()`. It works in Nunit 3.6.1 but not 3.7.1, Is this intended?

```
        [TestFixture]
	class TestSample1 {

		private static IEnumerable<TestCaseData> TestCasesMethod() {
			int age_sara = 21;
			Assert.That( age_sara, Is.GreaterThanOrEqualTo( 20 ) );
			return new TestCaseData[] { new TestCaseData( age_sara, "Sara" ), new TestCaseData( 23, "Liyue" ) };
		}

		[Test, TestCaseSource( nameof( TestCasesMethod ) )]
		public void test_1(int age, string name) {
			Console.WriteLine("name: "+name);
			Assert.That(age, Is.GreaterThan(20));
		}
	}
```

```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(IMethodInfo method)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
--NullReferenceException
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
   at Nunit3TestsSamples.TestSample1.TestCasesMethod() in C:\D2L-Littlefoot\RewriteNUnit3\Nunit3TestsSamples\TestSample1.cs:line 14
```

**Comment by CharliePoole** [comment]
While asserts were never intended to work outside of a test method, they didn't blow up so spectacularly in the past. Even in earlier releases, only a successful assert worked correctly. A failing assert threw an Assertion exception, which NUnit did not recognize or report as a failure. Rather it was treated like any other unhandled exception, causing the test to be invalid.

In 3.7, we introduced changes that led to a null reference when an assert is executed without a valid execution context. Issue #2242 deals with this problem and will probably result in a better error message in your situation, but not in making asserts usable outside of a test.

Your example code is designed to illustrate the problem but isn't a real example. If you can show or describe an actual use case for this pattern,  we can suggest better ways to handle it with NUnit.

**Comment by LiyueWang** [comment]
@CharliePoole Thanks!

Good to know and agree with that 
> asserts were never intended to work outside of a test method

In our real code, I found someof us used the `TryGet` pattern to get some values of the `TestCaseData`, and use `Assert.IsTrue` to throw exception if failed to get the values. It seems not a proper way to use `Assert`, we could throw exception explicitly if get values failed.
