### ISSUE TITLE
Using SetUp attribute with parallelizable atrribute creates conflicts in variables.

### ISSUE THREAD

**Issue by azakharov3** [nunit/nunit#2341]
NUnit Version: 3.7.0
Sorry in advance if it is by design but looks like assigning values to variables in [Setup] method creates conflicts. Please see the example code below:

```
using NUnit.Framework;
namespace UnitTests
{
    class Class1
    {
        private int testValue;

        [SetUp]
        public void BeforeEveryTest()
        {
            testValue = 2;
        }


        [Test, Parallelizable]
        public void Test1()
        {
            testValue++;
            Assert.That(testValue, Is.EqualTo(3));
        }

        [Test, Parallelizable]
        public void Test2()
        {
            testValue = testValue * 10;
            Assert.That(testValue, Is.EqualTo(20));
        }

        [Test, Parallelizable]
        public void Test3()
        {
            testValue = testValue * 3;
            Assert.That(testValue, Is.EqualTo(6));
        }
    }
}
```

Result:
```
Errors, Failures and Warnings

1) Failed : UnitTests.Class1.Test3
  Expected: 6
  But was:  60
at UnitTests.Class1.Test3() in C:\Users\azakharov\Documents\GitHub\IntegrationTests\UnitTests\Class1.cs:line 34

2) Failed : UnitTests.Class1.Test1
  Expected: 3
  But was:  61
at UnitTests.Class1.Test1() in C:\Users\azakharov\Documents\GitHub\IntegrationTests\UnitTests\Class1.cs:line 20
```

**Comment by CharliePoole** [comment]
This is by design. You can run fixtures in parallel if the individual tests interfere with one another.

Essentially, by using Parallelizable, you are promising not to modify state but NUnit can't prevent you from doing it.
