### ISSUE TITLE
WorkItemQueue is not thread safe

### ISSUE THREAD

**Issue by garuma** [nunit/nunit#2417]
General note: there are various things in this class that makes me itchy, it would really be better if this used something like `BlockingCollection` instead of rolling its own CAS logic (importing it in the source tree if necessary for earlier .NET). I pushed a possible re-implementation at: https://github.com/garuma/nunit/commit/da63106d8119ab4b32e48fbe0ed63ad88d3ed9a3

On the core of the issue though, with NUnit 3.8 running our test suite started throwing NREs:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at NUnit.Framework.Internal.Execution.WorkItemQueue.Dequeue()
    at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    at **System.Threading.ThreadHelper.ThreadStart()**
```

This seems to come from the queue array having null in it. In turn, I believe this is due to `InitializeQueues` being not concurrency safe, creating an array and initializing it directly on shared state.

Looking at the commit I referenced above, using my slightly different `CreateQueues` way makes it concurrent-safe.

**Comment by CharliePoole** [comment]
Yes, I believe you're right. `InitializeQueues` was not written to be thread-safe - and originally didn't need to be. But when we introduced the `Save` and `Restore` operations, it began to be called on worker threads and should have been made thread-safe.

I would hesitate to introduce a complete re-implementation - at least not without a great deal of review. Could you give a brief summary of why you find`BlockingCollection` more suitable than `ConcurrentQueue`?

**Comment by garuma** [comment]
Sure, the approach you have currently (monotonic dual integers manipulated via CAS) actually used to be how `BlockingCollection` worked on Mono (now that we use referencesource it's slightly different).

Some of the bits though are technically not necessary (your `Enqueue` operation doesn't need a CAS, the ticket form of Dequeue adds overhead, ...) and overall using `BlockingCollection` would reduce your code because it is a full implementation of a producer-consumer pattern like you are trying to do (with the added advantage that's guaranteed to be fully thread-safe and concurrent-safe). It actually relies on the same `ConcurrentQueue` you are using already to act as a safe storage underneath. Since you are already importing `ConcurrentQueue` from the framework for older runtime, adding `BlockingCollection` shouldn't be much worse.

Now the extra complication in there is due to the Pause state (implemented in my patch with an external `CancellationTokenSource`). If the sole reason for having `Pause` is to swap the queues, then the implementation can be simplified further using `Exchange` (I kept Pause in my commit to have the current unit-tests run verbatim).

**Comment by ChrisMaddock** [comment]
I've marked this critical - we were seeing a few of these excpeptions which were preventing us from moving to 3.8. I think this should go in a hotfix, with the Collection changes as well.

**Comment by CharliePoole** [comment]
Completely reimplement as a hotfix? What @garuma says makes sense but hotfixes are supposed to be closely targeted bug fixes.

**Comment by ChrisMaddock** [comment]
I meant fixing the NullReferenceExceptions as a hotfix.

**Comment by CharliePoole** [comment]
Good! We have been getting into trouble, it seems, by rushing things. Should we split this issue?

**Comment by ChrisMaddock** [comment]
Can do. Afraid I'm away for a week tomorrow, so won't be able to do any of the code for this.

**Comment by ChrisMaddock** [comment]
See https://github.com/nunit/nunit/issues/2428. I'll rename this issue to make it more general.

**Comment by CharliePoole** [comment]
@garuma We have done some minimal fixes for immediate release and I think it's now a good time to look at the full refactoring. Is it possible for you to rework your changes against the current master and create a PR?

**Comment by garuma** [comment]
Sorry for the late reply. Yes I will try to redo the patch, if I recall that was contingent on bringing `BlockingCollection` from the framework as well (under src/NUnitFramework/framework/Compatibility/System.Collections.Concurrent), is that something you would be ok with?

**Comment by oznetmaster** [comment]
At the time I wrote the existing code, I suggested bringing BlockingCollection as well as ConcurrentQueue into the compatibility namespace.

ConcurretQueue won.  There was a desire to port as few as possibile.

I see no reason why BlockingCollection should not also be ported.  I ported from mono.

**Comment by jnm2** [comment]
https://github.com/dotnet/corefx/commits/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/BlockingCollection.cs (MIT license) has also had recent performance improvements.

**Comment by CharliePoole** [comment]
@garuma I think porting a good version of BlockingCollection for the builds that need it is perfectly reasonable.

Bear in mind that folks will need to review the PR and that I'm not the deciding voice here. I __think__ we are ready to do a re-implementation of our `WorkItemQueue` but I'm not the final voice. @rprouse what do you say?

One big thing to decide - if you haven't already - is how to handle the save / restore functions. The way I did it was internally in `WorkItemQueue`. An alternative is to make it external - that is to create an entire new WIQ when doing the save. That might make it easier to save and restore all the queues in one operation, either under control of the dispatcher or of a class created just for the purpose.

**Comment by oznetmaster** [comment]
If the CoreFx BlockingCollection were to be used, I would suggest that the CoreFx ConcurrentQueue be used as well.

**Comment by rprouse** [comment]
I am also in favor of bringing BlockingCollection across and everyone knows I am in favor of refactoring `WorkItemQueue`. That said, any refactor will need extensive review and testing. We've just gotten through a period of instability that I would prefer not to get back into 😄

**Comment by CharliePoole** [comment]
It seems like this needs to be done early in a release cycle, i.e. starting a few months before we plan a release.

**Comment by rprouse** [comment]
> It seems like this needs to be done early in a release cycle, i.e. starting a few months before we plan a release.

I totally agree. @garuma you are welcome to start work on this, but be aware that it will not be merged before the next release which is currently scheduled for end Feb.

**Comment by jnm2** [comment]
I should probably comment before I forget that I ported BlockingCollection to net20 and didnt' end up needing it for something else. Saved the work at jnm2/nunit@e4e81a2.
