### ISSUE TITLE
Has.Property causes AmbiguousMatchException for shadowing properties

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2422]
```cs
ThirdPartyFoo actual = new ThirdPartyFooEx();
ThirdPartyFoo expected = new ThirdPartyFooEx();

Assert.That(actual, Has.Property(nameof(expected.Options)).EqualTo(expected.Options));
```

Causes:

> ```
> System.Reflection.AmbiguousMatchException : Ambiguous match found.
>    at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
>    at System.Type.GetProperty(String name, BindingFlags bindingAttr)
>    at NUnit.Framework.Constraints.PropertyConstraint.ApplyTo[TActual](TActual actual)
>    at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
>    at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
>    at NUnit_repro.SomeFixture.SomeTest()
> ```

Given:

```cs
public class ThirdPartyFooOptions
{
}

public class ThirdPartyFoo
{
    public ThirdPartyFooOptions Options { get; }
}

public class ThirdPartyFooExOptions : ThirdPartyFooOptions
{
}

public class ThirdPartyFooEx : ThirdPartyFoo
{
    public new ThirdPartyFooExOptions Options => (ThirdPartyFooExOptions)base.Options;
}
```

We should be settling on the ultimate shadowing property, right? This is how `dynamic` would handle the situation and it makes sense to me since we likewise don't know the compile-time type of the expression being passed into `Assert.That` because that's not how we roll. In other words, `2` is printed for:

```cs
dynamic expected = new ThirdPartyFooEx();
Debug.WriteLine((int)expected.Options);

public class ThirdPartyFoo
{
    public int Options => 1;
}

public class ThirdPartyFooEx : ThirdPartyFoo
{
    public new int Options => 2;
}
```

So I think we should match that. I expect all .NET languages with dynamic features to treat IL shadowing the same.

**Comment by jnm2** [comment]
We're going to have to do something a little smarter here:

https://github.com/nunit/nunit/blob/d72eede48b2a86a0de9553876481195888ae0ea0/src/NUnitFramework/framework/Constraints/PropertyConstraint.cs#L65-L66

**Comment by jnm2** [comment]
Ah, I think this is our compatibility ReflectionExtensions kicking in.

**Comment by jnm2** [comment]
> Ah, I think this is our compatibility ReflectionExtensions kicking in.

Never mind, it's not.

**Comment by jnm2** [comment]
Ah, it's only ambiguous when the property type differs, even without a setter. Makes sense because it's hidebysig and the getter return type is considered part of the signature.

**Comment by jnm2** [comment]
These are the test cases we should add:

```cs
public class BaseClass
{
    public object SomeProperty => 2;
}

public class ClassWithShadowingProperty : BaseClass
{
    public new int SomeProperty => 2;
}

public class DerivedClassWithoutProperty : ClassWithShadowingProperty
{
}

public class PropertyExistsTests
{

    [Test]
    public static void ShadowingPropertyOfDifferentType()
    {
        var instance = new DerivedClassWithoutProperty();
        Assert.That(instance, Has.Property(nameof(instance.SomeProperty)));
    }
}

public class PropertyTests
{

    [Test]
    public static void ShadowingPropertyOfDifferentType()
    {
        var instance = new DerivedClassWithoutProperty();
        Assert.That(instance, Has.Property(nameof(instance.SomeProperty)).EqualTo(instance.SomeProperty));
    }
}
```

**Comment by jnm2** [comment]
Tests:

```cs
public class BaseClass
{
    public object PublicProperty => 1;
    private object PrivateProperty => 1;
    public object PublicPropertyPrivateShadow => 1;
}

public class ClassWithShadowingProperty : BaseClass
{
    public new int PublicProperty => 2;
    private new int PrivateProperty => 2;
    private new int PublicPropertyPrivateShadow => 2;
}

public class DerivedClassWithoutProperty : ClassWithShadowingProperty
{
}

public class PropertyExistsTests
{
    [TestCase("PublicProperty")]
    [TestCase("PrivateProperty")]
    [TestCase("PublicPropertyPrivateShadow")]
    public static void ShadowingPropertyOfDifferentType(string propertyName)
    {
        var instance = new DerivedClassWithoutProperty();
        Assert.That(instance, Has.Property(propertyName));
    }
}

public class PropertyTests
{
    [TestCase("PublicProperty", true)]
    [TestCase("PrivateProperty", true)]
    [TestCase("PublicPropertyPrivateShadow", false)]
    public static void ShadowingPropertyOfDifferentType(string propertyName, bool shouldUseShadowingProperty)
    {
        var instance = new DerivedClassWithoutProperty();
        Assert.That(instance, Has.Property(propertyName).EqualTo(shouldUseShadowingProperty ? 2 : 1));
    }
}
```

**Comment by jnm2** [comment]
Implementation:

```cs
private static PropertyInfo GetUltimateShadowingProperty(Type type, string name, BindingFlags bindingFlags)
{
    if (type == null) throw new ArgumentNullException(nameof(type));
    if (name == null) throw new ArgumentNullException(nameof(name));

    if ((bindingFlags & BindingFlags.DeclaredOnly) != 0)
    {
        // If you're asking us to search a hierarchy but only want properties declared in the given type,
        // you're in the wrong place but okay:
        return type.GetProperty(name, bindingFlags);
    }

    if ((bindingFlags & (BindingFlags.Public | BindingFlags.NonPublic)) == (BindingFlags.Public | BindingFlags.NonPublic))
    {
        // If we're searching for both public and private properties, search for only public first
        // because chances are if there is a public property, it would be very surprising to detect the private shadowing property.

        for (var publicSearchType = type; publicSearchType != null; publicSearchType = publicSearchType.BaseType)
        {
            var property = publicSearchType.GetProperty(name, (bindingFlags | BindingFlags.DeclaredOnly) & ~BindingFlags.NonPublic);
            if (property != null) return property;
        }

        // There is no public property, so may as well not ask to include them during the second search.
        bindingFlags &= ~BindingFlags.Public;
    }

    for (; type != null; type = type.BaseType)
    {
        var property = type.GetProperty(name, bindingFlags | BindingFlags.DeclaredOnly);
        if (property != null) return property;
    }

    return null;
}
```
