### ISSUE TITLE
Stack trace shown for Assert.Warn

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2429]
@jnm2 commented on [Fri Sep 08 2017](https://github.com/nunit/nunit-console/issues/287)

I'm having a hard time reading my build logs because every Assert.Warn puts 40-50 lines of stack trace under the message. I only see this when looking at NUnit console output.

Is this by design? Is there a way to disable this?

---

@CharliePoole commented on [Fri Sep 08 2017](https://github.com/nunit/nunit-console/issues/287#issuecomment-328222728)

Yes. Make this issue a bug and somebody will fix it. 😄 

Our StackTrace filter removes certain class entries from the top of the stack. Most likely, being new, `Warn` isn't one of them. Alternatively, it may only do it for failures. Somebody should fix it.

---

@CharliePoole commented on [Sat Sep 09 2017](https://github.com/nunit/nunit-console/issues/287#issuecomment-328309089)

Actually, if you decide this should be fixed, it's a framework issue.

---

@jnm2 commented on [Sat Sep 09 2017](https://github.com/nunit/nunit-console/issues/287#issuecomment-328310341)

Thanks Charlie, will move.

**Comment by CharliePoole** [comment]
@jnm2 I cannot confirm this. Here's what I have done.
1. Added a simple Assert.Warn and ran under the nunitlite runner. I get a single entry stack trace showing where the message occured.
2. Ran it under the console runner and didn't see any message at all. Is the console runner not displaying warnings?
3. Added an assertion to the failure tests in WarningTests, which verifies that all the stack traces have either one or two lines - the async methods get an extra line.

Can you either provide some code that repros this or give more exact instructions as to how to see the problem?

**Comment by jnm2** [comment]
I see that the console does not show warning messages unless there is at least one failure. Separat eissue could be opened if that isn't by design.

The multiline stack trace appears to happen whenever you're in an async test and warn *or* fail after an `await`:

```cs
[Test]
[Test]
public static async Task WarningTest()
{
    await Task.Yield();
    Assert.Warn("(Warning message)");
}

[Test]
public static async Task FailingTest()
{
    await Task.Yield();
    Assert.Fail("(Failure message)");
}
```

**Comment by jnm2** [comment]
This is specifically what I'm seeing in the real-world project:
```
at Redacted1.<Redacted2>d__5.MoveNext()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
at Redacted3.<Redacted4>d__17.MoveNext()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
at Redacted5.<Redacted6>d__36.MoveNext()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at System.Threading.Tasks.Task.WhenAllPromise`1.Invoke(Task ignored)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
at Redacted7.<Redacted8>d__42.MoveNext()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
at Redacted9.<Redacted10>d__51.MoveNext()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by jnm2** [comment]
My repro isn't good enough though. I should try for a better one.

**Comment by jnm2** [comment]
Got a before/after.

**Comment by jnm2** [comment]
Figured it out.

**Comment by CharliePoole** [comment]
It seems like you want to see warnings if you're issuing them. 😄 

WRT the example stack trace, what would you want to see? Just the first line?

What did you figure out?

**Comment by jnm2** [comment]
Repro conditions:

 - Test DLL must be compiled with optimizations (release mode)
 - There must be at least one failure
 - The warn must happen in a new call stack (caused in this case by async trampolining)

[NUnit warn repro.zip](https://github.com/nunit/nunit/files/1290955/NUnit.warn.repro.zip)

Unzip and execute `.\build.ps1`.

**Comment by jnm2** [comment]
If you really want to see something cool, run it with this:

```cs
[Test]
public static void FailingTest()
{
    Assert.Fail("(Failure message)");
}

[Test]
public static async Task WarningTest()
{
    await Recurse(10);
    Assert.Warn("(Warning message)");
}

private static async Task Recurse(int times)
{
    await (times > 0 ? Recurse(times - 1) : Task.Delay(1));
}
```

**Comment by jnm2** [comment]
The problem is that NUnit doesn't shorten the call stack when `Assert.Warn` is called on another thread.

**Comment by jnm2** [comment]
The problem is that NUnit doesn't shorten the call stack when `Assert.Warn` is called on another thread, even though the exception is handled and passed nicely to NUnit via the `Task` instance returned by the test method.

There is a chance this would be fixed when I do the awaitables PR I wanted to do awhile back that I need to pick up again.
Related: https://github.com/nunit/nunit/issues/1200#issuecomment-312121166

**Comment by CharliePoole** [comment]
Currently, we trim the top and bottom of the stack trace. I can't see that working very well here. What do you think we should do?

**Comment by CharliePoole** [comment]
What do you mean "the exception is handled?" There is no exception involved in a warning.

**Comment by jnm2** [comment]
@CharliePoole I thought it threw a WarningException, but never mind then.

For one thing, some stack frames are annotated with [Resuming Async Method]:

![image](https://user-images.githubusercontent.com/8040367/30253351-f8b33d0a-9650-11e7-99ae-383c32f6764c.png)

We could trim those maybe?

**Comment by jnm2** [comment]
I could see it making sense to either

 - Throw away all frames from the top `[Resuming Async Method]` line to the bottom
 -

**Comment by jnm2** [comment]
My brain things the grey "Close and comment" button says "Cancel." 😒

**Comment by CharliePoole** [comment]
No, if an exception were thrown, we would be terminating the test. Warnings in general and failures within a multiple assert block can't throw an exception.

Bearing in mind that we only trim the stack in case of an assertion failure or warning, I'd say you want the first line in your sample stack only and that everything starting from the first "[Resuming Async Method]" on down should be dropped. Does that make sense?

**Comment by jnm2** [comment]
Yes, I like that.
