### ISSUE TITLE
Transient ParallelExecutionStrategyTests.SingleThreadedTestCase CI failure

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2457]
Failed during an AppVeyor PR test for net35 and I think I've seen this before.

https://ci.appveyor.com/project/CharliePoole/nunit/build/3.9.0-ci-04466-pr-2455#L1263

```
8) Cancelled : NUnit.Framework.Internal.Execution.ParallelExecutionStrategyTests.SingleThreadedTestCase(Default,Default)
Test cancelled by user
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args) in C:\projects\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 225
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunNonAsyncTestMethod(TestExecutionContext context) in C:\projects\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 109
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in C:\projects\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context) in C:\projects\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 59
```

**Comment by CharliePoole** [comment]
I wrote those tests pretty quickly, using a lot of components from the framework. It would probably be safer to use more mocks and fakes in the implementation.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
