### ISSUE TITLE
NUnitV2ResultWriter writes empty test result files

### ISSUE THREAD

**Issue by digitalpacman** [nunit/nunit#2474]
I had a legacy test framework written using unit2.  NUnit2 didn't support parallel runs so we wrote our own runner. This runner scans for all types in the assembly with a CategoryAttribute and executes the nunit runner selecting that test class only.  So if we have 10 tests, we start 10 threads and execute nunit console runner 10 times one for each test.

I upgraded nunit2 runner to nunit3 and upgraded my system to use nunit3.   Then we found out the framework code that was written in this legacy system doesn't support parallelism within the same appdomain.  So without massive work we can't use nunit3 parallelism but we still want to upgrade.

Often, and with non-determinism, this fails.  The test results xml file will be written as a blank file.  This is the stack trace.  This doesn't seem to happen for us when we output the nunit3 format.  We don't want nunit3 format because visualization tools aren't functional yet.  We use older nunit2 visualization tools.

```
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host

Server stack trace: 
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.Tcp.TcpFixedLengthReadingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read(__BinaryParser input)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadSerializationHeaderRecord()
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryResponseMessage(Stream inputStream, IMethodCallMessage reqMsg, Boolean bStrictBinding)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestAgent.Stop()
   at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.MasterTestRunner.Dispose()
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

**Comment by CharliePoole** [comment]
This issue is almost certainly in the wrong place, since it relates to the framework. However, I can't tell from reading it if it's an issue for the console runner or for the nunitv2 result writer. which are separate projects. For now, we'll keep it here while figuring out where it actually belongs.

As a start, would you please tell us the version of all the NUnit pieces you use? That should include the framework, runner, nunit v2 framework driver extension and nunit v2 result writer extension.

**Comment by rprouse** [comment]
We haven't heard back from @digitalpacman and this seems to be a duplicate of nunit/nunit-console#290, so I am closing in favor of that issue.

**Comment by digitalpacman** [comment]
@rprouse sorry I didn't get back.  We were in the process of upgrading so I didn't have fixed details. 

We only really notice this when using the system oddly.  Our old wrapper isn't thread safe so we cannot use nunit3 parallel mode.  So we issue an nunit3 run with nunit2 output for every test using our own runner.  We do a reflection scan etc then spawn parallel runs.  Since this is so weird I didn't think is was too pressing.  I added a rerun until file not empty check which solved it for us.  Using nunit3 with nunit3 output works and we are trying to upgrade.
