### ISSUE TITLE
Unit test failed to run getting below exception, I am using version nunit version 3.6.1

### ISSUE THREAD

**Issue by Rag1987** [nunit/nunit#2569]
2017.11.17 19:03:04.318   ERROR System.IO.FileNotFoundException: Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.
File name: 'nunit.framework'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Load()
   at NUnit.Engine.Runners.MasterTestRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Explore(TestFilter filter)
   at JetBrains.ReSharper.UnitTestRunner.nUnit30.BuiltInNUnitRunner.<>c__DisplayClass1.<RunTests>b__0()
   at JetBrains.ReSharper.UnitTestRunner.nUnit30.BuiltInNUnitRunner.WithExtensiveErrorHandling(IRemoteTaskServer server, Action action)

**Comment by jnm2** [comment]
We will need to know how to reproduce this. I know this isn't a problem in general with NUnit Framework 3.6.1 and ReSharper because I've used them together. What sort of project should we set up and what version of VS? What's the tiniest possible project that can be created that causes this issue?

**Comment by Rag1987** [comment]
I use VS2010 version. this project is to validate the mandatory data fields in the screen.

**Comment by jnm2** [comment]
Oh, that's interesting. What version of the .NET Framework does the project use? Are you using the NuGet extension for VS 2010? Can you make this problem happen in a brand new standalone test project that you can share?

**Comment by Rag1987** [comment]
I use framework version 4. I am running the test project through Resharper and I added the nunit.framework.dll in my project.

  [Test]
        public void ReteriveResponseData()
        {
            hold.Class = "Profile";
            hold.HoldingNumber = "123456";
            docList = docView.TestSearchDocs(hold, "4545484253989339", "en");            
            Assert.IsNotNull(docList);

        }

**Comment by jnm2** [comment]
[I edited your comment there to show syntax highlighting. If you like you can edit and check it out! 😃]

Thanks for the info. Still putting the pieces together. Where did you download `nunit.framework.dll` from? I ask because we publish six nunit.framework dlls and only one of them is for .NET Framework 4.0.
Most people use NuGet which automatically references the correct DLL in the project for them but you can also download the zip, so I'm curious which method you used to add NUnit to the project.

**Comment by Rag1987** [comment]
I downloaded the the zip (NUnit.Framework-3.6.1.zip) and referenced the 'nunit.framework.dll' from 4.0 folder

**Comment by jnm2** [comment]
Perfect, thanks. Sorry for all the questions!
 - What version of ReSharper are you using in VS 2010?
 - Does this happen for you with a brand new project or only on one specific project?

**Comment by Rag1987** [comment]
I resharper ultimate 2017.2.2, this issue happen to everyone who creates the new project with 3.6.1 nunit version.

**Comment by jnm2** [comment]
I don't have an answer for you yet but I'm setting up VS2010 in a virtual machine. Do you use Professional Edition? Is it RTM or is it Service Pack 1?

**Comment by Rag1987** [comment]
I use VS professional edition service pack 1

**Comment by jnm2** [comment]
Boy, this brings back memories! =)

![image](https://user-images.githubusercontent.com/8040367/32975007-05024668-cbd1-11e7-9ace-e7ca0318152e.png)

**Comment by jnm2** [comment]
I'm not able to find the problem yet:

![image](https://user-images.githubusercontent.com/8040367/32975900-5ecde0cc-cbda-11e7-9b47-3bc34419141f.png)

- This is Visual Studio 2010 Professional, version 10.0.40219.1 SP1Rel
- ReSharper 2017.2.2 build 109.0.20171006.122324
- bin\net-4.0\nunit.framework.dll from `https://github.com/nunit/nunit/releases/download/3.6.1/NUnit.Framework-3.6.1.zip`
- new class library targeting net40

.csproj:

<details>

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{1E4E3419-73C9-4B35-8DD0-0D9EE52ABF04}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>NUnitRepro</RootNamespace>
    <AssemblyName>NUnitRepro</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="nunit.framework">
      <HintPath>..\..\..\..\..\Desktop\nunit.framework.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Class1.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```

</details>

**Comment by jnm2** [comment]
You say you can reproduce this problem in a brand new class library targeting net40? Can you zip that and drop it in your reply on this thread so I can try it?

**Comment by jnm2** [comment]
If that doesn't work, the next step is for you to capture the assembly binding log using https://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
