### ISSUE TITLE
Getting WorkerId fails in debug

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#2696]
@botinko commented on [Fri Feb 02 2018](https://github.com/nunit/nunit-vs-adapter/issues/166)

Hi! 

1, Visual Studio 2017 Version 15.5.2
2. NUnit test adapter V 3.9 
3, Nunit 3.9 (installed via nuget) 

When I try to debug test from Test Explorer, getting TestContext.CurrentContext.WorkerId throws null reference exception. 
When I debug test in Rider or via Resharper in VS, then all is ok. 

---

@OsirisTerje commented on [Fri Feb 02 2018](https://github.com/nunit/nunit-vs-adapter/issues/166#issuecomment-362671063)

You placed this in the NUnit 2 adapter repo, I'll move it to the NUnit3 adapter repo.

Confirmed.  I get the same.  It seems however, to be an issue in NUnit itself.  
![image](https://user-images.githubusercontent.com/203432/35749447-d5ddf7fc-0851-11e8-90a9-70bbcbfca98e.png)

It fails in debug
It works with a non-debug run. 

@rprouse Can you have a look?
I'll move this to the NUnit repo.

**Comment by botinko** [comment]
Hi! Is there any progress on this bug? This is very annoying.

**Comment by ChrisMaddock** [comment]
What framework are you targeting?

This looks like it would throw when running on a target with no parallelization features available - I'm not sure how switching between RELEASE and DEBUG would affect that though. @CharliePoole - any ideas?

**Comment by ChrisMaddock** [comment]
@OsirisTerje - do we know what the adapter does differently depending on if you click 'debug' or 'run'?

**Comment by botinko** [comment]
Target framework is 4.6.1. Configuration Debug / Any CPU.

**Comment by jnm2** [comment]
Either way, this should use `_testExecutionContext.TestWorker?.Name` if we don't guarantee that there will always be a worker for every `TestContext` instance.

https://github.com/nunit/nunit/blob/facc4c8ee5c99653accb64acd3026e07f214457a/src/NUnitFramework/framework/TestContext.cs#L120-L126

**Comment by jnm2** [comment]
<details>
<summary>Stack trace in release shows `ParallelWorkItemDispatcher`</summary>

```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
   at NUnit.Framework.Internal.MethodWrapper.Invoke(Object fixture, Object[] args)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunNonAsyncTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(WorkItem work, ParallelExecutionStrategy strategy)
   at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.Dispatch(WorkItem work)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

</details>

<details>
<summary>Stack trace in debug does not</summary>

```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
   at NUnit.Framework.Internal.MethodWrapper.Invoke(Object fixture, Object[] args)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunNonAsyncTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch(WorkItem work)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch(WorkItem work)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch(WorkItem work)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunOnCurrentThread()
   at NUnit.Framework.Internal.Execution.WorkItem.Execute()
   at NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.RunnerThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
</details>

**Comment by CharliePoole** [comment]
@jnm2 How are you running to get these stack traces?

**Comment by jnm2** [comment]
Test Explorer window to debug or run with adapter VSIX 3.9 installed:

```cs
[Test]
public static void Test()
{
    var dump = new StackTrace(skipLines: 1).ToString();
    Debugger.Launch();
}
```

**Comment by CharliePoole** [comment]
@OsirisTerje said it's not an adapter bug. But has anyone verified this by use of either nunitlite or the console runner?

**Comment by CharliePoole** [comment]
The adapter sets the number of test workers to zero when debugging. I did this three years ago in response to nunit/nunit3-vs-adapter#36. We need to be better at researching stuff before we announce that it's a bug or where the bug is!

@botinko You should know that the purpose of `TestContext.WorkerId` is to help you __discover__ whether or not you are running under the parallel dispatcher and, if so, what kind of worker is executing your code. It's probably not useful for anything except NUnit testing. Note that the value may be `null` for any test code you have, since the person or program running the test can control which dispatcher is used. If you have a test that only makes sense when run under one dispatcher or the other, you can use an `Assume` statement to cause it to be inconclusive when run in the wrong context.

@OsirisTerje When we made this change, there were other options discussed. We could revisit, of course.

**Comment by jnm2** [comment]
I think the adapter should stay the way it is. The NRE is a real bug in the framework though that needs a test and a fix. I'll volunteer?

**Comment by CharliePoole** [comment]
Maybe I misunderstood. I thought the OP was trying to __use__ the workerid and that gave rise to the NRE. If merely accessing it causes an NRE, that's pretty easy. The NRE probably comes from the `TestExecutionContext` having a null worker.

**Comment by jnm2** [comment]
I've confirmed that this line causes an NRE to be thrown from the NUnit Framework stack frame:

`_ = TestContext.CurrentContext.WorkerId;`

If you look at the [code](https://github.com/nunit/nunit/issues/2696#issuecomment-365937703), you can see where. The interesting part will be writing the test for it.

**Comment by botinko** [comment]
@CharliePoole @jnm2  great thanks for response! 
WorkerId is very useful for us. We have many tests that run in parallel. There is also a pool of databases that are used in unit tests. Part of the DB name is the WorkerId. This allows us to effectively re-use the DB's between the Workers. In addition, WorkerId do not change between startups and are readable.

And when we try to debug our test in VS with NUnit adapter, we got NRE.

**Comment by jnm2** [comment]
Another option less tied to NUnit might be `Thread.CurrentThread.ManagedThreadId`.

**Comment by jnm2** [comment]
Another option less tied to NUnit might be `Thread.CurrentThread.ManagedThreadId` or `Task.CurrentId`, depending on what you care about tracking.

**Comment by jim-molecule** [comment]
1. Jetbrains Rider 2018.3
2. NUnit 3.11.0
3. Nunit3TestAdapter 3.12.0
4. [Parallelizable(ParallelScope.All)]

The same problem. TestContext.CurrentContext.WorkerId == null

**Comment by CharliePoole** [comment]
It seems silly that we haven't fixed this yet. While there are all kinds of implications that could be discussed, an NRE is an NRE after all!
