### ISSUE TITLE
The NUnit 3 driver encountered an error while executing reflected code.

### ISSUE THREAD

**Issue by MartinGonzalez** [nunit/nunit#2719]
I'm new running nunit with command line , and i need it to create automated tests.

I'm building with `msbuild .sln` and then try to run this 

`mono /path/to/NUnit/nunit3-console.exe Temp/bin/Debug/Assembly-CSharp-Editor.dll`

and i'm receiving this output

```
1) Error :
NUnit.Engine.NUnitEngineException : The NUnit 3 driver encountered an error while executing reflected code.
  ----> System.InvalidCastException : Specified cast is not valid.
--NUnitEngineException


Server stack trace:
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject (System.String typeName, System.Object[] args) [0x0002c] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load (System.String testAssemblyPath, System.Collections.Generic.IDictionary`2[TKey,TValue] settings) [0x0009e] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.LoadDriver (NUnit.Engine.Extensibility.IFrameworkDriver driver, System.String testFile, NUnit.Engine.TestPackage subPackage) [0x00008] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.LoadPackage () [0x000c4] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.TestDomainRunner.LoadPackage () [0x00017] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded () [0x00008] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.AbstractTestRunner.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Agents.RemoteTestAgent.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <a3ad5449913a4202999529a949a30f07>:0
  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices:InternalExecute (System.Reflection.MethodBase,object,object[],object[]&)
  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, System.Runtime.Remoting.Messaging.IMethodCallMessage reqMsg) [0x000b5] in <4fdc5ed61a074cafb49fa42deb20d521>:0

Exception rethrown at [0]:
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_remoting_wrapper (intptr,intptr)
  at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent:Run (NUnit.Engine.ITestEventListener,NUnit.Engine.TestFilter)
  at NUnit.Engine.Runners.ProcessRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00025] in <a3ad5449913a4202999529a949a30f07>:0
--InvalidCastException
  at NUnit.Framework.Api.FrameworkController+LoadTestsAction..ctor (NUnit.Framework.Api.FrameworkController controller, System.Object handler) [0x00008] in <116d15b838ac4e24a87624af132b3294>:0
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <4fdc5ed61a074cafb49fa42deb20d521>:0
```

I've downloaded the .zip and try to run a built dll

EDIT:

Also i've tried running like this

`nunint-console path-to-my-dll`

And i have two different experiences

1) if i'm testing some  basic test it works
2) if i'm testing something more complex i have this error

`System.MissingMethodException : Attempted to access a missing method.`

What i've read is that i have to run with mono because uses some framework "InternalCall" stuff or something that i'm not familiar with

**Comment by mikkelbu** [comment]
Hi @MartinGonzalez. If you add the flag `--trace=Debug` to your command line, then this will write various log files. These may contain more information.

**Comment by MartinGonzalez** [comment]
@mikkelbu Thanks for the response!

Yes i have this one. Also i edited something in the main post

InternalTrace.4668.log
```
InternalTrace: Initializing at level Debug
20:40:32.826 Info  [ 1] ExtensionService: Scanning nunit.engine assembly for extension points
20:40:32.837 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
20:40:32.840 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
20:40:32.841 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
20:40:32.841 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
20:40:32.841 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
20:40:32.841 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
20:40:32.841 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
20:40:32.848 Info  [ 1] ExtensionService: Processing file /Users/martingonzalez/Desktop/NUnit/nunit.engine.addins
20:40:32.869 Info  [ 1] ExtensionService: Scanning /Users/martingonzalez/Desktop/NUnit/addins/nunit.v2.driver.dll assembly for Extensions
20:40:32.893 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2FrameworkDriver
20:40:32.896 Info  [ 1] ExtensionService: Scanning /Users/martingonzalez/Desktop/NUnit/addins/nunit-v2-result-writer.dll assembly for Extensions
20:40:32.897 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnit2XmlResultWriter
20:40:32.898 Info  [ 1] ExtensionService:         ExtensionProperty Format = nunit2
20:40:32.898 Info  [ 1] ExtensionService: Scanning /Users/martingonzalez/Desktop/NUnit/addins/nunit-project-loader.dll assembly for Extensions
20:40:32.901 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type NUnitProjectLoader
20:40:32.901 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .nunit
20:40:32.901 Info  [ 1] ExtensionService: Scanning /Users/martingonzalez/Desktop/NUnit/addins/vs-project-loader.dll assembly for Extensions
20:40:32.901 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type VisualStudioProjectLoader
20:40:32.901 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .sln
20:40:32.901 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .csproj
20:40:32.901 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vbproj
20:40:32.901 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vjsproj
20:40:32.901 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .vcproj
20:40:32.901 Info  [ 1] ExtensionService:         ExtensionProperty FileExtension = .fsproj
20:40:32.901 Info  [ 1] ExtensionService: Scanning /Users/martingonzalez/Desktop/NUnit/addins/teamcity-event-listener.dll assembly for Extensions
20:40:32.903 Info  [ 1] ExtensionService:   Found ExtensionAttribute on Type TeamCityEventListener
20:40:33.026 Debug [ 1] RuntimeFrameworkService: Assembly /Users/martingonzalez/Documents/projects/games/voxsy-unity/Temp/bin/Debug/Assembly-CSharp-Editor.dll uses version 4.0.30319
20:40:33.027 Debug [ 1] RuntimeFrameworkService: Current framework is mono-4.0
20:40:33.027 Debug [ 1] RuntimeFrameworkService: Requested framework is any
20:40:33.028 Debug [ 1] RuntimeFrameworkService: Test will use mono-4.0 framework
20:40:33.033 Info  [ 1] ProcessRunner: Running 
20:40:33.035 Info  [ 1] TestAgency: Getting standard agent for use under mono-4.0
20:40:33.035 Debug [ 1] TestAgency: Using nunit-agent at /Users/martingonzalez/Desktop/NUnit/nunit-agent.exe
20:40:33.045 Debug [ 1] TestAgency: Launched Agent process 4669 - see nunit-agent_4669.log
20:40:33.045 Debug [ 1] TestAgency: Command line: "mono" --runtime=v4.0.30319 "/Users/martingonzalez/Desktop/NUnit/nunit-agent.exe" 7127aafc-3f29-480f-902e-dc53890c44de tcp://127.0.0.1:58621/TestAgency --pid=4668 --trace:Debug --work=/Users/martingonzalez/Desktop/NUnit
20:40:33.046 Debug [ 1] TestAgency: Waiting for agent {7127aafc-3f29-480f-902e-dc53890c44de} to register
20:40:33.453 Debug [ 1] TestAgency: Returning new agent {7127aafc-3f29-480f-902e-dc53890c44de}
20:40:33.723 Error [ 1] ProcessRunner: Failed to run remote tests The NUnit 3 driver encountered an error while executing reflected code.
20:40:33.732 Info  [ 1] ProcessRunner: Unloading 
20:40:33.743 Debug [ 1] ProcessRunner: Stopping remote agent
```

**Comment by mikkelbu** [comment]
Are there anything in the agent logs, i.e. in `nunit-agent_4669.log` mentioned above?

**Comment by MartinGonzalez** [comment]
@mikkelbu sorry! i've edited my previous comment adding the agent log

**Comment by CharliePoole** [comment]
Actually, since it reports an error running tests through reflection, that indicates the problem happens in the framework. You will find that in the log with the name of your test assembly in it. 😞

**Comment by mikkelbu** [comment]
@MartinGonzalez sorry about that I keep asking for other files, but what does the log for `Assembly-CSharp-Editor.dll` contain?

**Comment by MartinGonzalez** [comment]
@mikkelbu my bad again but this one is empty

InternalTrace.4669.Assembly-CSharp-Editor.dll.log
```
InternalTrace: Initializing at level Debug
```

**Comment by MartinGonzalez** [comment]
With `nunit-console` it works fine in a basic project, but i think this nunit is the one mono brings.
If i run this same command in the project where uses some framework calls (i think) i have this error
`System.MissingMethodException : Attempted to access a missing method.`

**Comment by CharliePoole** [comment]
That tells us your tests load and almost immediately crash!

**Comment by MartinGonzalez** [comment]
@CharliePoole i'm not so familiar with this kind of processes. I understand that the solution must be built and after that the tests are done over the dlls.
 i'm creating a gem in ruby doing the building of the solution and testing of the dlls and i crash on this :(

**Comment by MartinGonzalez** [comment]
I did a tests in Unity to determinate what could be failing and if i use Debug.Log from UnityEngine it throws the result
```
MyEditorTests.Should_Pass : System.MissingMethodException : Attempted to access a missing method.
at (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,string,UnityEngine.Object)
at UnityEngine.DebugLogHandler.LogFormat (UnityEngine.LogType logType, UnityEngine.Object context, System.String format, System.Object[] args) [0x0000b] in /Users/builduser/buildslave/unity/b
uild/Runtime/Export/Logger/DebugLogHandler.cs:9
at UnityEngine.Logger.Log (UnityEngine.LogType logType, System.Object message) [0x00029] in /Users/builduser/buildslave/unity/build/Runtime/Export/Logger/Logger.cs:41
at UnityEngine.Debug.Log (System.Object message) [0x00008] in /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cs:103
at MyEditorTests.Should_Pass () [0x00001] in /Users/martingonzalez/Desktop/NUnitConsoleTestsSampleApp/Assets/Editor/MyEditorTests.cs:11
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.Culture
Info culture) [0x00032] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
```

**Comment by MartinGonzalez** [comment]
Searching and testing a bit more this is more side of Unity.
If in the tests we use something that belong to the native core of unity (that must be initialized and running) it will break, but if its .net pure, it will succeed.
I'm closing this issue

**Comment by Divya0710** [comment]
NUnit.Engine.NUnitEngineException : The NUnit 3 driver encountered an error while executing reflected code.
  ----> System.InvalidCastException : Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
--NUnitEngineException
The NUnit 3 driver encountered an error while executing reflected code.

Server stack trace:
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
--
InvalidCastException
Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)

**Comment by mikkelbu** [comment]
The easiest way to get help is to provide as much information as possible. From the stacktrace I'll guess that you are trying to run dotnetcore 3.1 tests using the nunit console which does not support dotnet core yet (as your stacktrace is very similar to the one in e.g. nunit/nunit-console#792).

You can try out the beta runner that is able to also run dotnet core tests, see https://github.com/nunit/nunit-console/issues/475#issuecomment-667570922 for link to the beta.
