### ISSUE TITLE
Random failing of parallel test run: Unhandled Exception: System.InvalidOperationException: Stack empty.

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2772]
_From @YRudievGP on March 23, 2018 14:16_

Sorry if dublicate, I didn't find the issue.

Random failing of parallel test run. 
More then one hundred tests are in the test run and they are running parallel ([Parallelizable(ParallelScope.Fixtures)]). 
Seems that different threads trying to take next test when they are finished (it occurs in the end of the run).

```
Call stack:
The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: Stack empty.
[11:25:57][test]    at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
[11:25:57][test]    at System.Collections.Generic.Stack`1.Pop()
[11:25:57][test]    at NUnit.Framework.Internal.Execution.WorkItemQueue.Restore()
[11:25:57][test]    at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.RestoreQueues()
[11:25:57][test]    at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.OnEndOfShift(WorkShift endingShift)
[11:25:57][test]    at NUnit.Framework.Internal.Execution.WorkShift.<StartWorkers>b__26_1(TestWorker s, WorkItem ea)
[11:25:57][test]    at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
[11:25:57][test]    at System.Threading.Thread.ThreadMain_ThreadStart()
[11:25:57][test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

NUnit: 3.10.1
NUnit3testAdapter: 3.10.0
Target framework: netcoreapp2.0
CI: TeamCity 2017.2.1 (build 50732)
OS: Linux Ubuntu

_Copied from original issue: nunit/nunit3-vs-adapter#491_

**Comment by rprouse** [comment]
Thanks for the report. Based on the callstack, I believe this belongs in the NUnit Framework repository, so I am going to move it there.

**Comment by CharliePoole** [comment]
@rprouse Is parallel execution new for .NET Standard 2.0?

**Comment by jnm2** [comment]
It was present in the .NET Standard 2.0 build when I first added it (https://github.com/nunit/nunit/pull/2607). First shipped in 3.10.

**Comment by Ant-hem** [comment]
Hello, any update on this issue? 
I am having this error from time to time as well.

NUnit: 3.11.0
NUnit3testAdapter: 3.11.2
Target framework test project: netcoreapp2.1
Target framework library tested: netstandard2.0
CI: Azure Pipeline
OS: macOS

Thanks!

**Comment by Ant-hem** [comment]
hey @mikkelbu, I have the following stack strace (happened yesterday on my CI). I'll run with `InternalTraceLevel = Debug` and send you the error log when this error happens. (it happens very randomly CI and Local)

Some additional  information that could help you : I have around 30 Parallelizable TestFixture, global TearDown/Setup and some OneTimeSetup for specific TestFixture. If you want to have a look at the test project it's [here on GH](https://github.com/algolia/algoliasearch-client-csharp/tree/client-csharp-v2/src/Algolia.Search.Test).

```
2018-12-19T13:45:32.5263490Z The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: Stack empty.
2018-12-19T13:45:32.5264090Z    at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
2018-12-19T13:45:32.5264330Z    at System.Collections.Generic.Stack`1.Pop()
2018-12-19T13:45:32.5264550Z    at NUnit.Framework.Internal.Execution.WorkItemQueue.Restore()
2018-12-19T13:45:32.5264800Z    at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.RestoreQueues()
2018-12-19T13:45:32.5265050Z    at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.OnEndOfShift(WorkShift endingShift)
2018-12-19T13:45:32.5265230Z    at NUnit.Framework.Internal.Execution.WorkShift.<StartWorkers>b__26_1(TestWorker s, WorkItem ea)
2018-12-19T13:45:32.5265470Z    at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
2018-12-19T13:45:32.5265680Z    at System.Threading.Thread.ThreadMain_ThreadStart()
2018-12-19T13:45:32.5265950Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-12-19T13:45:32.5267050Z --- End of stack trace from previous location where exception was thrown ---
2018-12-19T13:45:32.5267300Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by ztittle** [comment]
Hey all. We have been seeing this issue as well. Our test suite consists of over 475 tests that are setup to run in parallel. As we expand test cases, we have been running into this concurrency issue more often since our build machines have 8 cores. It appears to be a timing issue when restoring the work item queue. I've created a PR https://github.com/nunit/nunit/pull/3154 that addresses the issue.

**Comment by jnm2** [comment]
If you'd like to try this out before 3.12.0 is released, you can merge this with your nuget.config and look for version `3.12.0-dev-06138` or greater:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NUnit MyGet" value="https://www.myget.org/F/nunit/api/v3/index.json" />
  </packageSources>
</configuration>
```

Please let us know what you see if you try it. I'll close via https://github.com/nunit/nunit/pull/3154 for now. (Thanks, @ztittle!)

**Comment by abelbraaksma** [comment]
@jnm2 Using NUnit 3.13.1 this still happens, at least just now for me. If I run a test in isolation, one by one, there's no issue. When I run tests in parallel in the test runner, the aforementioned error pops up:

```
  Message: 
    System.InvalidOperationException : Stack empty.
  Stack Trace: 
    Stack`1.ThrowForEmptyStack()
    Stack`1.Pop()
    OperatorStack.Pop()
    ConstraintBuilder.Resolve()
```

I'm not yet sure why this is happening now. I did a few refactorings in my code and it started popping up. I'll revert and investigate. But be as it may, the problem is still there...
