### ISSUE TITLE
uint attribute parameter conversion fails with leading zeros

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2783]
In the following example:

```
        [TestCase(0x00FFFFFF, TestName = "{m}(Clear)")]
        [TestCase(0xFFFFFFFF, TestName = "{m}(White)")]
        public void UIntTest(uint stopColor)
        {
        }
```

The second test case passes, where as the first failes with the below Exception:

```
System.ArgumentException : Object of type 'System.Int32' cannot be converted to type 'System.UInt32'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
```

This is NUnit 3.10.0

**Comment by CharliePoole** [comment]
You would probably have to use the debugger to confirm, but here's what I think happens...

First Case:
 * Compiler interprets argument as an Int32
 * TestAttribute performs no special conversions for unsigned targets because user is assumed to use either a variable of the correct type or a constant with `U` suffix.
 * An error ensues when we try to call the method.

Second Case:
 * Compiler interprets the argument as an unsigned int (guessing here)
 * TestAttribute does no conversion since arg is the correct type
 * It works correctly

So essentially, NUnit is doing nothing to change the arguments here but is relying on .NET to figure out any automatic conversions when calling the method. That's what happens in the majority of cases, in fact.

Workaround would be to use some syntax that let's compiler know it's dealing with an unsigned. There are several possible options including casting and use of a defined constant.

Alternative is to add a special conversion from int to uint in test attribute or further along in the pipeline. Further along makes sense, since this could arise just as well with TestCaseSource. However, this seems like a bit of a corner case to me, so I probably would leave it to the user to make the type clear.

**Comment by ChrisMaddock** [comment]
Ah, should I be adding the u suffix to force it? I’m to used to Nunit converting all the things for me. 😄

Maybe once all this parameter logic has been harmonised, it might be more sensible to make this addition. I’ll call it an enhancement instead.

**Comment by CharliePoole** [comment]
A general principle behind the design of NUnit - way back before NUnit 3 even - was this: "If you tell us to do something, or use something, we'll try. If it fails, it's on you." OTOH, if you let us decide (as with defaults of various kinds) then it's on us to make it work.

WRT TestCaseAttribute args, we compromised but we only step in if you have a target Type that cannot be expressed as an attribute argument. So, for example, if we didn't convert double to decimal, you could never have a test method that took a decimal argument. In the case of uint, you can have them but you have to express them correctly.

Not saying it should continue that way, but that was the idea in the beginning, based on the user audience we had. There's no doubt that the audience has changed and that expectations for doing things automatically are higher than at the beginning.

**Comment by CharliePoole** [comment]
A thought: maybe we should do all the conversions that we already do on numerics (e.g. for equality). That would probably feel more consistent. If so, we should do them where they will work for all data attributes rather than just for TestCaseAttribute.

**Comment by jnm2** [comment]
I agree that we should be consistent with the other places we convert types. If we don't already convert int to uint anywhere, do we need to add that though? Are there languages whose analog of the `u` suffix are not an easy thing to do?

**Comment by CharliePoole** [comment]
I see two sides here. (It's a curse... 😄 )

OTOH, as you say, why do it if it's easy enough for the user to do.

OTOH, @ChrisMaddock , who among other things is a really smart user, expected it to work.

Right now, we convert int to uint when comparing numerics for equality. Is that inconsistent with not doing it here? I guess it depends on how you look at it.

**Comment by jnm2** [comment]
Since we are already converting int to uint when comparing for equality, that answers my question since I think we should make the all type conversions use the same logic. And we wouldn't want to remove that feature when unifying.

**Comment by CharliePoole** [comment]
I agree with supporting the feature although I'm not keen on the "unification" idea itself.

**Comment by jnm2** [comment]
Hmm, okay. Well, the closer we make them, the happier I will be, so going only that far is still a positive from my pov. 😀

**Comment by CharliePoole** [comment]
It would help me if you pointed out the specific problem you are trying to fix. "Unifying" the various pieces of code could be good, could be bad, depending. I remember a guy who removed "duplication" by replacing the value 10 with a manifest constant in a bunch of places. Except they were actually three different discounts, offered to different people for different reasons! While I know you wouldn't do anything that bad, I'm still in favor of starting from the logical side and working toward the code.

In this case, I think the logical side is (1) deciding when to convert, (2) deciding what Types to convert, (3) selecting the target Type and (4) performing the conversion. Item (1) is a design issue, (2) is somewhat situational, (3) is sometimes trivial but other times not and (4) is probably the most straightforward to extract.

**Comment by jnm2** [comment]
My perspective was that users should not have to try to remember two sets of rules for the conversions we run which are fairly arbitrary by necessity. For example, why should we convert ExpectedResult differently than we convert other arguments to the attribute?

But you raise a good point. If the purposes of the conversions are fundamentally different in each scenario, it could be a good thing to make people stop and think about which set of rules will apply.

My best guesses from past excursions into the code:

The equality scenario `Assert.That(1, Is.EqualTo(someValue))` does conversion because we wanted to interpret the syntax `1` as if it was target-typed by the compiler. That is, as though the syntax `1` was specified in a statically-typed `byte` position (when the other value happens to be a `byte` at runtime; `double` if the other value happens to be a `double`, etc).

The purpose of conversion with test parameters and ExpectedResult is not only the above but additionally to bridge the gap with the limitations on what can be specified as an attribute value. E.g. "2018-03-27" as the attribute value to end up in a DateTime parameter or ExpectedResult.

If this is the way things are, it might make sense to share the common layer of conversions between them.

**Comment by jnm2** [comment]
My perspective was that users should not have to try to remember two sets of rules for the conversions we run which are fairly arbitrary by necessity. For example, why should we convert ExpectedResult differently than we convert other arguments to the attribute?

But you raise a good point. If the purposes of the conversions are fundamentally different in each scenario, it could be a good thing to make people stop and think about which set of rules will apply.

My best guesses from past excursions into the code:

The equality scenario `Assert.That(1, Is.EqualTo(someValue))` does conversion because we wanted to interpret the syntax `1` as if it was target-typed by the compiler. That is, as though the syntax `1` was specified in a statically-typed `byte` position (when the other value happens to be a `byte` at runtime; `double` if the other value happens to be a `double`, etc).

The purpose of conversion with test parameters and ExpectedResult is not only the above but additionally to bridge the gap with the limitations on what can be specified as an attribute value. E.g. "2018-03-27" as the attribute value to end up in a DateTime parameter or ExpectedResult.

If this is the way things are, it might make sense to share the common layer of conversions between them.

**Comment by CharliePoole** [comment]
Your interpretation of equality conversion is correct. We wanted `Assert.AreEqual` to work like the `==` operator for numeric values.

I agree that parameter conversion and expected value conversion should work the same. OTOH, I don't think users look at equality as being quite the same thing as either of them.

I think the whole issue of feature parity is more important than that of creating common code. And if you create feature parity, you thereby enable extraction of common code. Or, in other words, you create duplication of code so you can subsequently remove it.

**Comment by stevenaw** [comment]
I came across this issue while searching for "numerics". It's been a while since there was any activity. I'm a little unclear from the discussion, is there a change we need to do here?

**Comment by stevenaw** [comment]
Sounds like this behaviour is also present in the `RangeAttribute`
