### ISSUE TITLE
The active test run was aborted. Reason: <empty>

### ISSUE THREAD

**Issue by Duracell1989** [nunit/nunit#2817]
We have a ASP.NET Core Web Application in which the solution also contains a Test project.
I've run into the problem that when creating a Release build and then trying to run the test against the release build; the Microsoft.TestPlatform.Build.Tasks.VSTestTask fails after running some tests.

We have the following settings:
```
<TargetFramework>netcoreapp2.0</TargetFramework>
<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
```

The command which I run:
`dotnet test --configuration Release`

The output in the Console:
```
NUnit3TestExecutor converted 1726 of 1726 NUnit test cases
The active test run was aborted. Reason:

Total tests: Unknown. Passed: 323. Failed: 0. Skipped: 0.
Test Run Aborted.
Test execution time: 33.8924 Seconds
```
with d[etailed] output:
```
       Done executing task "Microsoft.TestPlatform.Build.Tasks.VSTestTask" -- FAILED.
   1:7>Done building target "VSTest" in project "<snip>.Test.csproj" -- FAILED.
   1:7>Done Building Project "C:\src\<snip>.Test.csproj" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)
```
There isn't any reason specified and when I try to run it with `dotnet test` it succeeds.

**Comment by mikkelbu** [comment]
Hi @Duracell1989
Does any of the advice from https://github.com/Microsoft/vstest/issues/627 provide more info? (e.g. '--blame' or '-d:log.txt ')

**Comment by Duracell1989** [comment]
the --blame don't work:
```
dotnet test --blame --configuration Release
MSBUILD : error MSB1001: Unknown switch.
Switch: --blame
```

I have already added the -d:log (detailed) info; but I can't find anything I can work with within the detailed output.

**Comment by mikkelbu** [comment]
@Duracell1989 Sorry I should have tested that the info in https://github.com/Microsoft/vstest/issues/627 was legit, but I was on my phone. According to https://github.com/Microsoft/vstest/issues/1427 you can use `dotnet vstest testProject.dll /blame` instead to create the sequence file.

What if you "increase" the verbosity? (e.g. `-v diag`) does that give us any information?

**Comment by Duracell1989** [comment]
With the blame; I found the test; but I can't find anything wrong. I've multiple other similar classes which are structured the same way.
If I add the /diag: option; I get the following message:
```
TpTrace Information: 0 : 24616, 12, 2018/04/23, 16:13:19.392, 21036624853, vstest.console.dll, TestRunRequest:SendTestRunStatsChange: Completed.
TpTrace Error: 0 : 24616, 12, 2018/04/23, 16:13:26.228, 21055368224, vstest.console.dll, Socket: Message loop: failed to receive message due to socket error System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
TpTrace Verbose: 0 : 24616, 12, 2018/04/23, 16:13:26.228, 21055370441, vstest.console.dll, TestRequestSender: OnTestRunAbort: Set operation complete.
TpTrace Verbose: 0 : 24616, 12, 2018/04/23, 16:13:26.229, 21055371269, vstest.console.dll, TestRequestSender.SetOperationComplete: Setting operation complete.
TpTrace Verbose: 0 : 24616, 12, 2018/04/23, 16:13:26.231, 21055378431, vstest.console.dll, TestRequestSender: GetAbortErrorMessage: Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
TpTrace Verbose: 0 : 24616, 12, 2018/04/23, 16:13:26.231, 21055378988, vstest.console.dll, TestRequestSender: GetAbortErrorMessage: Client has disconnected. Wait for standard error.
TpTrace Error: 0 : 24616, 6, 2018/04/23, 16:13:26.234, 21055385818, vstest.console.dll, Test host exited with error: ''
TpTrace Information: 0 : 24616, 6, 2018/04/23, 16:13:26.234, 21055386397, vstest.console.dll, TestRequestSender.OnClientProcessExit: Test host process exited. Standard error: 
TpTrace Information: 0 : 24616, 12, 2018/04/23, 16:13:26.234, 21055387017, vstest.console.dll, TestRequestSender: GetAbortErrorMessage: Received test host error message.
TpTrace Information: 0 : 24616, 12, 2018/04/23, 16:13:26.235, 21055387452, vstest.console.dll, TestRequestSender: GetAbortErrorMessage: Timed out waiting for test host error message.
TpTrace Error: 0 : 24616, 12, 2018/04/23, 16:13:26.235, 21055387817, vstest.console.dll, TestRequestSender: Aborting test run because 
TpTrace Verbose: 0 : 24616, 12, 2018/04/23, 16:13:26.235, 21055388230, vstest.console.dll, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 24616, 12, 2018/04/23, 16:13:26.235, 21055388678, vstest.console.dll, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Warning: 0 : 24616, 12, 2018/04/23, 16:13:27.262, 21058203948, vstest.console.dll, ProxyOperationManager: Timed out waiting for test host to exit. Will terminate process.
TpTrace Verbose: 0 : 24616, 12, 2018/04/23, 16:13:27.664, 21059306752, vstest.console.dll, ProxyDataCollectionManager.InvokeDataCollectionServiceAction: Starting.
TpTrace Verbose: 0 : 24616, 12, 2018/04/23, 16:13:27.664, 21059307436, vstest.console.dll, DataCollectionRequestSender.SendAfterTestRunStartAndGetResult : Send AfterTestRunEnd message with isCancelled: False
```

**Comment by Duracell1989** [comment]
The problem was a NullRefException within **optimized** code of Automapper (in which a LambdaExpression calls another Expression<Func<...>> in which the expression tree get's compiled and called).

Rewriting the (Lambda)Expression with NULL checks fixes my problem.
