### ISSUE TITLE
SetUp failed for test fixture - Array was not a one-dimensional array.  Issue seems related to byte[,] method parameters

### ISSUE THREAD

**Issue by Kritner** [nunit/nunit#2823]
I'm in the process of updating from `3.8.1` to `3.10.1` and I'm having an issue where testfixtures that pass in 3.8.1, fail to "SetUp" in 3.10.1.

R# test runner refuses to even display the fixture sometimes, and when it does, test results are always "inconclusive, test not run".

I only discovered this issue for this particular fixture because i received the stacktrace (below) when running `dotnet test` from the command line.

Here's the stacktrace:

```
SetUp failed for test fixture MyFixture
An exception was thrown while loading the test.
System.ArgumentException: Array was not a one-dimensional array.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Array.GetValue(Int32 index)
   at NUnit.Framework.Internal.TestNameGenerator.NameFragment.GetDisplayString(Object arg, Int32 stringMax) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\TestNameGenerator.cs:line 241
   at NUnit.Framework.Internal.TestNameGenerator.ArgListFragment.GetText(MethodInfo method, Object[] arglist) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\TestNameGenerator.cs:line 558
   at NUnit.Framework.Internal.TestNameGenerator.GetDisplayName(TestMethod testMethod, Object[] args) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\TestNameGenerator.cs:line 93
   at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(IMethodInfo method, Test parentSuite, TestCaseParameters parms) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestCaseBuilder.cs:line 89
   at NUnit.Framework.TestCaseSourceAttribute.<BuildFrom>d__22.MoveNext() in C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 142
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultTestCaseBuilder.cs:line 144
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 183
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 158
   at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext() in C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\TestFixtureAttribute.cs:line 227
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultSuiteBuilder.cs:line 80
```

I'm not sure if this modified example will actually have the issue or not, but my fixture looks similar to this:

Edit (simplifying example)
```
public class FastUnitTest : BaseCategoryAttribute { }

[TestFixture, FastUnitTest]
public class MyFixture
{

    // note my test has no `[SetUp]`, but seems to be referenced in the stacktrace above

        private static object[] testDataByteArray = new object[]
        {
            new object[]
            {
                "test",
                "another deal",
                new byte[] {1, 2, 3, 4}
            }
        };

        // this test passes with both 3.8.1 and 3.10.1
        [Test]
        [TestCaseSource(nameof(testDataByteArray))]
        public void TestThing(string thing, string anotherString, byte[] multiByte)
        {
            Assert.Pass();
        }

        private static object[] testDataMultiDimensionalByteArray = new object[]
        {
            new object[]
            {
                "test",
                "another deal",
                new byte[,] { { 1, 2 }, { 2, 3 } }
            }
        };

        // this test passes only on 3.8.1, it fails (to even set up the fixture) with the stacktrace above of 3.10.1
        [Test]
        [TestCaseSource(nameof(testDataMultiDimensionalByteArray))]
        public void TestThingMultiDimension(string thing, string anotherString, byte[,] multiByte)
        {
            Assert.Pass();
        }
}
```

Any thoughts?

**Comment by mikkelbu** [comment]
I think that the problem is related to #1382. Note in particular the comment in https://github.com/nunit/nunit/issues/1382#issuecomment-349611032 "Multidimensional arrays are not covered by this issue.".

For solving your problem you can probably provide the name of the testcase explicit, but perhaps we should also try to solve the general problem (or at least improve the solution to #1382).

**Comment by CharliePoole** [comment]
IIRC my comment was based on the belief that the rank of the array was checked before trying to generate a name. That would be the minimum fix.

**Comment by mikkelbu** [comment]
@Kritner To solve your problem you can change 
```
        private static object[] testDataMultiDimensionalByteArray = new object[]
        {
            new object[]
            {
                "test",
                "another deal",
                new byte[,] { { 1, 2 }, { 2, 3 } }
            }
        };
```
into
```
        private static IEnumerable<TestCaseData> testDataMultiDimensionalByteArray = new List<TestCaseData>
        {
            new TestCaseData
            (
                "test",
                "another deal",
                new byte[,] { { 1, 2 }, { 2, 3 } }
            )
            {
                TestName = "Some name for the testcase"
            }
        };
```

I'll see if I can supply the minimum fix that @CharliePoole describes.
