### ISSUE TITLE
Test runner hangs after Assert.Fail in AfterTest

### ISSUE THREAD

**Issue by MillerJames** [nunit/nunit#2938]
I'm running an NUnit 3.9 test suite with nunit3-console, with a TestAction which asserts on some state after the fixture finishes. When the assert fails, it throws an exception and the runner hangs indefinitely. Are AfterTest implementations not allowed to assert or throw?

```C#
using NUnit.Framework;
using NUnit.Framework.Interfaces;
namespace Tests
{
    [TestFixture]
    [MyTestAction]
    public class MyTest
    {
        [Test]
        public void Pass() { }
    }

    public class MyTestActionAttribute : TestActionAttribute
    {
        public override void BeforeTest(ITest test)
        {
            base.BeforeTest(test);
        }

        public override void AfterTest(ITest test)
        {
            Assert.Fail("A test left resources open");
            base.AfterTest(test);
        }
    }
}
```

**Comment by ChrisMaddock** [comment]
I don't believe assertions of any kind (such as Assert.Fail()) are allowed in either `TearDown` or `AfterTest` - the intention is that all assertions are made in your test, and the latter two methods are for cleaning up. You could instead throw an exception in your AfterTest, which I believe would cause the test to 'error' rather than 'fail' - but would still alert you to the fact that something is wrong.

Of course - it shouldn't hang. That sounds like a bug! A pull request to fix that would be very welcome - although it's not an area of the code I'm familiar with, and I imagine it could be quite involved...!

**Comment by mikkelbu** [comment]
Regarding the hang. Perhaps nunit/nunit#2920 will solve this?

Att: @MillerJames. Can you try if the "hang" is still there if you compile against the current code from master instead version 3.9 - e.g. the code from https://ci.appveyor.com/project/CharliePoole/nunit/build/3.11.0-dev-05759/artifacts.

**Comment by MillerJames** [comment]
The hang still occurs on master, but I think I have a simple fix. OneTimeTearDownCommand has a try/catch block where it calls the user-defined teardown method, and will call RecordTearDownException with any caught exception. It seems like AfterTestActionCommand should do something similar, but does not.

I'll open a pull request later with the change, once I write few tests.

**Comment by CharliePoole** [comment]
@MillerJames I think I see the problem. `AfterTestActionCommand` had an assumption built into it that it would always be wrapped by a `OneTimeTearDownCommand`. This was once the case but has changed in the code. You can see a remnant of that in the following comment:

```C#
        // If there are new assertion results here, they are warnings issued
        // in teardown. Redo test completion so they are listed properly.
```

The assumption is that an assertion failure or other exception in `AfterTest` will not return. The wrapping `OneTimeTearDownCommand` would then handle the exception correctly. You can see this if you add an empty `[OneTimeTearDown]` method to the class.

Originally, `OneTImeTearDownCommand` handled 0 to n one time teardown methods. A subsequent revision made it deal with a single method only, with 0 to n commands generated. Hence, if there are no one time setup methods, the exception goes unhandled.

A similar problem existed for AfterTest actions on methods and was fixed in `WorkItem.PerformWork()`. In the case of classes, `CompositeWorkItem.PerformWork()` is overridden to do nothing. I think that the internal organization of WorkItems needs to be refactored so that errors in TearDown and OneTimeTearDown are handled by common code.

**Comment by alex-davidson** [comment]
We ran into this issue with an assembly-level AfterTest which had long assumed that the BeforeTest had fully initialised everything, which it would not have done if it failed. Since the failing AfterTest would cause the runner to hang we never received notification of a failure, and it took some time to identify the issue.

I've written a test case to catch this issue and a fix which appears to 'work':

https://github.com/BluewireTechnologies/nunit/pull/1/commits

Suggestions? I expect the test will need cleaning up, but I wasn't sure how to incorporate it into the existing fixture since it involves an assembly-level action which always fails.

**Comment by CharliePoole** [comment]
Note that all the previous discussion here has been about AfterTest actions at the class level. This is the first time that assembly-level usage has come up. I'm in favor of capturing any exceptions, as @alex-davidson has done here but I would hope to see that coupled with a change that keeps people from running asserts in places where they are not actually "allowed". I put that in quotes because we can't do anything but throw an exception at runtime, but maybe it should not be an AssertionException, which is only thrown on failure. That is, maybe any assert should check if it's being used at a valid point in the code (e.g. not in TearDown or AfterTest) and throw an exception before it performs any check at all.

(This, btw, is what I was thinking of in my earlier comment about reorganizing the command structure.)

**Comment by guerital** [comment]
Is this bug planned to be fixed? Thanks

**Comment by alexandersorokin** [comment]
Is it OK to implement a simpler solution?

For example, I can add `try`, `catch` and `RecordTearDownException` to `TestActionItem ` class, `AfterTestActionCommand` class or `PerformOneTimeTearDown` method in `CompositeWorkItem` class in the same way as it is already implemented in `SetUpTearDownItem` class, `OneTimeTearDownCommand` class and `PerformWork` method in `SimpleWorkItem` class.

I am not sure is a good idea to generalize way of handling exceptions in `PerformWork` method in `SimpleWorkItem` class for the `TearDown` methods. It is because they have some differences. One difference is calling `RecordTearDownException` instead of `RecordException`.

**Comment by z002Holpp** [comment]
I also just stumbled over this behavior in our production environment.

Could reproduce the behavior as per the following table:
| Framework | NUnit  | TestAdapter | Exception with| Execution in | Result   |
| --------- | ------ | ------- | ------------ | ------------ | -------- |
| 4.8       | 3.12.0 | 3.16.1  | BeforeTest   | dotnet test  | ok       |
| 4.8       | 3.12.0 | 3.16.1  | AfterTest    | dotnet test  | hangs    |
| 4.8       | 4.3.2  | 5.0.0   | BeforeTest   | dotnet test  | ok       |
| 4.8       | 4.3.2  | 5.0.0   | AfterTest    | dotnet test  | hangs    |
| 8.0       | 4.3.2  | 5.0.0   | BeforeTest   | dotnet test  | ok       |
| 8.0       | 4.3.2  | 5.0.0   | AfterTest    | dotnet test  | crashes* |

Some small remarks:
* Throwing Exception or failing assertion leads to the same results.
* Adding the ActionAttribute on Fixture or Assembly Level seems not to make any difference (except that the stacktrace in case of the crash looks a bit longer).

In case of the crash (last line in above table), the outcome was as follows:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.Exception: Intended Exception in AfterTest
   at TestProject3.MyActionAttribute.AfterTest(ITest test) in C:\TestProject3\TestProject3\UnitTest1.cs:line 19
   at NUnit.Framework.Internal.Commands.TestActionItem.AfterTest(ITest test)
   at NUnit.Framework.Internal.Commands.AfterTestActionCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.AfterTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeTearDown()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.OneTimeTearDownWorkItem.Execute()
   at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()


Test Run Aborted.
```

**Comment by manfred-brands** [comment]
In the `BeforeAndAfterTestCommand` the `AfterTest` is executed inside an `RunTestMethodInThreadAbortSafeZone` which catches and records any exception, but in the `AfterTestCommand` it is not.

Adding that to the latter seems logical, at least consistent.

**Comment by z002Holpp** [comment]
Wow, I didn't  expect this to get fixed so fast! Absolutely fantastic, this helps us a lot!
Thank you very much @manfred-brands !

I already tried the new code and can confirm that the issue is solved. :-)

I have one small question though. My observation is now the following:
* Throwing an exception in the BeforeTest() leads to a failed test and the exception being displayed in the test output.
* Throwing an exception in the AfterTest() leads to a passed test with no indication about the exception to the user.

Is this intended?

Thanks again very much!

**Comment by manfred-brands** [comment]
> I have one small question though. My observation is now the following:
> 
> * Throwing an exception in the BeforeTest() leads to a failed test and the exception being displayed in the test output.
> * Throwing an exception in the AfterTest() leads to a passed test with no indication about the exception to the user.

There is a difference if the failing attribute is put on a fixture or on a test and there is a difference between test result and fixture result.

| Attribute Location | Exception in | Fixture Result | Test Result | Comment |
| - | - | - | - | - |
| Fixture | Before | Failed:SetUp | Failed:Parent | The test is not run as the Fixture BeforeTest fails |
| Fixture | After | Failed:Test | Passed:Test | The test runs successfully and passes, but the fixture fails although the location should be TearDown |
| Test | Before | Failed:Child | Failed:Test | The test is considered failed as the beforeTest is part of the test |
| Test | After | Failed:Child | Failed:Test | The test is considered failed as the AfterTest is part of the test |
