### ISSUE TITLE
FormatValueTuple throws NullReferenceException

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [nunit/nunit#2991]
NUnit seems to have problem with ValueTuple.
For example, this simple assertion will throws NullReferenceException:
`Assert.That(new [] {("Age", 16)}, Is.Empty);`

**Comment by mikkelbu** [comment]
Hi @Doan-Van-Tuan 
Which version of NUnit are you using, because it sounds like an issue that was resolved in 3.10 (see e.g. #2518 and #2660)

**Comment by Doan-Van-Tuan** [comment]
I'm using 3.8.1.0.
Stack trace:
`System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Framework.Constraints.MsgUtils.FormatValueTuple(Object value, Boolean printParentheses)
   at NUnit.Framework.Constraints.MsgUtils.<>c__DisplayClass14_11.<.cctor>b__24(Object val)
   at NUnit.Framework.Internal.TextMessageWriter.WriteValue(Object val)
   at NUnit.Framework.Internal.TextMessageWriter.WriteActualLine(ConstraintResult result)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
`

**Comment by Doan-Van-Tuan** [comment]
I'll check with 3.10.

**Comment by Doan-Van-Tuan** [comment]
Fixed in 3.10. I should have checked my version first.

**Comment by mikkelbu** [comment]
No worries 😄
