### ISSUE TITLE
Cannot get test properties when using TestCaseSource

### ISSUE THREAD

**Issue by sircody01** [nunit/nunit#3065]
```
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

namespace NUnit_Sample
{
    public class Class1
    {
        public const string PropertyA = "PropA";

        [Test]
        [Property(PropertyA, "ValueA")]
        [Property(PropertyA, "ValueB")]
        public void Test1()
        {
            var propertyList = TestContext.CurrentContext.Test.Properties[PropertyA];
            Assert.AreEqual(2, propertyList.Count());
            Assert.AreEqual("ValueA", TestContext.CurrentContext.Test.Properties[PropertyA].ToList()[0] as string);
            Assert.AreEqual("ValueB", TestContext.CurrentContext.Test.Properties[PropertyA].ToList()[1] as string);
        }

        [Test]
        [Property(PropertyA, "ValueA")]
        [Property(PropertyA, "ValueB")]
        [TestCaseSource(nameof(MyData))]
        public void Test2(string parm1)
        {
            var propertyList = TestContext.CurrentContext.Test.Properties[PropertyA];
            Assert.AreEqual(2, propertyList.Count());
            Assert.AreEqual("ValueA", TestContext.CurrentContext.Test.Properties[PropertyA].ToList()[0] as string);
            Assert.AreEqual("ValueB", TestContext.CurrentContext.Test.Properties[PropertyA].ToList()[1] as string);
        }

        public static List<TestCaseData> MyData()
        {
            var tcData = new List<TestCaseData>();
            tcData.Add(new TestCaseData("Fox"));
            tcData.Add(new TestCaseData("Rabbit"));
            tcData.Add(new TestCaseData("Hound"));
            return tcData;
        }
    }
}
```

Maybe I'm missing something, but I've found when a test method relies on a TestCaseSource, the Property attributes are dropped or inaccessible. In the above code sample Test1 passes as expected, but Test2 fails all three iterations. The first assert fails

```
1) Failed : NUnit_Sample.Class1.Test2("Fox")
  Expected: 2
  But was:  0
   at NUnit_Sample.Class1.Test2(String parm1) in C:\Users\c_gibson\source\repos\NUnit Sample\NUnit Sample\Class1.cs:line 30

2) Failed : NUnit_Sample.Class1.Test2("Rabbit")
  Expected: 2
  But was:  0
   at NUnit_Sample.Class1.Test2(String parm1) in C:\Users\c_gibson\source\repos\NUnit Sample\NUnit Sample\Class1.cs:line 30

3) Failed : NUnit_Sample.Class1.Test2("Hound")
  Expected: 2
  But was:  0
   at NUnit_Sample.Class1.Test2(String parm1) in C:\Users\c_gibson\source\repos\NUnit Sample\NUnit Sample\Class1.cs:line 30

```

**Comment by rprouse** [comment]
This is because the test methods form a parent test fixture for the child parameterized tests, so the properties are on the parent, not on the tests themselves. You need to add the properties to your `TestCaseData` using the `SetProperty` method.

Remove the property attributes from your `Test2` and rewrite `MyData` to this,

```C#
public static IEnumerable<TestCaseData> MyData()
{
    yield return new TestCaseData("Fox").SetProperty(PropertyA, "ValueA").SetProperty(PropertyA, "ValueB");
    yield return new TestCaseData("Rabbit").SetProperty(PropertyA, "ValueA").SetProperty(PropertyA, "ValueB");
    yield return new TestCaseData("Hound").SetProperty(PropertyA, "ValueA").SetProperty(PropertyA, "ValueB");
}
```

It looks a bit verbose, but it gives you the flexibility to set different properties on each child test.

I am marking this as a question and closing. Feel free to continue to post if you have questions...

**Comment by sircody01** [comment]
@rprouse Thanks for the tips and suggestion. I tried your suggestion:
```
   yield return new TestCaseData("Fox").SetProperty(PropertyA, "ValueA").SetProperty(PropertyA, "ValueB");
```
What I find is that it seems the second SetProperty overwrites the first one. The test only receives 1 property with value "ValueB". The first "ValueA" is missing when the test gets control.

**Comment by rprouse** [comment]
@sircody01 what version of NUnit are you using? I used your `Test2` with the `MyData` I wrote and the latest version of NUnit and the test passed.

Here is the code from a project I use for testing issues like this,

https://github.com/rprouse/nunit-tests/blob/b93ceab128945f02f3458e0ae0f18429aa19c663/nunit-v3/TestCaseDataTests.cs#L80

**Comment by sircody01** [comment]
Never mind. I took a closer look at my code and discovered I put quotes in my code where they should not have been. After removing the quotes it works the way you say.
