### ISSUE TITLE
Suggestion: log exception thrown in ActualValueDelegate

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#3072]
```
object getResponse() => MakeSomeRequest();
Assert.That(someResponse, Is.EqualTo(ExpectedValue));
```

In code about if MakeSomeRequest fails with exception, I would only see the exception itself. Maybe would make sense to log expected value as well, something like
```
Expected: equal to 'ExpectedValue'
Actual: exception thrown *Exception details*
```
That would make failed test analysis easier, I think/

**Comment by jnm2** [comment]
Sounds good to me! @nunit/framework-team Okay to mark 'Good first issue'?

**Comment by mikkelbu** [comment]
The assertion is executed as it is passed an `ActualValueDelegate` that is evaluated by the assertion (below I've made a more complete example - I need it to fully understand the original question)

```csharp
    [Test]
    public void Test1()
    {
      object getResponse() => MakeSomeRequest();
      Assert.That(getResponse, Is.EqualTo("42"));
    }

    static object MakeSomeRequest()
    {
      if (DateTime.MinValue < DateTime.Now)
        throw new ArgumentNullException("HELLO");
      return null;
    }
  }
```
If we execute the test then it fails with 
```
Result StackTrace:	
at NameSpace.Class1.MakeSomeRequest() in SOMEFOLDER\Class1.cs:line 24
   at NameSpace.Class1.<>c.<Test1>g__getResponse|0_0() in SOMEFOLDER\Class1.cs:line 17
   at NUnit.Framework.Constraints.Constraint.GetTestObject[TActual](ActualValueDelegate`1 del) in C:\src\nunit\nunit\src\NUnitFramework\framework\Constraints\Constraint.cs:line 150
   at NUnit.Framework.Constraints.Constraint.ApplyTo[TActual](ActualValueDelegate`1 del) in C:\src\nunit\nunit\src\NUnitFramework\framework\Constraints\Constraint.cs:line 124
   at NUnit.Framework.Assert.That[TActual](ActualValueDelegate`1 del, IResolveConstraint expr, String message, Object[] args) in C:\src\nunit\nunit\src\NUnitFramework\framework\Assert.That.cs:line 143
   at NUnit.Framework.Assert.That[TActual](ActualValueDelegate`1 del, IResolveConstraint expr) in C:\src\nunit\nunit\src\NUnitFramework\framework\Assert.That.cs:line 126
   at NameSpace.Class1.Test1() in SOMEFOLDER\Class1.cs:line 18
Result Message:	
System.ArgumentNullException : Value cannot be null.
Parameter name: HELLO
```
That being said I also find little value in this, as the expect values in most cases are constants and not do not "exists" where the exception is thrown.

**Comment by jnm2** [comment]
@Dreamescaper Can you explain the scenario you found where knowing the actual value would have helped figure out the exception?

**Comment by Dreamescaper** [comment]
Mostly for API tests, where I can't control all exceptions thrown.
For example, I'm trying to get some entity from service, and to assert that Name is equal to "Test Name". If this GET request fails with 404 or 500 error - I can see only that exception without any info what i actually tried to assert. That's especially useful if those tests are executed in CI, where access to test source code is harder.
It could also help to have explicit difference between exception in some pre-conditions (where test result probably names no value), and actually trying to assert things.

**Comment by CharliePoole** [comment]
@mikkelbu My misunderstanding. However, the only code that is executed is in the base `Constraint`class. At the point the exception is thrown, we don't know what kind of derived constraint is being executed. So it appears that the exception, now handled in the base, would have to be handled by every different derivedp constraint in order to give a message that relates to  what is being tested.

Of course, we could do this if it brings value, but I just don't see it. You know your code threw an exception in a particular line.The exception is the same no matter what test you were about to make on the actual value.It's not clear that including the expected value will really add anything to diagnosing the problem.

IMO, in the situation that Dreamscaper outlines, the call that is failing is what ought to be first asserted, before asserting on the value of what is returned. Why not just write

```C#
var response;
Assert.That(response = MakeSomeRequest(), Does.Not.Throw); // or equivalent lambda
Assert.That(response, Is.EqualTo("42"));
```

Which __explicitly__ tests that the call (1) does not throw and (2) returns what is expected.
