### ISSUE TITLE
Azure DevOps build fails in Save package artifacts

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit#3109]
It fails with the message "File upload failed even after retry." and logging at the logs it states 
```
2018-12-06T10:30:50.0592970Z Fail to upload 'D:\a\1\a\NUnit.Framework-3.12.0.zip' due to 'TF400813: The user '0de7c0cc-4788-4aa7-a5d1-963778911bd6' is not authorized to access this resource.'.
2018-12-06T10:30:50.0593299Z Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: The user '0de7c0cc-4788-4aa7-a5d1-963778911bd6' is not authorized to access this resource.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Boolean uploadFirstChunk, Object userState, Boolean compressStream)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.UploadAsync(IAsyncCommandContext context, Int32 uploaderId, CancellationToken token)
```
See e.g. https://nunit.visualstudio.com/NUnit/_build/results?buildId=1252 or https://nunit.visualstudio.com/NUnit/_build/results?buildId=1251

**Comment by jnm2** [comment]
Forgot to close. This was fixed: https://github.com/nunit/nunit/pull/3103#issuecomment-447021056
