### ISSUE TITLE
TestCaseSource "Single" cannot be converted to "int" issue

### ISSUE THREAD

**Issue by eberzosa** [nunit/nunit#3125]
I don't know if this is an issue or a feature :) but a TestCaseSource cannot be used in two methods with different parameter types, in the following case, the second test fails with  Object of type 'System.Single' cannot be converted to type 'System.Int32'

`class Test
   {
      private static readonly TestCaseData[] Cases =
      {
         new TestCaseData("", 0),
         new TestCaseData("", 1)
      };
      
      [TestCaseSource(nameof(Cases))]
      public void TestA(string a, float b)
      {
      }

      [TestCaseSource(nameof(Cases))]
      public void TestB(string a, int b)
      {
      }
   }`

**Comment by mikkelbu** [comment]
I can reproduce the issue and the problem is in 
https://github.com/nunit/nunit/blob/6d030213f861161f25badb3a5a6ac147c9dc1e95/src/NUnitFramework/framework/Internal/TypeHelper.cs#L244-L258
where we change the integer into a float.

I don't know much about this area of the codebase, and it looks like this behaviour is old. It was introduced in https://github.com/nunit/nunit/commit/57f64ef3a3b0c52a73df09512687d11c421d60a9#diff-f6d1cef53e8881b5735640354e2d8f5d with the commit message "convert args in advance to support building for the compact framework", so perhaps it is no longer necessary, but this will require a more thorough examination.

**Comment by CharliePoole** [comment]
I vaguely recall that we needed to do this for CF. The conversion was handled automatically for other platforms. That may or may not still be true but as it's tested it should be easy to see.

My suspicion is that the conversion may be done once and cached rather than for each method, but I haven't had time to check - we have a visitor for the holidays.

**Comment by mikkelbu** [comment]
I tried to remove `TypeHelper.ConvertArgumentList` (the method called above) and that solved the problem, and all the other tests were still executed successfully.

The only "problem" I have with removing `TypeHelper.ConvertArgumentList` is that it is public - although in the `NUnit.Framework.Internal` namespace. I tried to search for other usages of this method in other projects on the internet, but I did not find any. The only results I got was this codebase and the issue #1881.

Personally, I think we should remove the usage and the method, but we can also remove the usage and obsolete the method (and the remove the method in a later release).

**Comment by ChrisMaddock** [comment]
Sounds removable to me. 👍

**Comment by oznetmaster** [comment]
This code has never had a CF conditional around it, so it was not added specifically for CF.

Perhaps it does affect other platforms as well?

I will try taking it out and see if it breaks CF.  Will report back after new years.

**Comment by CharliePoole** [comment]
I'm pretty sure that's why I added it... which is why I wrote the comment. Strictly speaking, it could have been a limitation of the C# implementation in VS2008, which we used to compile that version, rather than CF itself.

**Comment by oznetmaster** [comment]
Since it will be very difficult to test this exhaustively, I would suggest doing what @CharliePoole suggests:  move the code to where it will be called for each use of the data source rather then just once.

**Comment by stevenaw** [comment]
There's been a few different functions that do type conversions for parameters that have slowly been consolidated into `ParamAttributeTypeConversions`:

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/ParamAttributeTypeConversions.cs#L101

It looks like that doesn't currently convert "single". Would a good first step for this be to add single support to that function, and then have TestCaseSource call it instead? I figure if the goal is to eventually remove pre-conversions, it might be easiest to do if they're all in one place

**Comment by CharliePoole** [comment]
The original goal was for each attribute to be independent, allowing for user-defined attributes to work as the creator might see fit.

Not sure what the current goal is as it's not articulated.

**Comment by stevenaw** [comment]
Oh I see thanks for clarifying @CharliePoole  Then yes, consolidating type conversions may not be in line with that goal. I wasn't aware of that goal, or if it's changed

**Comment by CharliePoole** [comment]
Nor am I. As you say, there has been some consolidation, which might imply a change. I'd prefer the intent to be articulated, which is why I made the comment.

One approach that might make sense would be to centralize "normal" conversions like int to double while separating in each attribute the "special" ones, like those from string.

**Comment by savornicesei** [comment]
Hi all,

I would like to bring this issue into focus since it impacts the project I'm working on.
We just migrated out tests from xUnit and a lot of them fail with
```
ConversionTests.ToInt_FromObject_WithGivenCultureInfo(1.0m,,1.0d)

System.ArgumentException : Object of type 'System.Double' cannot be converted to type 'System.Int32'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args) in D:\a\1\s\src\NUnitFramework\framework\Internal\Reflect.cs:line 266
```
This is the test:
```
public void ToInt_FromObject_WithGivenCultureInfo(object value, CultureInfo cultureInfo, int expected)
		{
			//Arrange

			//Act
			var result = Conversion.ToInt(value, cultureInfo);

			//Assert
			result.Should().Be(expected);
		}
```
and in the data source I have
```
yield return new TestCaseData("6‎", CultureInfo.InvariantCulture, defaultValue); //empty unicode character
				yield return new TestCaseData("6‎", CultureInfo.CreateSpecificCulture("en-US"), defaultValue); //empty unicode character
				yield return new TestCaseData("6‎", CultureInfo.CreateSpecificCulture("ro-RO"), defaultValue); //empty unicode character
yield return new TestCaseData(1.1, CultureInfo.InvariantCulture, 1.1);
				yield return new TestCaseData(1.1, CultureInfo.CreateSpecificCulture("en-US"), 1.1);
				yield return new TestCaseData(1.1, CultureInfo.CreateSpecificCulture("ro-RO"), 1.1);

				yield return new TestCaseData(1.0M, CultureInfo.InvariantCulture, 1.0);
				yield return new TestCaseData(1.0M, CultureInfo.CreateSpecificCulture("en-US"), 1.0);
				yield return new TestCaseData(1.0M, CultureInfo.CreateSpecificCulture("ro-RO"), 1.0);
```
The tests checking the unicode values show as 'Inconclusive. test not run'

We're using NUnit 3.12. Is there a workaround for this?

Thank you.

**Comment by mikkelbu** [comment]
@savornicesei This is not the same error as in the original post. I tried to run the code, but I'm unsure what "empty unicode character" is, so I cannot answer this part.

The failing testcases, however, is since the test method expects the last argument to be an integer, and you pass doubles. So changing the signature from `public void ToInt_FromObject_WithGivenCultureInfo(object value, CultureInfo cultureInfo, int expected)` to `public void ToInt_FromObject_WithGivenCultureInfo(object value, CultureInfo cultureInfo, double expected)` should solve the problem.

EDIT: I was actually a bit surprised that XUnit rounds passed doubles to nearest integer (if the test methods expects an integer). So the first two cases pass and the last two fail with `Expected: 2 ... Actual:   1`.
```csharp
        [Theory]
        [InlineData(1.2)]
        [InlineData(1.4)]
        [InlineData(1.5)]
        [InlineData(1.9)]
        public void TestXUnit(int expected)
        {
            Assert.Equal(expected, 1);
        }
```
