### ISSUE TITLE
Can't run tests in a .net 3.5 project

### ISSUE THREAD

**Issue by FruitcakeElemental** [nunit/nunit#3143]
Hi Guys,

I updated my Visual Studio (to 15.9.5) the other day then went to run a unit test from test explorer in a 3.5 project of mine and got this error message:

`[23/01/2019 2:15:45 AM Informational] ------ Run test started ------
[23/01/2019 2:15:45 AM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Framework35 is not supported. For projects targeting .Net Framework 3.5, please use Framework40 to run tests in CLR 4.0 "compatibility mode".
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.UpdateRunSettingsIfRequired(String runsettingsXml, List`1 sources, String& updatedRunSettingsXml)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass19_0.<StartTestRun>b__0()
[23/01/2019 2:15:45 AM Informational] ========== Run test finished: 0 run (0:00:00.1069443) ==========`

I am using the latest NUnit and NUnit3TestAdapter nuget packages.

Googling for answers I found this might be related? [https://github.com/Microsoft/vstest/pull/1723](url). I suspect this may be Microsoft's change, but the error message is really unhelpful, I've spent a while googling how to run tests in 4.0 compatibility without any success.

**Comment by mikkelbu** [comment]
Hi @FruitcakeElemental This is more a vstest question than a NUnit question, but I guess that the solution is just to set the target framework of your test project to be at least 4.0. So right-click the project file in VS, select Properties, the tab Application, and select .NET Framework 4 as the target framework - or just update the csproj file by hand.

Of course, if you use the same project for both production code and test code then perhaps it will not be possible to change the target framework, but that depends on the constraints that you are under.

In VS it will look similar to this.
<img width="400" alt="set target framework" src="https://user-images.githubusercontent.com/1007631/51559218-a6d37080-1e81-11e9-832a-366783adfc68.png">

The problem was also discovered in https://github.com/nunit/nunit/issues/3070#issuecomment-440490373

**Comment by rprouse** [comment]
The error isn't terribly useful, but it is coming from Visual Studio, not from NUnit or the adapter (`Microsoft.VisualStudio.TestPlatform`), so we can't fix it sorry. Visual Studio has stopped supporting targeting tests for .NET 3.5 and older.
