### ISSUE TITLE
NUnit3-console + timeout + shadowcopy

### ISSUE THREAD

**Issue by ybeapps** [nunit/nunit#3185]
Hi,

I have tests assemblies
I'm running the following command:

> "C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" --shadowcopy [myTestsDlls] --timeout=4000

I have a test that uses the TimeoutAttribute to override the default timeout (of 4 seconds) like this:
```
[Test, Timeout(90000)]
public void MyTest()
```

I expects this test to pass successfully because it has enough time defined in the timeout attribute.

The actual result is:

> Errors, Failures and Warnings
> 
> 1) Error : MyTest
> System.AggregateException : One or more errors occurred.
>   ----> System.NullReferenceException : Object reference not set to an instance of an object.
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at MyTestedCode(Int32 endPageNumber) in C:\Projects\MyCode.cs:line 164
>    at MyTest() in C:\Projects\MyTest.cs:line 128
> --NullReferenceException
>    at MyNamespace.<RunAsync>d__10.MoveNext() in C:\Projects\MyCode.cs:line 67

I believe this is a bug. when I change the timeout switch to a bigger value there is no issue!
Also, When I remove the --shadowcopy switch the tests pass!
Both resolves the issue:

Solution 1:

> "C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" --shadowcopy [myTestsDlls] --timeout=90000

Solution 2:

> "C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" [myTestsDlls] --timeout=4000

**Comment by CharliePoole** [comment]
What is your purpose in using `--shadowcopy`?

What is your target platform?

What versions of the NUnit framework and console are you using?

**Comment by ybeapps** [comment]
I didn't put any reasonable thought on why using "shadowCopy", I just used it. I don't really need it.

> NUnit Console Runner 3.9.0
> Copyright (c) 2018 Charlie Poole, Rob Prouse
> 
> Runtime Environment
>    OS Version: Microsoft Windows NT 10.0.16299.0
>   CLR Version: 4.0.30319.42000
> 
> Run Settings
>     DisposeRunners: True
>     DefaultTimeout: 4000
>     InternalTraceLevel: Verbose
>     WorkDirectory: C:\Projects\BIS_R2\Monitor\trunk
>     ImageRuntimeVersion: 4.0.30319
>     ImageTargetFrameworkName: .NETFramework,Version=v4.7.2
>     ImageRequiresX86: False
>     ImageRequiresDefaultAppDomainAssemblyResolver: False
>     NumberOfTestWorkers: 4

**Comment by CharliePoole** [comment]
M

**Comment by CharliePoole** [comment]
That gives you an easy solution but this may still be a bug for NUnit.

**Comment by ybeapps** [comment]
You’re right 
That is the reason I opened a new issue
