### ISSUE TITLE
"TearDown method failed. SetUp" error?

### ISSUE THREAD

**Issue by Plasma** [nunit/nunit#3188]
Hello,

I am experiencing sporadic unit test failures with a confusing stack trace message.

An exception may look like:

```
TearDown method failed. SetUp : System.ExampleException : ExampleMessage
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at MyApp.Domain.Tests.BaseFixture.SetUp()
   at MyApp.Persistence.Tests.DatabaseFixture.SetUp()
   at MyApp.Services.Tests.ServiceFixture.SetUp()
   at MyApp.Services.Tests.MyService.SetUp()
--TearDown
   at MyApp.Services.Tests.ServiceFixture.TearDown()
```

First I am confused by it saying "TearDown method failed", OK, but then it immediately talks about SetUp(). What's happening here? 

If I read it right, Test 1 is going through a TearDown() phase, and the code path in NUnit for TearDown() then internally calls SetUp() on the next test, which is where I then encounter a NullRef exception.

When one of these kinds of errors happen, it cascades to future tests. Looking at some stack traces, I feel like there is a concurrent test run happening at one moment and so two concurrent tests are sharing the same objects.

If anyone can shed light on what the error message is elluding to and why the stack trace is confusing (TearDown talking about SetUp), and perhaps how a test could accidentally run concurrently? (Perhaps one test has an async task/process that does not get await'd so NUnit Runner thinks its finished and goes to next test too early?)

Thank you

**Comment by CharliePoole** [comment]
Are you sure this message is from NUnit? I can't find the text "TearDown methiod failed" anywhere in the current source code.

In any case, you have a failure in SetUp, which is immediately followed by a TearDown failure. There are two stack traces, with the TearDown trace shown after the label "--TearDown".

You should solve the SetUp problem first. Most likely that will also solve the TearDown issue. Start by figuring out why `BaseFixture.SetUp` is encountering an NRE.

**Comment by mikkelbu** [comment]
Closing this due to lack of activity. The message indicates that this comes from TeamCity's NUnit runner.

Please note that we will still see additional comments to this issue, so if more information become available then we can reopen the issue.
