### ISSUE TITLE
Null dereference in TestWorkerThreadProc

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3248]
[Found on .NET Core 2.0 on macOS in our CI build:](https://nunit.visualstudio.com/NUnit/_build/results?buildId=1683&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=00f564b5-c6ae-5329-43c9-96bc79a72ec9&lineStart=1565&lineEnd=1568&colStart=1&colEnd=119)

> ```
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc() in /Users/vsts/agent/2.150.3/work/1/s/src/NUnitFramework/framework/Internal/Execution/TestWorker.cs:line 137
>    at System.Threading.Thread.ThreadMain_ThreadStart()
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> ```

I also hit the same thing on Mono on my local Ubuntu vm: https://github.com/nunit/nunit/pull/3095#issuecomment-489441743

**Comment by jnm2** [comment]
@oznetmaster This was added in https://github.com/nunit/nunit/pull/1202:

https://github.com/nunit/nunit/blob/8a6245b90276fcab21a11bf65b06bbcdd562d67b/src/NUnitFramework/framework/Internal/Execution/TestWorker.cs#L188-L189

Can you shed light on the difference it makes if `_currentWorkItem` is set to null here?

**Comment by oznetmaster** [comment]
Not sure exactly what you are asking?

**Comment by jnm2** [comment]
@oznetmaster I'd like to remove that line, but I don't understand the effect it has (besides a possible NullReferenceException). Why is it there, or what would break if it was removed?

**Comment by OsirisTerje** [comment]
@manfred-brands @stevenaw 

Another High Pri bug, but we haven't seen this since, afaik, and besides that, this is part of the StopRun which we don't do this way any more (force = true:  am I right?).    Also see @rprouse comment here:  https://github.com/nunit/nunit/issues/3276#issuecomment-1121769267

1. Can we just close this?
2. Should we look more into this ?

**Comment by manfred-brands** [comment]
I'm in favour of removing force stop from the API like @rprouse said.
Maybe a good time for 5.0.

Remove any reference to `Thread.Abort` as even on .NET Framework it won't cleanup as teardown won't be executed.

There are two options:
* Silently ignore force
* Remove parameter from API, but that will break all runners.

**Comment by stevenaw** [comment]
Was this related to `StopRun(true)`? I admit I can't recall as it's been many years since I encountered this myself. 

I would be fine with closing this one as `cant repro`.

I am comfortable with removing `StopRun(true)` as well, but would like to suggest we ensure we communicate that clearly enough in advance. I can't recall if we've marked the API method with the overload as obsolete or not, but phasing in any change here helps minimize any adoption friction. I think at least one popular consumer (Jetbrains) has been caught by surprise in past releases. The first step to that would likely be a dedicated GH issue around deprecation+removal.

EDIT: It might also be worth discussing if we were to only deprecate or drop it for certain TFMs/runtimes instead of holistically
