### ISSUE TITLE
Test discovery does not appear to be correct when test cases contain arrays of tuples

### ISSUE THREAD

**Issue by paynecrl97** [nunit/nunit#3422]
Take this test:
```
[TestCaseSource("MyTestCases")]
public void MyTest(string path, (string type, string name)[] expectedResults)
{
}

static object[] MyTestCases =
{
	// Folders
	new object[] { "pathA", new[] { (type: "TypeA", name: "A") } },
	new object[] { "pathB", new[] { (type: "TypeA", name: "A"), (type: "TypeB", name: "B") } },
};
```

This is how the Test Explorer in VS 2019 displays the test:

![image](https://user-images.githubusercontent.com/2872984/68610250-3c8ec980-04af-11ea-9e1f-92e057e2a467.png)

I'd expect there to be a line with the text `MyTest (2)`, and under that I'd expect to see the two test cases. In this state, the test runner fails if you try and run all the tests in the class: `An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Missing '('. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.`

Now, change the test cases so that the arrays are now the same length:

```
[TestCaseSource("MyTestCases")]
public void MyTest(string path, (string type, string name)[] expectedResults)
{
}

static object[] MyTestCases =
{
	// Folders
	new object[] { "pathA", new[] { (type: "TypeA", name: "A") } },
	new object[] { "pathB", new[] { (type: "TypeB", name: "B") } },
};
```

This is better, but still not correct:
![image](https://user-images.githubusercontent.com/2872984/68610431-a27b5100-04af-11ea-9b06-8bfa3c98e193.png)

Note that the tests are nested as expected, but the name of the test is `MyTest]) (2)` - the test name is siffixed with `])`. It is now possible to run all the tests in the class (because the tuple arrays are all the same length).

**Comment by paynecrl97** [comment]
I've realised that this may well be an issue for https://github.com/nunit/nunit3-vs-adapter. Let me know if so, and I can move it.

**Comment by CharliePoole** [comment]
Can you run this under the console runner? If so, examine the test names created in the XML to decide if it's an NUnit problem or an adapter problem. One of us will transfer the issue if you say so.

**Comment by paynecrl97** [comment]
Full result file:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="1" result="Failed" label="Error" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0" engine-version="3.10.0.0" clr-version="4.0.30319.42000" start-time="2019-11-13 20:30:44Z" end-time="2019-11-13 20:30:45Z" duration="1.600006">
  <command-line><![CDATA[nunit3-console  "C:\xxxx.dll"]]></command-line>
  <test-suite type="Assembly" id="0" name="" fullname="" runstate="NotRunnable" testcasecount="1" result="Failed" label="Error" start-time="2019-11-13 20:30:45Z" end-time="2019-11-13 20:30:45Z" duration="0.001" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
    <failure>
      <message><![CDATA[NUnit.Engine.NUnitEngineException : The NUnit 3 driver encountered an error while executing reflected code.
  ----> System.InvalidCastException : Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.]]></message>
      <stack-trace><![CDATA[--NUnitEngineException
The NUnit 3 driver encountered an error while executing reflected code.

Server stack trace: 
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
--
InvalidCastException
Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)
]]></stack-trace>
    </failure>
  </test-suite>
</test-run>
```

**Comment by CharliePoole** [comment]
Is this a .NET Core test? If so, running under the console was bad advice on my part. :disappointed:

**Comment by paynecrl97** [comment]
Yes it's .NET Core, sorry I should have been clear about that in the original issue description.
