### ISSUE TITLE
Assert.That NullReferenceException depending on order of constraints

### ISSUE THREAD

**Issue by thomasfdm** [nunit/nunit#3429]
When making an assertion against value that is a nullable string and checking if the value is null or empty the throws a NullReferenceException or ArgumentException (depending on platform) but only if the Empty Constraint is checked against first.

For example, the following two code examples:

        [Test]
        public void ThrowsEx()
        {
            Assert.That(null, Is.Empty.Or.Null);
        }

        [Test]
        public void WorksFine()
        {
            Assert.That(null, Is.Null.Or.Empty);
        }

The first will throw an Exception where as the latter will pass as expected.

NUnit version 3.11.0 on .NET Core using the `dotnet test` command on OSX Mojave throws an Argument exception: 
```
Error Message:
   System.ArgumentException : The actual value must be a string, non-null IEnumerable or DirectoryInfo. The value passed was of type System.Object.
Parameter name: actual
  Stack Trace:
     at NUnit.Framework.Constraints.EmptyConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Constraints.OrConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
... My Code
```

Unity's Test Runner (not sure what version of NUnit it ships with but thought it worth mentioning) instead give a NullReferenceException:
```

System.NullReferenceException : Object reference not set to an instance of an object
---
at NUnit.Framework.Constraints.EmptyConstraint.ApplyTo (System.Object actual) [0x00001] in <59819be142c34115ade688f6962021f1>:0 
  at NUnit.Framework.Constraints.OrConstraint.ApplyTo (System.Object actual) [0x00001] in <59819be142c34115ade688f6962021f1>:0 
  at NUnit.Framework.Assert.That[TActual] (TActual actual, NUnit.Framework.Constraints.IResolveConstraint expression, System.String message, System.Object[] args) [0x0000e] in <59819be142c34115ade688f6962021f1>:0 
  at NUnit.Framework.Assert.That (NUnit.Framework.TestDelegate code, NUnit.Framework.Constraints.IResolveConstraint constraint, System.String message, System.Object[] args) [0x00001] in <59819be142c34115ade688f6962021f1>:0 
  at NUnit.Framework.Assert.That (NUnit.Framework.TestDelegate code, NUnit.Framework.Constraints.IResolveConstraint constraint) [0x00001] in <59819be142c34115ade688f6962021f1>:0 
... My and Unity's code
```

**Comment by CharliePoole** [comment]
The ordering difference is by design, of course. Apparently, NullConstraint isn't handling nullables correctly. I don't recall if we actually discussed how nullables should be handled in various constraints. Maybe we should.

**Comment by mikkelbu** [comment]
People have run into this before, so we added some text about it in the documentation last summer. https://github.com/nunit/docs/wiki/OrConstraint 
> Note that the constraint evaluates the sub-constraints left to right, meaning that `Assert.That(i, Is.Null.Or.GreaterThan(9));` where `i` is a nullable `int` will work for both `12` and `null`. On the other hand, `Assert.That(i, Is.GreaterThan(9).Or.Null);` will only work for `12`, but throw an exception for `null`, as `null` cannot be compared to `9`.

But I don't think that these pages are read a lot as they don't appear high in Google etc. unless you know exactly what to search for i.e. `OrConstraint`. The problem is that that people think of `Is.Empty.Or.Null` as compare the value against empty and if that fails then compare it against null, but they don't consider that these comparisons might throw exceptions. Personally, I think of the constraints similar to the conditions in if-statements, where order also matter.

```csharp
string valueToCompare = null;
if (!valueToCompare.Any() || valueToCompare == null) 
{
...
}
```

I cannot remember how the code is structured, but perhaps it would be possible to instead of failing on `null` values with exceptions, we could record a failing result and then perhaps the logic of the `OrConstraint` could handle the problem. This "patching" could perhaps eliminate the worst cases?

**Comment by CharliePoole** [comment]
It seems as if we need a whole set of pages on ConstraintExpressions, backed up by the documentation of the Constraints themselves.
