### ISSUE TITLE
Handling of passing null as element to a parametric testmethod that accepts a params

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit#3434]
The following issue can up when I tried to add (i.e. extend some tests to solve nunit.analyzers#169)

Given
```csharp
[TestCase(1, null)]
[TestCase(1, "A")]
public void TestHandlingOfNullInParams(params int[] a) {
    Assert.That(a, Is.EquivalentTo(new[] { 1, 0 }));
}
```
The first test passes, but the second test fails with
```
Result Message:	System.InvalidCastException : Object cannot be stored in an array of this type.
Result StackTrace:	
at System.Array.InternalSetValue(Void* target, Object value)
   at System.Array.SetValue(Object value, Int32 index)
   at NUnit.Framework.TestCaseAttribute.GetParametersForTestCase(IMethodInfo method) in D:\a\1\s\src\NUnitFramework\framework\Attributes\TestCaseAttribute.cs:line 263
```
I would have expected them both to fail, as null cannot be put in an int array, but due to the note mentioned on https://docs.microsoft.com/en-us/dotnet/api/system.array.setvalue?view=netframework-4.8#System_Array_SetValue_System_Object_System_Int32_ the null is "converted" into a zero.

> If SetValue is used to assign `null` to an element of an array of value types, all fields of the element are initialized to zero. The value of the element is not a null reference, and cannot be found by searching for a null reference.

And we use `SetValue` twice in 
https://github.com/nunit/nunit/blob/46f8b2ae280a6a6150e0f0bf86718a783d8b0c9d/src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs#L281-L307

So perhaps we should add special handling of placing null into value-type arrays?

**Comment by CharliePoole** [comment]
Perhaps. Or perhaps just detect that you are not passing an int[] and give an error?

**Comment by Phyrik** [comment]
Bit of an old issue but I'd like to work on it. Any consensus on which route to go with fixing this? I think a special case for setting null into value type arrays would be a good way to go

**Comment by stevenaw** [comment]
Thanks for asking @Phyrik ! This one would likely be a great candidate for work once we decide on an approach.

@CharliePoole @mikkelbu for what it's worth, I think I agree with @mikkelbu. If I compare this to the vanilla C# equivalent (below), I would expect `null` could be passed into a params as a null array _if it were the only extra parameter in the list_. If multiple args resolved to the `params` then it would make sense to me to add the "value type" check suggested since it seems to match how C# approaches this.

Is this a change we want to pursue? If so, are there other attributes which support params that we should ensure this behaviour is consistent between?

```csharp
public static void Main()
  {
    A(null);        // outputs "In params, passed null"
    //A(1, null);   // compiler error: Argument 2: cannot convert from '<null>' to 'int'

    B(null);        // outputs "In params, passed null"
    B("1", null);   // outputs "In params, array of length 2"
  }


  private static void B(params string[] o) {
    Console.Write($"In params");

    if (o is null)
      Console.WriteLine(", passed null");
    else
      Console.WriteLine($", passed array of length {o.Length}");
  }

  private static void A(params int[] o) {
    Console.Write($"In params");

    if (o is null)
      Console.WriteLine(", passed null");
    else
      Console.WriteLine($", passed array of length {o.Length}");
  }
```

**Comment by manfred-brands** [comment]
@stevenaw There are not many method declared with `params` that can deal with a `null` array argument. But I agree that a `TestCase(null)` should do just that.

I have found no other usages of `ParamArrayAttribute` in the source.
But there is code to try to figure out if an source array is an array or to be split into individual ones.

**Comment by CharliePoole** [comment]
Devil's advocate here... this is such an edge case that I wonder why it's needed. If you simply don't provide an argument to TestCase, an empty array is passed. If you are passing null deliberately to a test, you are probably trying to test error handling behavior _in the same test, which tests the happy path_. That doesn't seem like a practice to be encouraged.

**Comment by manfred-brands** [comment]
@CharliePoole You are right, the can test the `null` case with a separate: 
`Assert.That(() => Method(null), Throws.ArgumentNullException);`

**Comment by stevenaw** [comment]
Hmm I can appreciate that too @CharliePoole . I'd hoped you'd be able to provide a counter perspective 🙂

Going back to mikkel's original example, with passing null as the second element to a value array, what would make sense to you for the framework to do in that case? I agree with @mikkelbu that it's misleading to have null silently coalesced to 0 as an array element.

**Comment by stevenaw** [comment]
Or anyone else following this thread, obviously. :)
How should the framework handle that case?

**Comment by manfred-brands** [comment]
I think the behaviour should be the same as a cast to `int` and result in a  `System.NullReferenceException`.

```csharp
object? o = null;
return (int)o;
```

Unfortunately that is not the case for single `TestCase` either:
```
[TestCase(123, ExpectedResult = 123)]
[TestCase(null, ExpectedResult = 0)]
public int MethodThatExpectsAnInteger(int i) => i;
```

The `NUnit.Analyzer` correctly raises NUnit1001 but the NUnit test passes:

![image](https://user-images.githubusercontent.com/8655218/158040841-35351045-83a8-4086-8bef-3017e104fb66.png)

This is because when calling by reflection, the XML doc for _parameter_ says:

> Any object in this array that is not explicitly initialized with a value will contain the default value
for that object type. For reference-type elements, this value is null. For value-type
elements, this value is 0, 0.0, or false, depending on the specific element type.

Which is verified by the below test.

```csharp
[Test]
public void CallByReflection()
{
    MethodInfo? method = GetType().GetMethod(nameof(MethodThatExpectsAnInteger));

    Assert.That(method, Is.Not.Null);
    object? result = method.Invoke(this, new object?[] { null });
    Assert.That(result, Is.Not.Null);
    Assert.That(result, Is.TypeOf<int>());
    Assert.That(result, Is.EqualTo(0));
}
```

If we want to expected behaviour of failing, we need to check the parameters ourselves like in:
```csharp
[TestCase(123, ExpectedResult = true)]
[TestCase(default(int), ExpectedResult = true)]
[TestCase(null, ExpectedResult = false)]
public bool AssignableToInt(object? o) => typeof(int).IsAssignableFrom(o?.GetType());
```

For the `params` case, each element needs to be checked against the declared type of the parameter.

**Comment by stevenaw** [comment]
Thanks for the detailed investigation @manfred-brands ! If I understand right about a part of your comment, you're saying that the analyzer and the validation by the framework aren't in sync here in some cases?

**Comment by stevenaw** [comment]
I believe the conversion of null->0  was default behavior in the pre-.NET days of VB when not specifying the optional "strict" compilation option. It wouldn't surprise me if that directly shaped this behavior in the original version of .NET, to ensure compatibility.

That said, I personally feel this can be misleading to users in general, especially when using other languages like C#. I think I recall seeing (possibly in a comment by @CharliePoole ) that NUnit's approach to parameter passing is to accept what is given and to try to use it rather than trying to "be smart and guess what is desired", but in this case I'd advocate for some sort of validation here. It's possible it could break or surprise a small percentage of VB users, however.

What does the @nunit/framework-team think?
