### ISSUE TITLE
Odd Exit Code/Timing out

### ISSUE THREAD

**Issue by MJWherry** [nunit/nunit#3446]
We run our tests via console runner after jenkins builds the project. They are UIAutomation tests. Every once in a while the build will time out (after 3 hours, the normal runtime is under an hour). 

```
Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code -532462766
	at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e)
	at System.Diagnostics.Process.OnExited()
	at System.Diagnostics.Process.RaiseOnExited()
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
Build timed out (after 180 minutes). Marking the build as aborted.
ERROR: Aborted Ivy execution for InterruptedException
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.Channel.call(Channel.java:954)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
	at com.sun.proxy.$Proxy85.join(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
	at hudson.Launcher$ProcStarter.join(Launcher.java:470)
	at hudson.tasks.Ant.perform(Ant.java:232)
	at hudson.ivy.IvyModuleSetBuild$RunnerImpl.doRun(IvyModuleSetBuild.java:480)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.Run.run(Run.java:1764)
	at hudson.ivy.IvyModuleSetBuild.run(IvyModuleSetBuild.java:273)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

Different timeouts yield different exit codes but they point to the same file and error when using windows error searching tool [(Err_6.5.4.exe](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-code-lookup-tool))

The error definition lookup (decimal to hex) for the error codes returned
```
# anonymous HRESULT: Severity: FAILURE (1), Facility 0x1fff, Code 0xffff
# for hex 0xffff / decimal 65535
  CDERR_DIALOGFAILURE                                            cderr.h
```

The exit point seems to be random but just looking at the logs it seems its either happening during setup or teardowns (from what i see, not mid-test) and I cannot reproduce. The tests run on a vm but this has happened locally also. Below are example stack traces
[Example1.txt](https://github.com/nunit/nunit/files/3973696/Example1.txt)
[Example2.txt](https://github.com/nunit/nunit/files/3973699/Example2.txt)
[Example3.txt](https://github.com/nunit/nunit/files/3973700/Example3.txt)

**Comment by MJWherry** [comment]
Its been almost a month and no Tags even, are more logs or more information needed to look into this?

**Comment by mikkelbu** [comment]
The exit code indicates that an CLR exception has been thrown. The best way to pinpoint the error is to look into the "Windows Event Log" when the failure occur. Hopefully, that should give you more details about the error and perhaps also a stacktrace.

I have seen similar exit codes before where the problem was that the client code sometimes made an Debug.Assert fail in a third-party library.

Regarding more information then it could also be relevant to mention (but probably the most important is the event log):
* Version of the NUnit console
* Version of the NUnit framework
* Version of .NET (.NET Core / .NET Framework ...)
* More details about "UIAutomation tests". E.g. which language and which tools.

You can also try to run the console with the option `--inprocess`. Sometimes that provides better feedback.

**Comment by MJWherry** [comment]
Ahh, thank you, Ive checked the event logs and it seems i have a memory exception when dealing with the screen recording (https://github.com/sskodje/ScreenRecorderLib) on it's write method when writing the memory stream after the recording. This write happens during the teardown to each test (though unsure why it's hanging as it had crashed during a test and not just during the teardown where the write would occur

Per the other info, 
Nunit Console: 3.9.0
Nunit FW: 3.11.0
.Net: 4.6.1
Using a inhouse built FW that uses mainly microsofts UIAutomation Client/Provider/Types.

Ill append that to the command jenkins runs and see if it fails again,

I appreciate the response thank you. This has been plaguing me for a month now and needs to be fixed before it can be used in production.

**Comment by MJWherry** [comment]
This seems to be something with the screen recorder lib I use, so i am closing. Thank you for the help with tracing this issue
