### ISSUE TITLE
Test discovery fails with generic arrays

### ISSUE THREAD

**Issue by akalnay** [nunit/nunit#3524]
The following works as expected:  three tests are discovered and they all pass.

```C#
    public class Tests
    {
        [Test]
        public void Test1()
        {
            Assert.Pass();
        }

        [TestCase(new [] { 1, 3, 5 })]
        public void Test2(int[] values)
        {
            Assert.Pass();
        }

        [TestCase(1, new [] { 1, 3, 5 })]
        public void Test3<T>(T typeInferer, IEnumerable<T> values)
        {
            Assert.Pass();
        }

        //[TestCase(1, new[] { 1, 3, 5 })]
        //public void Test4<T>(T typeInferer, T[] values)
        //{
        //    Assert.Pass();
        //}
    }
```
Uncommenting Test4() prevents the tests from being discovered.  I tried this on both Visual Studio 2017 and Visual Studio 2019 with a Net Core 2.2 project and NUnit 3.11, NUnit3TestAdapter 3.11, and Microsoft.NET.Test.Sdk 15.9.0.

While I can work around it by having an IEnumerable<T> parameter instead of an array, I am wondering if this is a known issue and if it is, then if it is documented and I just missed it.

**Note**:  After posting my original message I realized that I had created my test project with the "NUnit Test Project (.NET Core)" template and that I probably needed to update the project's Nuget packages.  Indeed the packages needed updating, I updated them to NUnit 3.12.0, NUnit3TestAdapter 3.16.1, and Microsoft.NET.Test.Sdk 16.5.0.  Unfortunately updating the Nuget packages did not solve the issue I encountered:  Uncommenting Test4() still prevents the tests from being discovered.

**Comment by mikkelbu** [comment]
I tried to run the code in the nunit console and got the following exception
```
An exception was thrown while loading the test.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType(Type parmType, Type argType) in D:\a\1\s\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 106
   at NUnit.Framework.Internal.GenericMethodHelper.TryGetTypeArguments(Object[] argList, Type[]& typeArguments) in D:\a\1\s\src\NUnitFramework\framework\Internal\GenericMethodHelper.cs:line 80
   at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature(TestMethod testMethod, TestCaseParameters parms) in D:\a\1\s\src\NUnitFramework\framework\Internal\Builders\NUnitTestCaseBuilder.cs:line 220
   at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(IMethodInfo method, Test parentSuite, TestCaseParameters parms) in D:\a\1\s\src\NUnitFramework\framework\Internal\Builders\NUnitTestCaseBuilder.cs:line 64
```
From the exception I found #3259, which we solved almost a year ago, so this will be fixes in NUnit 3.13. Until then you can use the prerelease of NUnit from myget - https://www.myget.org/feed/nunit/package/nuget/NUnit. 

So I'm closing this as a duplicate, but note that we will still see additional comments in this issue.
