### ISSUE TITLE
"Test host process crashed : Unhandled exception." when switching to async test methods

### ISSUE THREAD

**Issue by doctor-house** [nunit/nunit#3595]
I have a suite of tests that make calls to an API. Previously the tests looked something like this:

```c#
public class TestClass : ApiTestFixture
{
    public ApiClient client;
    
    [SetUp]
    public void TestClassSetUp()
    {
        client = new ApiClient(/* Setup parameters */);
    }
 
    [Test]
    public void ApiTest()
    {
        var response = client.ExecuteRequest().Result;
        // Assert stuff about the response
    }
}
```
which worked fine, but then I read that NUnit 3 supports `async` test methods so I went through an updated a bunch of tests to look like the following:
```c#
public class TestClass : ApiTestFixture
{
    public ApiClient client;
    
    [SetUp]
    public void TestClassSetUp()
    {
        client = new ApiClient(/* Setup parameters */);
    }
 
    [Test]
    public async Task ApiTest()
    {
        var response = await client.ExecuteRequest();
        // Assert stuff about the response
    }
}
```
At first this seemed fine; after updating a small batch of tests, I would run those tests to see that they still worked and then merge the changes. One thing to note is that `client.ExecuteRequest()` throws an exception when the API endpoint it's calling fails for some reason. In the synchronous version of the tests this would just result in a test failure with the exception message printed, but with the asynchronous version I am consistently getting the following when I try to run all of the tests at once:
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. ApiException: api exception message
at ...
at ...
at ApiTests.TestClass.<ApiTest> in C:\src\ApiTests\TestClass.cs
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
at System.Threading.QueueUserWorkItemCallback.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
With the `ApiException` being an exception that previously just caused a test failure. I'm not too knowledgable on the inner workings of threads, tasks, and how NUnit handles this stuff so I don't know if this is an issue with NUnit, my code, or something else. Any insight into this would be appreciated. I can provide more info if needed.

Other possibly relevant things:
 - the test assembly has parallelizable scope set to fixture
 - the `async` tests run fine in small batches, although this might be because exceptions are less likely to occur in smaller batches
- the number of tests that run before the process crashes has been anywhere from ~5 tests to almost the entire suite (~couple hundred), and in one instance the entire suite ran successfully (reporting exceptions as failures without crashing).
- This occurs whether I'm executing tests via the command line or in visual studio.

Versions:
 - .NET Core 3.1
 - Microsoft.NET.Test.Sdk 16.6.1
 - NUnit 3.12
 - NUnitTestAdapter 3.16.1

**Comment by doctor-house** [comment]
After digging around through my test code I realized I made the following easy-to-miss mistake:

Old Test:
```c#
[Test]
public void ApiTest()
{
    var testList = client.ExecuteRequest(/* get list of data from API */).Result;
    testList.ForEach(item => {
        var testResponse = client.Execute(/* get API data based off current item */).Result;
        // Verify test response
    });
}
```

Naively make everything `async`:
```c#
[Test]
public async Task ApiTest()
{
    var testList = await client.ExecuteRequest(/* get list of data from API */);
    testList.ForEach(async item => {
        var testResponse = await client.Execute(/* get API data based off current item */);
        // Verify test response
    });
}
```

This works fine if the testResponse `await` call never throws an exception. However, `List<T>.ForEach` only has one definition for `Action<T>` type delegates, and therefore naively making that delegate `async` has the unintended effect of also making it an `async void` method. So any exceptions thrown in it aren't attached to a task and are unhandle-able from outside the lambda -> test process crashes. Looking at previous test runs, it seems this was the single point of failure and exactly when the test run would crash depended entirely on when this test was scheduled for execution. The one run where the process didn't seem to crash was because this test coincidentally was the last test to execute.

I switched the code to avoid using `async` delegates and everything works as expected:
```c#
[Test]
public async Task ApiTest()
{
    var testList = await client.ExecuteRequest(/* get list of data from API */);
    foreach (var item in testList)
    { 
        var testResponse = await client.Execute(/* get API data based off current item */);
        // Verify test response
    }
}
```
