### ISSUE TITLE
AreAlmostEqualUlps throws OverflowException for -0

### ISSUE THREAD

**Issue by markhobson** [nunit/nunit#3596]
Similar to #1046, the following assertion:

```
Assert.That(-0d, Is.EqualTo(0d).Within(1).Ulps);
```

Results in:

```
System.OverflowException : Negating the minimum value of a twos complement number is invalid.
   at NUnit.Framework.Constraints.FloatingPointNumerics.AreAlmostEqualUlps(Double left, Double right, Int64 maxUlps)
   at NUnit.Framework.Constraints.Numerics.AreEqual(Double expected, Double actual, Tolerance& tolerance)
   at NUnit.Framework.Constraints.Numerics.AreEqual(Object expected, Object actual, Tolerance& tolerance)
   at NUnit.Framework.Constraints.Comparers.NumericsComparer.Equal(Object x, Object y, Tolerance& tolerance, Boolean topLevelComparison)
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance, Boolean topLevelComparison)
   at NUnit.Framework.Constraints.EqualConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
```

Tested against NUnit 3.12.0.

**Comment by appel1** [comment]
Might be related to #1094 unless something has changed with the nunit ulps implementation since then.

**Comment by Poimen** [comment]
Ah, the good ol' `0 == -0` problem.

For those interested, there is a good write up on floating numbers here:
https://ciechanow.ski/exposing-floating-point/

The long and short of it is that IEEE floating point numbers represent `0` as two different amounts so `0` and `-0` are valid and different, while at the same time `0 == -0` is valid. Math is hard :rofl: 

@mikkelbu the easier fix is to do a `left == right` comparison when the signs mismatch to prevent the `Math.Abs` from throwing. If you would like, I can put a PR together if nobody is looking at this?

**Comment by mikkelbu** [comment]
@Poimen You are most welcome to look at this problem. Please note that the following is working
```csharp
Assert.That(-0d, Is.EqualTo(0d));
```
It is only when we compare the values with tolerance using "Ulps" - unit in the last place - that the problem occur.
