### ISSUE TITLE
Better exception message when using non-BCL class in property

### ISSUE THREAD

**Issue by jahav** [nunit/nunit#360]
Hi,
I have been using property attribute for some metadata using non-BCL class and I got Serialization exception per documentation of PropertyAttribute constructor:

> Constructor for use by derived classes that use the name of the type as the property name. Derived classes must ensure that the Type of the property value is a standard type supported by the BCL. Any custom types will cause a serialization Exception when in the client.

We have been using ReSharper to run our unit tests and the tests worked there so it took a while to track it down (we have tried NUnit GUI runner and Visual Studio Adapter). More helpful error message or perhaps even exception thrown from the constructor would be nice.

```
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
	public class LoginAsAttribute : PropertyAttribute
	{
		public LoginAsAttribute(Role role) : base(role)
		{
		}
	}
```

**Comment by constructor-igor** [comment]
```c#
    public class NUnitIssue360
    {
        [Test]
        [LoginAsAttribute]
        public void Test()
        {
            Console.WriteLine("NUnitIssue360:start");
            Assert.Pass();
            Console.WriteLine("NUnitIssue360:finish");
        }
    }

    [Serializable]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class LoginAsAttribute : PropertyAttribute
    {
        public LoginAsAttribute()
            : base(new Role())
        {
        }
    }
    public class Role
    {        
    }
```

NUnit v2 console shows next error:
```
System.Runtime.Serialization.SerializationException: Type 'NUnit_v2_samples.Role
' in Assembly 'NUnit_v2_samples, Version=1.0.0.0, Culture=neutral, PublicKeyToke
n=null' is not marked as serializable.

Server stack trace:
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMemb
ers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type
 type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberI
nfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSeriali
ze(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, S
erObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter
objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObj
ectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Obje
ct graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(S
tream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeMessage
Parts(ArrayList argsToSerialize)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage..ctor(IMetho
dReturnMessage mrm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.SmuggleIfPos
sible(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqS
tmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smug
gledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCa
llback(Object[] args)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   at NUnit.Core.TestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(
IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMes
sage msg)

Exception rethrown at [1]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   at NUnit.Core.TestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

**Comment by constructor-igor** [comment]
NUnit v2
```c#
    public class NUnitIssue360
    {
        [Test]
        [LoginAs]
        public void Test()
        {
            Console.WriteLine("NUnitIssue360:start");
            Assert.Pass();
            Console.WriteLine("NUnitIssue360:finish");
        }
    }

    [Serializable]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class LoginAsAttribute : PropertyAttribute
    {
        public LoginAsAttribute()
            : base()
        {
        }
    }

    [Serializable]
    public class Role
    {
    }
```

NUnit v2 console:
```
          <test-suite type="TestFixture" name="NUnitIssue360" executed="True" result="Success" success="True" time="0.003" asserts="0">
            <results>
              <test-case name="NUnit_v2_samples.NUnitIssue360.Test" executed="True" result="Success" success="True" time="0.002" asserts="0">
                <reason>
                  <message><![CDATA[]]></message>
                </reason>
              </test-case>
            </results>
          </test-suite>
```

According to documentation 
>The PropertyAttribute is not used for any purpose by NUnit itself, but it does display them in the >XML output file and in the Test Properties dialog of the gui.
I expect to see the attribute in nunit xml report.

**Comment by constructor-igor** [comment]
```c#
    public class NUnitIssue360
    {
        [Test]
        [LoginAs]
        public void Test()
        {
            Console.WriteLine("NUnitIssue360:start");
            Assert.Pass();
            Console.WriteLine("NUnitIssue360:finish");
        }
    }

    [Serializable]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class LoginAsAttribute : PropertyAttribute
    {
        public LoginAsAttribute()
            : base(new Role())
        {
        }
    }

    [Serializable]
    public class Role
    {
    }
```
Report file cannot be created and NUnit v2 console shows error message:
```
Unhandled Exception:
System.Runtime.Serialization.SerializationException: Unable to find assembly 'NU
nit_v2_samples, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Server stack trace:
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssem
bly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(Binary
AssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String obje
ctName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInf
ormationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, Bi
naryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWi
thMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(He
aderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAp
pDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize
(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCr
ossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObjec
t(MemoryStream stm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.FixupForNewA
ppDomain()
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMe
ssage reqMsg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   at NUnit.Core.TestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(
IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMes
sage msg)

Exception rethrown at [1]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   at NUnit.Core.TestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

**Comment by constructor-igor** [comment]
```c#
    public class NUnitIssue360
    {
        [Test]
        [LoginAs]
        public void Test()
        {
            Console.WriteLine("NUnitIssue360:start");
            Assert.Pass();
            Console.WriteLine("NUnitIssue360:finish");
        }
    }

    [Serializable]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class LoginAsAttribute : PropertyAttribute
    {
        public LoginAsAttribute()
            : base(new Role())
        {
        }
    }

    [Serializable]
    public class Role
    {
    }
```

NUnit v3 console:
```
      <test-suite type="TestFixture" id="1009" name="NUnitIssue360" fullname="NUnit_v3_samples.NUnitIssue360" classname="NUnit_v3_samples.NUnitIssue360" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-04-27 14:03:55Z" end-time="2015-04-27 14:03:55Z" duration="0.136000" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
        <test-case id="1010" name="Test" fullname="NUnit_v3_samples.NUnitIssue360.Test" methodname="Test" classname="NUnit_v3_samples.NUnitIssue360" runstate="Runnable" seed="1347475421" result="Passed" start-time="2015-04-27 14:03:55Z" end-time="2015-04-27 14:03:55Z" duration="0.135000" asserts="0">
          <properties>
            <property name="LoginAs" value="NUnit_v3_samples.Role" />
          </properties>
          <reason>
            <message />
          </reason>
          <output>NUnitIssue360:start
</output>
        </test-case>
      </test-suite>
```

**Comment by CharliePoole** [comment]
@constructor-igor So, would you summarize what the situation is for NUnit 3.0? Is there anything to fix?

**Comment by CharliePoole** [comment]
Also, should we add a test to ensure this continues to work?

**Comment by constructor-igor** [comment]
Yes, I didn't find any problems in nunit v3. related to the issue.
Ok. I'll try to implement relevant test. Probably, could you send me relevant test clase (sample how to test configuration file)?

**Comment by CharliePoole** [comment]
Something like the following... (mail list code... may not compile!)

[CustomProperty]
public void Test()
{
}

class CustomPropertyAttribute : PropertyAttribute
{
    public CustomPropertyAttribute()
    {
        Properties["Testing"] = new SomeClass();
    } 
}

All we want to know is that the test runs without crashing with a serialization error.

Charlie
