### ISSUE TITLE
Build issue with the latest .NET SDK 5.0.100-rc.2

### ISSUE THREAD

**Issue by siburny** [nunit/nunit#3650]
If I install latest version .NET SDK 5.0.100-rc.2 I am not able to compile the project, because NuGetRestore downloads FSharp.Core v5.0.0 in `nunit.testdata.fsharp` project. It errors out with the following message: "Package FSharp.Core 5.0.0 is not compatible with net45"

If I install version .NET SDK 5.0.100-preview.6 (which is listed in `global.json`) NuGetRestore downloads FSharp.Core v4.7.2 which lets me compile the solution without any errors.

**Comment by siburny** [comment]
It turns out they `FSharp.Core` removed `net45` in the target frameworks:

https://github.com/dotnet/fsharp/blob/8b2422463201b90f90336768d6869e4f606d3d35/src/fsharp/FSharp.Core/FSharp.Core.fsproj#L7

**Comment by rprouse** [comment]
Sorry for the late reply. I was waiting for the final version of .NET 5.0 to be released to see if there were more issues. I've been fixing and testing.

- Global.json needs to be updated
- We need to target FSharp.Core 4.7.2 and disable automatically targeting 5.0.0.
- The framework define `NETCOREAPP5_0` was switched to `NET5_0`
- Our WPF test code needs to target `net5.0-windows`
- There are some changes in nullability

I've fixed all of these, but now 8 tests in the .NET 5.0 target are failing. I am looking at those.

```
1) Error : NUnit.Framework.Internal.AsyncSetupTeardownTests.FailingSetupShouldLetExceptionBubbleUpUnwrapped
System.MissingMethodException : Method not found: 'Void NUnit.Framework.Internal.Commands.SetUpTearDownItem..ctor(System.Collections.Generic.IList`1<System.Reflection.MethodInfo>, System.Collections.Generic.IList`1<System.Reflection.MethodInfo>)'.
   at NUnit.Framework.Internal.AsyncSetupTeardownTests.FailingSetupShouldLetExceptionBubbleUpUnwrapped()

2) Error : NUnit.Framework.Internal.AsyncSetupTeardownTests.FailingTeardownShouldRecordFailureInTestContext
System.MissingMethodException : Method not found: 'Void NUnit.Framework.Internal.Commands.SetUpTearDownItem..ctor(System.Collections.Generic.IList`1<System.Reflection.MethodInfo>, System.Collections.Generic.IList`1<System.Reflection.MethodInfo>)'.
   at NUnit.Framework.Internal.AsyncSetupTeardownTests.FailingTeardownShouldRecordFailureInTestContext()

3) Error : NUnit.Framework.Internal.AsyncSetupTeardownTests.SuccessfulSetup
System.MissingMethodException : Method not found: 'Void NUnit.Framework.Internal.Commands.SetUpTearDownItem..ctor(System.Collections.Generic.IList`1<System.Reflection.MethodInfo>, System.Collections.Generic.IList`1<System.Reflection.MethodInfo>)'.
   at NUnit.Framework.Internal.AsyncSetupTeardownTests.SuccessfulSetup()

4) Error : NUnit.Framework.Internal.AsyncSetupTeardownTests.SuccessfulThenFailingSetupShouldLetExceptionBubbleUpUnwrapped
System.MissingMethodException : Method not found: 'Void NUnit.Framework.Internal.Commands.SetUpTearDownItem..ctor(System.Collections.Generic.IList`1<System.Reflection.MethodInfo>, System.Collections.Generic.IList`1<System.Reflection.MethodInfo>)'.
   at NUnit.Framework.Internal.AsyncSetupTeardownTests.SuccessfulThenFailingSetupShouldLetExceptionBubbleUpUnwrapped()

5) Error : NUnit.Framework.Internal.AsyncSetupTeardownTests.SuccessfulThenFailingTeardownShouldRecordFailureInTestContext
System.MissingMethodException : Method not found: 'Void NUnit.Framework.Internal.Commands.SetUpTearDownItem..ctor(System.Collections.Generic.IList`1<System.Reflection.MethodInfo>, System.Collections.Generic.IList`1<System.Reflection.MethodInfo>)'.
   at NUnit.Framework.Internal.AsyncSetupTeardownTests.SuccessfulThenFailingTeardownShouldRecordFailureInTestContext()

6) Failed : NUnit.Framework.Attributes.LifeCycleAttributeTests.OneTimeSetupTearDownIsCalledOnce
  Expected: Passed
  But was:  Failed
   at NUnit.Framework.Attributes.LifeCycleAttributeTests.OneTimeSetupTearDownIsCalledOnce() in C:\Src\NUnit\nunit\src\NUnitFramework\tests\Attributes\LifeCycleAttributeTests.cs:line 71

7) Failed : NUnit.Framework.Attributes.LifeCycleAttributeTests.OneTimeSetupTearDownIsCalledOnFirstInstance
  Expected: 35bc86c6-efa9-472c-baf7-b999929aa492
  But was:  00000000-0000-0000-0000-000000000000
   at NUnit.Framework.Attributes.LifeCycleAttributeTests.OneTimeSetupTearDownIsCalledOnFirstInstance() in C:\Src\NUnit\nunit\src\NUnitFramework\tests\Attributes\LifeCycleAttributeTests.cs:line 48

8) Failed : NUnit.Framework.Attributes.LifeCycleAttributeTests.SetupTearDownIsCalledOnce
  Expected: 1
  But was:  0
   at NUnit.Framework.Attributes.LifeCycleAttributeTests.SetupTearDownIsCalledOnce() in C:\Src\NUnit\nunit\src\NUnitFramework\tests\Attributes\LifeCycleAttributeTests.cs:line 58
```

**Comment by rprouse** [comment]
Test failures were caused by changes to the binary directories and old files left in some of the directories. Fix was just a minor update to the `build.cake` file. 

Now I just need to update the various CI builds and this should be done. PR incoming shortly.
