### ISSUE TITLE
PlatformAttribute and Net 5.0

### ISSUE THREAD

**Issue by reegeek** [nunit/nunit#3705]
Hi,

PlatformAttribute is not working if test project is targetting Net 5.0.

I have the following exception:
```csharp
System.ArgumentException: Unknown framework version 5.5 (Parameter 'version')
   at NUnit.Framework.Internal.RuntimeFramework.ThrowInvalidFrameworkVersion(Version version)
   at NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(Version version)
   at NUnit.Framework.Internal.RuntimeFramework..ctor(RuntimeType runtime, Version version)
   at NUnit.Framework.Internal.RuntimeFramework.<>c.<.cctor>b__33_0()`
```

Regards

**Comment by mikkelbu** [comment]
Hi @reegeek

This looks like a duplicate of #3565 and thus solved on master and part of the 3.13 release that soon should be ready. Can you check that the issue is gone, if you use one of the latest prerelease builds from MyGet - see https://www.myget.org/feed/nunit/package/nuget/NUnit.

**Comment by reegeek** [comment]
Your are right is the same issue. Sorry, I did found it.
I closed this issue.
Regards.

**Comment by mikkelbu** [comment]
No problem :)
