### ISSUE TITLE
Assert.Catch inside Assert.Multiple gives unclear failure message

### ISSUE THREAD

**Issue by provegard** [nunit/nunit#3849]
I have the following tests inside a .NET 5 project:

        [Test]
        public void Single()
        {
            Assert.Catch<ArgumentException>(() => throw new InvalidOperationException("x"));
        }
        
        [Test]
        public void Multi()
        {
            Assert.Multiple(() =>
            {
                Assert.Catch<ArgumentException>(() => throw new InvalidOperationException("x"));
            });
        }

When I run using `dotnet test`, I get:

```
  Failed Multi [50 ms]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.ArgumentException'.

  1)   Expected: instance of <System.ArgumentException>
  But was:  <System.InvalidOperationException: x
   at test_failures.Program.<>c.<Multi>b__1_1() in C:\kod\projects\test-failures\Program.cs:line 20
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>


  Stack Trace:
     at NUnit.Framework.Assert.Catch[TActual](TestDelegate code)
   at test_failures.Program.<>c.<Multi>b__1_0() in C:\kod\projects\test-failures\Program.cs:line 20
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at test_failures.Program.Multi() in C:\kod\projects\test-failures\Program.cs:line 18
  Failed Single [1 ms]
  Error Message:
     Expected: instance of <System.ArgumentException>
  But was:  <System.InvalidOperationException: x
   at test_failures.Program.<>c.<Single>b__0_0() in C:\kod\projects\test-failures\Program.cs:line 12
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>

  Stack Trace:
     at test_failures.Program.Single() in C:\kod\projects\test-failures\Program.cs:line 12
```

Note that the `Single` test results in good failure output:

```
  1)   Expected: instance of <System.ArgumentException>
  But was:  <System.InvalidOperationException: x
```

But the `Multi` test failure is worse:

```
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.ArgumentException'.
```

My csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>test_failures</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
  </ItemGroup>

</Project>
```

**Comment by mikkelbu** [comment]
I think you have split the error message in the wrong part, so the single results start at `Failed Single [1 ms]` (this would be more clear if there were some linebreaks before this). I've tried to split it up how I read the message

![image](https://user-images.githubusercontent.com/1007631/117420073-85e19d00-af1d-11eb-8fad-aa6f8b80fb82.png)


Adding confirm label, as I'm unsure if this is a problem - and if it is whether the problem is in the framework or in the adapter (or perhaps vs test).

But there is something strange about the `Assert.Catch` that makes it look like an exception is thrown. The following 

```csharp
        [Test]
        public void Multi()
        {
            Assert.Multiple(() =>
            {
                Assert.Catch<ArgumentException>(() => throw new InvalidOperationException("x"));
                Assert.That(1, Is.EqualTo(2));
            });
        }
```
gives (only one failing assertion)
```
  Failed Multi [59 ms]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.ArgumentException'.

  1)   Expected: instance of <System.ArgumentException>
  But was:  <System.InvalidOperationException: x
   at NUnitErrorReporting.Program.<>c.<Multi>b__1_1() in ...\NUnitErrorReporting\NUnitErrorReporting\Program.cs:line 19
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>


  Stack Trace:
     at NUnit.Framework.Assert.Catch[TActual](TestDelegate code)
   at NUnitErrorReporting.Program.<>c.<Multi>b__1_0() in ...\NUnitErrorReporting\NUnitErrorReporting\Program.cs:line 19
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at NUnitErrorReporting.Program.Multi() in ...\NUnitErrorReporting\NUnitErrorReporting\Program.cs:line 17
```
but if reverse the order of the asserts inside the multi-block then I get (two failing assertions)
```csharp
  Failed Multi [94 ms]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.ArgumentException'.

Multiple failures or warnings in test:
  1)   Expected: 2
  But was:  1

  2)   Expected: instance of <System.ArgumentException>
  But was:  <System.InvalidOperationException: x
   at NUnitErrorReporting.Program.<>c.<Multi>b__1_1() in ...\NUnitErrorReporting\NUnitErrorReporting\Program.cs:line 20
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>


  Stack Trace:
     at NUnit.Framework.Assert.Catch[TActual](TestDelegate code)
   at NUnitErrorReporting.Program.<>c.<Multi>b__1_0() in ...\NUnitErrorReporting\NUnitErrorReporting\Program.cs:line 20
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at NUnitErrorReporting.Program.Multi() in ...\NUnitErrorReporting\NUnitErrorReporting\Program.cs:line 17
```

So this could indicate that we have a problem with `Assert.Catch` inside `Assert.Multiple`.

**Comment by provegard** [comment]
You're right that I split the error message wrong, but regardless I think the `InvalidCastException` error is unexpected and confusing.

**Comment by mikkelbu** [comment]
I think the problem is that `Assert.Throws` and `Assert.Catch` when called with a type parameter tries to cast the thrown exception to that type and that will fail if the Exception is a wrong type. See e.g. https://github.com/nunit/nunit/blob/b34eba3ac1aa6957157857bddd116256c634afab/src/NUnitFramework/framework/Assert.Exceptions.cs#L180. We should probably only try to cast the Exception if we know that the cast can be done and otherwise return `null`.

So given the following test
```csharp
        [Test]
        public void AssertMultiple()
        {
            Assert.Multiple(() =>
            {
                Assert.That(1, Is.EqualTo(2));
                // Assert.Catch<ArgumentException>(() => throw new InvalidOperationException("Hello"));
                // Assert.Catch<ArgumentException>(() => { });
                Assert.That("A", Is.EqualTo("B"));
            });
        }
```
returns
```
  Message: 
    Multiple failures or warnings in test:
      1)   Expected: 2
      But was:  1
    
      2)   String lengths are both 1. Strings differ at index 0.
      Expected: "B"
      But was:  "A"
      -----------^
```
and if we include `Assert.Catch<ArgumentException>(() => { })` then we get three failed asserts
```
 Message: 
    Multiple failures or warnings in test:
      1)   Expected: 2
      But was:  1
    
      2)   Expected: instance of <System.ArgumentException>
      But was:  null
    
      3)   String lengths are both 1. Strings differ at index 0.
      Expected: "B"
      But was:  "A"
      -----------^
````
but if we also include `Assert.Catch<ArgumentException>(() => throw new InvalidOperationException("Hello"));` then we don't get all the assertions as the code is failing trying to cast `InvalidOperationException` into `ArgumentException`.
```
  Message: 
    System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.ArgumentException'.
    
    Multiple failures or warnings in test:
      1)   Expected: 2
      But was:  1
    
      2)   Expected: instance of <System.ArgumentException>
      But was:  <System.InvalidOperationException: Hello
       at NUnitErrorReporting.Program.<>c.<AssertMultiple>b__3_1() in C:\Users\Mikkel N. Bundgaard\source\repos\NUnitErrorReporting\NUnitErrorReporting\Program.cs:line 37
       at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>
    
    
  Stack Trace: 
```

**Comment by OsirisTerje** [comment]
Repro code here:  https://github.com/nunit/nunit.issues/tree/main/Issue3849

**Comment by OsirisTerje** [comment]
Bug fixed somewhere after 4.0.1. Main branch works.
