### ISSUE TITLE
Is.EquivalentTo no longer works for tuples that contain non-comparable elements

### ISSUE THREAD

**Issue by a-ctor** [nunit/nunit#3877]
The performance improvements concerning equivalence of large collections done in issue #2799 breaks checking equivalence for arrays with tuples that contain non-comparable elements.

The following test succeeds in 3.13.1 but fails in 3.13.2:

```c#
[Test]
public void Test1()
{
    var tuple1 = new Tuple<StringBuilder>(new StringBuilder());
    var tuple2 = new Tuple<StringBuilder>(new StringBuilder());
      
    var tuples = new[] { tuple1, tuple2 };
    var tuples2 = new[] { tuple1, tuple2 };
      
    Assert.That(tuples, Is.EquivalentTo(tuples2));
}
```

Exception:

```
System.InvalidOperationException : Failed to compare two elements in the array.
  ----> System.ArgumentException : At least one object must implement IComparable.
   at System.Array.SorterObjectArray.IntrospectiveSort(Int32 left, Int32 length)
   at System.Array.Sort(Array keys, Array items, Int32 index, Int32 length, IComparer comparer)
   at System.Collections.ArrayList.Sort(Int32 index, Int32 count, IComparer comparer)
   at System.Collections.ArrayList.Sort()
   at NUnit.Framework.Constraints.CollectionTally..ctor(NUnitEqualityComparer comparer, IEnumerable c)
   at NUnit.Framework.Constraints.CollectionItemsEqualConstraint.Tally(IEnumerable c)
   at NUnit.Framework.Constraints.CollectionEquivalentConstraint.Matches(IEnumerable actual)
   at NUnit.Framework.Constraints.CollectionEquivalentConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
   at TestProject1.Tests.Test1() in C:\Users\patrick.widauer\RiderProjects\Testit\TestProject1\UnitTest1.cs:line 21
--ArgumentException
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Collections.Generic.Comparer`1.System.Collections.IComparer.Compare(Object x, Object y)
   at System.Tuple`1.System.Collections.IStructuralComparable.CompareTo(Object other, IComparer comparer)
   at System.Tuple`1.System.IComparable.CompareTo(Object obj)
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Array.SorterObjectArray.SwapIfGreater(Int32 a, Int32 b)
   at System.Array.SorterObjectArray.IntroSort(Int32 lo, Int32 hi, Int32 depthLimit)
   at System.Array.SorterObjectArray.IntrospectiveSort(Int32 left, Int32 length)
```

This is a problem for both `Tuple<>` and `ValueTuple<>`. They implement `IComparable` but this comparison might not work at runtime. If none of the tuple's elements implements `IComparable` it will fail with an exception as seen above.

In #2799 arrays are sorted if the array type implements `IComparable`, which in cases of tuple types will fail when trying to sort the internal array.

**Comment by mikkelbu** [comment]
This have also been reported in #3841, so closing this as a duplicate.
