### ISSUE TITLE
Whole tests sequence is aborted when single test fails because of async bug

### ISSUE THREAD

**Issue by paatrofimov** [nunit/nunit#3930]
I had a bugged test on framework 4.8. Simplified reproduction is below.
Obviously, the assertion exception in B will be thrown outside of try-catch in ShouldPass and outside of B test scope.
On fw 4.8 this bug caused to fail only test B. Tests A, C succeeded.
On net 5 this bug causes all tests after B to acquire an inconclusive state. Even all other tests outside of Bar test fixture.
From my perspective, tests isolation has obviously degraded even though it might be due to changes in runtime implementation. Can this be fixed on the level of nunit library in order to roll back to the previous, preferable for user behavior?

```
    [TestFixture]
    internal class Bar
    {
        [TearDown]
        public void TearDown()
        {
            // imitate long cleaning teardown
            Thread.Sleep(5.Seconds());
        }

        [Test]
        public void A()
        {
            Console.WriteLine("Bar.A");
        }

        [Test]
        public void B()
        {
            ShouldPass(
                async () =>
                {
                    // imitate real async work to force context switch
                    await Task.Yield();
                    Thread.Sleep(3.Seconds());
                    Assert.Fail();
                });
        }

        [Test]
        public void C()
        {
            Console.WriteLine("Bar.C");
        }

        private static void ShouldPass(Action action)
        {
            var budget = TimeBudget.StartNew(10.Seconds());
            while(!budget.HasExpired())
            {
                try
                {
                    action();
                    return;
                }
                catch(AssertionException)
                {
                }
            }
        }
    }

    [TestFixture]
    internal class Foo
    {
        [Test]
        public void A()
        {
            Console.WriteLine("Foo.A");
        }
    }
```

tests sequence on fw 4.8

![image](https://user-images.githubusercontent.com/17619635/133026510-538282e4-8708-4666-9808-77c5e98fcfbe.png)

```
D:\tools\misc\bin\Release>dotnet test misc.exe -v normal
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.0.0.0: Test execution started
Running all tests in D:\tools\misc\bin\Release\misc.exe
   NUnit3TestExecutor discovered 4 of 4 NUnit test cases using Current Discovery mode, Non-Explicit run
Bar.A

  Passed A [5 s]
  Failed B [5 s]
  Stack Trace:
     at misc.Bar.<>c.<<B>b__2_0>d.MoveNext() in D:\tools\misc\Program.cs:line 57
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

Bar.C

  Passed C [5 s]
Foo.A

NUnit Adapter 4.0.0.0: Test execution complete
  Passed A [< 1 ms]

Test Run Failed.
Total tests: 4
     Passed: 3
     Failed: 1
 Total time: 16.3083 Seconds
```

tests sequence on net 5

![image](https://user-images.githubusercontent.com/17619635/133026487-076be604-afbc-4977-a1d8-30759aa5329c.png)

```
D:\tools\misc-core\bin\Release\net5.0>dotnet test misc-core.dll -v normal
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.0.0.0: Test execution started
Running all tests in D:\tools\misc-core\bin\Release\net5.0\misc-core.dll
   NUnit3TestExecutor discovered 4 of 4 NUnit test cases using Current Discovery mode, Non-Explicit run
Bar.A

  Passed A [5 s]
  Failed B [5 s]
  Stack Trace:
     at misc_core.Bar.<>c.<<B>b__2_0>d.MoveNext() in D:\tools\misc-core\Program.cs:line 70
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)

The active test run was aborted. Reason: Test host process crashed : Unhandled exception. NUnit.Framework.AssertionException
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at NUnit.Framework.Assert.Fail()
   at misc_core.Bar.<>c.<<B>b__2_0>d.MoveNext() in D:\tools\misc-core\Program.cs:line 70
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


Test Run Aborted.
Total tests: Unknown
     Passed: 1
     Failed: 1
 Total time: 10.7241 Seconds
```

**Comment by rprouse** [comment]
It sounds like you understand that `TestB` is incorrectly written because it isn't async and doesn't await `ShouldPass` and you are just asking for better test isolation to protect from these incorrect tests?

**Comment by paatrofimov** [comment]
Yes. I believe a single incorrect test should not lead to the termination of all following tests. And on fw it was exactly so.

**Comment by OsirisTerje** [comment]
This is still the case, and could have a  look at this one, as it is about test isolation.
Added repro here:  https://github.com/nunit/nunit.issues/tree/main/Issue3930

<img width="1601" height="1600" alt="Image" src="https://github.com/user-attachments/assets/30e67083-c57d-47f6-9037-f6f1e780a82d" />

@nunit/framework-team

**Comment by manfred-brands** [comment]
@OsirisTerje The problem here is that `ShouldPass` expects an `Action`.
The test passes in an `async void`! This is run by MS in the background and NUnit thinks the test has finished instantly.

`async void` is a red flag and is only allowed for UI event handlers.

In my Test projects this is flagged by 2 analyzers:

<img width="937" height="230" alt="Image" src="https://github.com/user-attachments/assets/8314f2d2-b3db-41c3-abe5-b19c31cb1325" />

The first one is from my work, the 2nd from Microsoft.VisualStudio.Threading.Analyzers with a message that explains it all.

I added a call to [TestScheduler.UnobservedTaskException](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception?view=net-10.0) in a `OneTimeSetUp`:

```csharp
    private string? CaughtExceptionMessage = null;

    [OneTimeSetUp]
    public void CatchUnobservedException()
    {
        TaskScheduler.UnobservedTaskException += HandleUnobservedTaskException;
    }

    private void HandleUnobservedTaskException(object? sender, UnobservedTaskExceptionEventArgs args)
    {
        // just catch unobserved exception to not fail the test run
        string test = TestContext.CurrentContext.Test.Name;
        CaughtExceptionMessage = $"Caught unobserved task exception in test {test}: {args.Exception}";
        args.SetObserved();
    }

    [TearDown]
    public void TearDown()
    {
        // imitate long cleaning teardown
        Thread.Sleep(5000);
        if (CaughtExceptionMessage is not null)
        {
            Assert.Fail(CaughtExceptionMessage);
        }
    }
```

Now test `B` fails with:

<img width="831" height="148" alt="Image" src="https://github.com/user-attachments/assets/6d5ab855-a139-42b0-a18e-a3ff9e9d7b76" />

BUT ONLY because the `TearDown` waits long enough.
If I remove the Sleep there, all tests are green as NUnit thinks the test finish before the test actually fails.

What to do here:
1. Augment the NUnit.Analyzer to not only detect `async void` Test methods, but also calls to `async void` methods.
2. Add an global `UnobservedTaskException` handler when starting a test run, to prevent us crashing. Note that the exception might come after the test is marked as passed.

PS. Rewriting `ShouldPass` to expect and `Func<Task>` does what was intended.

**Comment by OsirisTerje** [comment]
@manfred-brands Thanks!

Pt.1 :  This is something we can do.   
Pr.2 :  Is it worthwhile to do this ?  

Imho, having the analyzers flag "bad" code should be enough.  The framework should not cover everything - it may add too much costs (imho), and I am fine with it crashing as long as the analyzers scream out. 
Did you mean *we* could add an `UnobservedTaskException` handler in the framework or should the test writer do it in their code?  And if us, would that have any possible side effects?  And last, do we really need it when we have the analyzer warnings ?

PS: Since it works in framework, is that accidental, or is it a change between framework and .net ?

**Comment by manfred-brands** [comment]
Re 1. I will add an issue to the analyzers and implement it.
Re 2. Not all users run the analyzers, other suppress issues ... But that is then their problem.

The main issue with us adding it is whether we can adjust the test result when it fails much later. The other is that the test might fail after all tests are completed.
Let me try something tomorrow.

P.S. There were changes to default exception handling, I'll check.

**Comment by manfred-brands** [comment]
1: https://github.com/nunit/nunit.analyzers/issues/962


Both net462 and net8.0 fail with the same Unhandled Exception.
If I remove the `Thread.Sleep(5000)` from the `TearDown`, both tests pass because the test run finishes before the failing task can throw.

Adding `TaskScheduler.UnobservedTaskException` exception handling doesn't seem to be called. From what I read, the reason is that there is no `Task` instance in an `async void` method.

Adding `AppDomain.CurrentDomain.UnhandledException` only works on .NET Framework, but not on .NET 8.0

From [Async/Await - Best Practices in Asynchronous Programming](https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming):

_Async void methods have different error-handling semantics. When an exception is thrown out of an async Task or async Task<T> method, that exception is captured and placed on the Task object. With async void methods, there is no Task object, so any exceptions thrown out of an async void method will be raised directly on the SynchronizationContext that was active when the async void method started._

Based upon that I inserted a `SafeSynchronizationContext` when a test method is called.
This seems to work.

I put the code inside the `ContextUtils.DoIsolated`, but if you think there is a better place, let me know so we can move it.
Maybe move it into `NUnitTestAssemblyRunner.RunAsync`?

I added exception handlers of last resort to NUnitTestAssemblyRunner.
This would catch exceptions thrown by Tasks that are not awaited.
However by the time that handlers is called, the `TestExecutionContext.Current` is not set (it returns AdhocContext)
At least it won't bring NUnit Engine down.

An reporting might be lost depending on the time between the exception and the test run progressing.
