### ISSUE TITLE
Stderr/Console.Error will hold back unicode escaped log messages

### ISSUE THREAD

**Issue by mxschmitt** [nunit/nunit#4144]
TL;DR: log messages which are unicode escaped and are logged to the stderr are not shown. If you use the stdout instead, it works as expected.

Repro:

```csharp
namespace Example;

public class Tests
{
    [Test]
    public void Test1()
    {
        Console.Error.WriteLine("\u001B THIS WONT GET LOGGED!");
        Console.Error.WriteLine("\a THIS WONT GET LOGGED!");
        Console.WriteLine("\a THIS WILL GET LOGGED!");
        Console.Error.WriteLine("THIS WORKS");

        // original repro
        Console.Error.WriteLine("\u001b[38;5;45;1mpw:api \u001b[0mTHIS WONT GET LOGGED! \u001b[38;5;45m+23ms\u001b[0m");
        Assert.Pass();
    }
}
```

Expected: Two lines which get logged to the console.
Actual: Only the second line gets logged to the console.

Version: 3.13.3

Was reproducible with `dotnet new nunit -n Example`.

Looks related to this: https://github.com/nunit/nunit/issues/1787

**Comment by mxschmitt** [comment]
Got a stack by enabling the tracing logs: 

```
System.ArgumentException: '', hexadecimal value 0x1B, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteCDataSection(String text)
   at System.Xml.XmlEncodedRawTextWriter.WriteCData(String text)
   at System.Xml.XmlWellFormedWriter.WriteCData(String text)
   at NUnit.Framework.Interfaces.TNode.WriteCDataTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.get_OuterXml()
   at NUnit.Framework.Interfaces.TestOutput.ToXml()
   at NUnit.Framework.Internal.TestProgressReporter.TestOutput(TestOutput output)
```

When `\u001B` gets written to the stderr, it tries to write it to the xml file and it fails there since it's an invalid character.

We could either set [`CheckCharacters = false`](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlreadersettings.checkcharacters?view=net-6.0) or escape it somehow.

Actually its related to https://github.com/nunit/nunit/issues/850 now.
