### ISSUE TITLE
`NullReferenceException` during equality comparison of `IEnumerable` objects when `GetEnumerator()` returns `null`

### ISSUE THREAD

**Issue by ssrmm** [nunit/nunit#4150]
The following test produces a `NullReferenceException` in NUnits framework code. Note that the compared objects implement `IEnumerable`, but `GetEnumerator()` always returns `null` instead of an actual enumerator:
```csharp
using System.Collections;
using NUnit.Framework;

namespace Test;

[TestFixture]
public sealed class Tests
{
    [Test]
    public void Equality()
    {
        var one = new SomeEnumerable();
        var two = new SomeEnumerable();
        Assert.That(one, Is.EqualTo(two));
    }

    private sealed class SomeEnumerable : IEnumerable
    {
        public IEnumerator GetEnumerator() => null;
    }
}
```

```
Failed Equality [2 ms]
Error Message:
  System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
  at NUnit.Framework.Constraints.Comparers.EnumerablesComparer.Equal(Object x, Object y, Tolerance& tolerance, ComparisonState state)
  at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance, ComparisonState state)
  at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance)
  at NUnit.Framework.Constraints.EqualConstraint.ApplyTo[TActual](TActual actual)
  at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
  at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
  at Test.Tests.Equality()
```

At first glance this might seem a little stupid, because you wouldn't normally implement `GetEnumerator()` like this. However the real scenario where I encountered this issue seems pretty reasonable to me:

I'm using Moq to mock a complex type, that among other things implements `IEnumerable` and `IComparable` (`IComparable` is not related to the actual issue, but is necessary to get into the right code path that triggers the equality comparisons in this scenario). The tested code returns a collection of these mocks. I'm then using the `Is.EquivalentTo` constraint to check that the code returned the ones that I expect.

The tested code does not care about the `IEnumerable` implementation of the individual objects at all. Because of this I didn't specify any setups for `ISomeComplexThing.GetEnumerator()` and Moq creates a default implementation that just returns `null`.  NUnit however sees the `IEnumerable` implementation and will attempt to use it (and fail because it is not prepared for the case that it gets back `null`).

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Moq;
using NUnit.Framework;

namespace Test;

[TestFixture]
public sealed class MoqTests
{
    private static readonly ISomeComplexThing Thing1 = Mock.Of<ISomeComplexThing>(t => t.Name == "Thing 1");
    private static readonly ISomeComplexThing Thing2 = Mock.Of<ISomeComplexThing>(t => t.Name == "Thing 2");

    private static IEnumerable<ISomeComplexThing> NormalOrder()
    {
        yield return Thing1;
        yield return Thing2;
    }

    private static IEnumerable<ISomeComplexThing> ReverseOrder()
    {
        yield return Thing2;
        yield return Thing1;
    }

    [Test]
    public void SameOrder() // This succeeds
    {
        var actual = NormalOrder();
        var expected = NormalOrder();
        Assert.That(actual, Is.EquivalentTo(expected));
    }

    [Test]
    public void DifferentOrder() // This fails with NullReferenceException
    {
        var actual = NormalOrder();
        var expected = ReverseOrder();
        Assert.That(actual, Is.EquivalentTo(expected));
    }
}

[SuppressMessage("Design", "CA1010")]
[SuppressMessage("Naming", "CA1710")]
public interface ISomeComplexThing : IEnumerable, IComparable
{
    string Name { get; }
}

```

I'm using the latest NUnit 3.13.3.

**Comment by stevenaw** [comment]
Thanks @ssrmm I agree this is an unusual scenario but I understand why you would ask it.

My concern here with adding this is that it would make NUnit's handling of `IEnumerator` inconsistent with .NET's own, where similar code when used in a language construct like a `foreach` would also throw a `NullReferenceException` instead of silently not iterating (see this fiddle: https://dotnetfiddle.net/zPpi1n). This could then potentially hide bugs in others' code where they may have accidentally not implemented `IEnumerable` properly and need it to noisily fail.

Would it work instead for you to mock out the call to `GetEnumerator()` and have it return `Enumerable.Empty<object>()` ?

**Comment by manfred-brands** [comment]
The problem is with the implicit mock. I can appreciate you not implementing something you don't expect to be called, but in those cases uses a strict mock. That way you get an exception there instead of somewhere in the caller. Now your instance returns null from a method that is defined as not returning null, meaning you are in violation of the IEnumerable contract. If you pass an instance of your class to something else you cannot know what methods they call and it could even change when upgrading library versions.
Should NUnit give a preference to IEnumerable over IComparable, is similar to the discussion in #3631.

**Comment by ademchenko** [comment]
As in my opinion:
1. @stevenaw is right about the logic of null enumerator and foreach. Nevertheless how it is really implemented, logically, comparing by items should conform to the behaviour of iterating by foreach. To change that behaviour means to introduce a new class of bugs that are not easy to identify.
2. @manfred-brands have given a link to a discussion #3631. Reading the discussion, it becomes clear why it's made that way. That behaviour will probably remain the same.
3. Even if your proposal was implemented it would not solve the issue in general. Because the general case is not just to fix NullReferenceException but to avoid iteration over enumerable items in some cases. Suppose your type implements Equals which compares two objects just by the field "Name". Even with the fixed null reference, you wouldn't probably be satisfied with the result - for instance, NUnit will coalesce null iterators to empty arrays and decide that your object are equal because there are no elements in both. 

Meanwhile, your issue is solved very easily :-) Just specify the typed comparer to give a hint to NUnit about how you want to process comparing:
`Assert.That(one, Is.EqualTo(one).Using<SomeEnumerable>(EqualityComparer<SomeEnumerable>.Default));`

**Comment by ssrmm** [comment]
Thanks for explaining the rationale of the current behavior.

> Would it work instead for you to mock out the call to `GetEnumerator()` and have it return `Enumerable.Empty<object>()` ?

Not really. That would just make everything equal and render the test useless, right?

> The problem is with the implicit mock. I can appreciate you not implementing something you don't expect to be called, but in those cases uses a strict mock.

I guess I can do that, but that is also somewhat inconvenient:
1. There is no good way of knowing when to make the mock strict. Obviously I can do that now that I've diagnosed the problem, but I can't know that I need a strict mock before running into problems. The only criteria that I can really see is to make any mock strict as soon as it is passed to NUnit. Since strict mocks tend to increase the maintenance cost of the test suite, so I'd like to avoid creating too many of them.
2. In isolation it is a three-step thing: make the strict mock, provide an comparer and provide a setup for `IComparer` (NUnit invokes `Array.Sort()`, which then throws an exception on `CompareTo()` calls).
3. Making it strict will cause errors when printing differences between collections (similar to related issue #4152).

> If you pass an instance of your class to something else you cannot know what methods they call and it could even change when upgrading library versions.

I think that bad, generally speaking. If you call a method, you should know what kind of things it is going to both the system as a whole but also the objects that you pass it.  Case in point, I did not know that NUnit checks for this many types and especially not that it does recursive collection comparisons. Now that I encountered this issue, I've seen the documentation on it, but it is implicit behavior that caused the confusion.

> Should NUnit give a preference to IEnumerable over IComparable, is similar to the discussion in #3631.

I'm not really concerned with this personally at the moment. In my case reference equality is all I need.


> Even if your proposal was implemented [...]

I intentionally did not provide any proposals in the original post, because I am not the one best fit to provide one.

> [...} it would not solve the issue in general. Because the general case is not just to fix NullReferenceException but to avoid iteration over enumerable items in some cases. Suppose your type implements Equals which compares two objects just by the field "Name". Even with the fixed null reference, you wouldn't probably be satisfied with the result - for instance, NUnit will coalesce null iterators to empty arrays and decide that your object are equal because there are no elements in both.

Yes, just making all objects equal in case `GetEnumerator()` returns `null` is obviously not a useful thing. If I had to come up with a proposal, it would probably be to make `EnumerablesComparer.Equal()` return `null` if either of the `GetEnumerator()` calls returns `null`. And just let it fall through to the next thing in line.

> Meanwhile, your issue is solved very easily :-) Just specify the typed comparer to give a hint to NUnit about how you want to process comparing

Indeed, this fixes the problem and that is what I am doing for now. However the current behavior still isn't nice usability wise, I think.

**Comment by manfred-brands** [comment]
> There is no good way of knowing when to make the mock strict.

Always make a strict mock. You only mock what you think is called. If the object you passing your instance to changes and calls unmocked methods you will know straight away and can mock them appropriately.

> Strict mocks tend to increase the maintenance cost of the test suite, so I'd like to avoid creating too many of them.

Allowing automocking to return null on methods that by their definition are not supposed to return null is worse.

**Comment by stevenaw** [comment]
My (perhaps solitary) opinion is that this is "not an nunit bug". It looks like .NET itself has likely chosen to treat this as a runtime concern instead of a library concern as I don't see any null checks for this scenario in .NET class libraries themselves. For example, the genericized version of the above snippet would throw the same exception if passed to Linq's `Min()` or `Max()` functions in addition to the `foreach` construct:

```cs
var items = new MyEnumerable();

// Each of the below will throw an NRE
var mn = items.Min();
var mx = items.Max();
foreach(var item in items);

public class MyEnumerable : IEnumerable<int>
{
    public IEnumerator<int> GetEnumerator() => null;
    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => null;
}
```
From an nunit-specific perspective, I also think that it could be dangerous to have the sample equality test pass in this case when identical code would fail at runtime when used in common language constructs like `foreach` or standard library functions.

**Comment by stevenaw** [comment]
@ssrmm While I'm glad the custom comparer worked for you, one other option that I wanted to suggest for consideration or others is around the sense of "object identity". Without being able to enumerate items, something _else_ needs to be used for comparison. That would normally fall back to object references for classes or non-record structs, but your example also includes a `Name`. Could it also work for your tests to `return Name.GetEnumerator()` so to speak, to allow for using that for comparisons of object identity?

**Comment by ssrmm** [comment]
> For example, the genericized version of the above snippet would throw the same exception if passed to Linq's `Min()` or `Max()` functions in addition to the `foreach` construct:

Which in those cases is totally fine, there it is obvious that an enumeration is happening, so it is reasonable to have a failure if the enumerator does not work. It wasn't my natural expectation that NUnit would perform an enumeration on those `IEnumerables` nested in the lists. This is kind of similar to how you should know where/when an enumeration is happening so that you can avoid enumerating multiple times in cases where enumeration is much more expensive than iteration alone.

But I do understand the concern about tests silently passing when they should fail.

> That would normally fall back to object references for classes or non-record structs, but your example also includes a `Name`. Could it also work for your tests to `return Name.GetEnumerator()` so to speak, to allow for using that for comparisons of object identity?

I added the name to the example to make it easier to see things in the debugger when making the minimal example and then left it in because it seemed generally useful. It is not actually part of the type in question. What I could do instead is implement `GetEnumerator()` correctly, the information necessary for this is available on the mock. However, that wouldn't solve the problem because the actual enumeration result doesn't even relate to object equality. IMO that type shouldn't implement `IEnumerable` to begin with. But it is from a third-party framework and cannot be changed.
