### ISSUE TITLE
NUnit.Engine.NUnitEngineException : Unable to acquire remote process agent

### ISSUE THREAD

**Issue by ppathi** [nunit/nunit#4157]
I am trying to run the batch command using NUnit Console to execute the test and running into the following issue. Idea is that once this issue is resolved I can run the tests through Jenkins. Any help is greatly appreciated.

Here is the command I am using: <path to Nunit Console>\nunit3-console <path to test folder>\testfile.dll

Once the above command is executing following is the log.

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
     C:<path to test folder>\testfile.dll

Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code 1
   at NUnit.Engine.Services.TestAgency.OnAgentExit(Process process, Guid agentId)
   at NUnit.Engine.Services.TestAgency.<>c__DisplayClass13_0.<GetAgent>b__0(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

Errors, Failures and Warnings

1) Error :
NUnit.Engine.NUnitEngineException : Unable to acquire remote process agent
--NUnitEngineException
Unable to acquire remote process agent
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunnerIfNeeded()
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2022-08-19 15:22:58Z
    End time: 2022-08-19 15:22:59Z
    Duration: 0.758 seconds

Results (nunit3) saved as TestResult.xml

**Comment by stevenaw** [comment]
Thanks for filing this @ppathi I didn't see this at the time it was made but the fact you are seeing an "EngineException" makes me suspect this is in fact an issue in the console runner, which has its own repo + tracker here : https://github.com/nunit/nunit-console. This repo is primarily for the underlying framework :)

I'm unable to transfer the issue there, but some general advice I could give if you are still working on setting this up is to perhaps check that all permissions on the directories where you are running the console runner from and where the testfile.dll resides are setup for the identity that your Jenkins agent is running under.

Of course, if you are still having an issue with this, you may get the best help if you were to create an issue against the console runner repo.
