### ISSUE TITLE
Tests not being discovered for .NET 5 target [System.InvalidCastException]

### ISSUE THREAD

**Issue by sansjunk** [nunit/nunit#4168]
I have a multi-targeted test project that targets .NET Framework 4.6.2 and .NET 5. After building the project in Visual Studio 2022, the test explorer only shows tests for net462 and not for net5. 

> ========== Starting test discovery ==========
NUnit Adapter 4.2.0.0: Test discovery starting
NUnit Adapter 4.2.0.0: Test discovery complete
NUnit Adapter 4.2.0.0: Test discovery starting
Exception NUnit.Engine.NUnitEngineException, Exception thrown discovering tests in C:\Work\Workspaces\VisualStudio\dotNET_testing\Builds\net5\Debug\UnitTests.dll
The NUnit 3 driver encountered an error while executing reflected code.
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 88
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger messageLogger, ITestCaseDiscoverySink discoverySink) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestDiscoverer.cs:line 82
InnerException: System.InvalidCastException: Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)
NUnit Adapter 4.2.0.0: Test discovery complete
No test is available in C:\Work\Workspaces\VisualStudio\dotNET_testing\Builds\net5\Debug\UnitTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 248 Tests found in 5.2 sec ==========

Here are the versions of the packages being used:
- Microsoft.NET.Test.Sdk (Version 17.3.0)
- NUnit (Version 3.13.3)
- NUnit.Console (Version 3.15.2)
- NUnit3TestAdapter (Version 4.2.1)

**Comment by mikkelbu** [comment]
This sounds related to nunit/nunit3-vs-adapter#722 or nunit/nunit3-vs-adapter#973. Does it help to clean up VS temp files.

**Comment by sansjunk** [comment]
It doesn't help. I still get the same error. I increased the logging level to "Diagnostic" and captured the following log.

```[01-09-2022 2:42:55.870 PM]  Grouped C:\Work\Workspaces\VisualStudio\dotNET_testing\Builds\net5\Debug\UnitTests.dll : (AnyCPU, FrameworkCore10, net5.0, )
[01-09-2022 2:42:55.871 PM]  Test discovery settings for C:\Work\Workspaces\VisualStudio\dotNET_testing\Builds\net5\Debug\UnitTests.dll:
 <RunSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\Work\Workspaces\VisualStudio\dotNET_testing\Source\TestResults</ResultsDirectory>
    <SolutionDirectory>C:\Work\Workspaces\VisualStudio\dotNET_testing\Source\</SolutionDirectory>
    <CollectSourceInformation>False</CollectSourceInformation>
  </RunConfiguration>
</RunSettings>.
[01-09-2022 2:42:57.692 PM]  NUnit Adapter 4.2.0.0: Test discovery starting
[01-09-2022 2:42:58.177 PM] [Warning] Exception NUnit.Engine.NUnitEngineException, Exception thrown discovering tests in C:\Work\Workspaces\VisualStudio\dotNET_testing\Builds\net5\Debug\UnitTests.dll
[01-09-2022 2:42:58.179 PM] [Warning] The NUnit 3 driver encountered an error while executing reflected code.
[01-09-2022 2:42:58.182 PM] [Warning]    at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 88
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger messageLogger, ITestCaseDiscoverySink discoverySink) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestDiscoverer.cs:line 82
[01-09-2022 2:42:58.183 PM] [Warning] InnerException: System.InvalidCastException: Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)
[01-09-2022 2:42:58.189 PM]  NUnit Adapter 4.2.0.0: Test discovery complete
[01-09-2022 2:42:58.198 PM] [Warning] No test is available in C:\Work\Workspaces\VisualStudio\dotNET_testing\Builds\net5\Debug\UnitTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[01-09-2022 2:42:58.262 PM]  ========== Test discovery finished: 248 Tests found in 5.9 sec ==========

**Comment by SimonCropp** [comment]
can you share your csproj?

**Comment by sansjunk** [comment]
[UnitTests.csproj.txt](https://github.com/nunit/nunit/files/9540040/UnitTests.csproj.txt)

**Comment by SimonCropp** [comment]
can u try without the `IntermediateOutputPath` and `OutputPath`

you could also try updating Microsoft.NET.Test.Sdk

**Comment by sansjunk** [comment]
> can u try without the `IntermediateOutputPath` and `OutputPath`
> 
> you could also try updating Microsoft.NET.Test.Sdk

I updated Microsoft.NET.Test.Sdk to version 17.3.1 and then the latest preview version, both didn't help. Also removed `IntermediateOutputPath` and `OutputPath`. Still get the same exception.

**Comment by manfred-brands** [comment]
Can you drop the reference to Nunit.Console? You are now referencing two engines which might interfere.

**Comment by sansjunk** [comment]
I commented the reference to NUnit.Console and a rebuild. I am still seeing the same exception and no tests are discovered for .NET 5. With all these changes being done, there has been no issues discovering tests for .NET Framework 4.6.2.

I also tried targeting only .NET 5 (`<TargetFramework>net5</TargetFramework>`) and still see the same exception and no tests are discovered.

**Comment by OsirisTerje** [comment]
@sansjunk Are you still having this issue?

1. Update to adapter 4.3.1, does it still fail ?
2. If so, can you please create a small repro for this issue, verify that it still fails and upload that repro?

**Comment by sansjunk** [comment]
@OsirisTerje yes, still having the issue. Updating the adapter to 4.3.1 didn't help. 
I am unable to extract out a repro from the main project. While doing so, I inadvertently created a project file with a setting that does cause the same exception to be thrown. This project is attached to this comment, and I think it may provide a clue as to what could be going wrong. In this project file the `AppendTargetFrameworkToOutputPath` is `false` causing one of the target DLL to be overwritten by the other. This causes the adapter to fail. The type of exception thrown depends on which target DLL (.net462 or .net5) ends up in the output folder. Though my main project uses the same setting (`AppendTargetFrameworkToOutputPath` is `false`), the output folder is set explicitly using the following setting

    <OutputPath>..\Builds\$(TargetFramework.ToLowerInvariant())\$(Configuration)\</OutputPath>

Since the same exception is being thrown 
when I build the main project, I am guessing the adapter is picking up the wrong target DLL when trying to enumerate the tests?

[NunitRepro.zip](https://github.com/nunit/nunit/files/10110254/NunitRepro.zip)

**Comment by SimonCropp** [comment]
@sansjunk so based on your comment [NunitRepro.zip](https://github.com/nunit/nunit/files/10110254/NunitRepro.zip) is not really a valid repro. since as you point out, the output from multiple tfms is being placed in a single dir  . can you share a repro that is a valid project config and still reproduces the issue?

**Comment by sansjunk** [comment]
@SimonCropp as I mentioned in my earlier comment, I am unable to repro the issue when I extract out only the test project. Would it help if I shared the test assembly that is causing the adapter to throw the exception?

**Comment by SimonCropp** [comment]
> Would it help if I shared the test assembly that is causing the adapter to throw the exception?

only if you can supply all the assemblies it uses.

**Comment by Shotem** [comment]
Hi, I'm having a similar issue. Has there been any updates on this?

**Comment by mikkelbu** [comment]
@Shotem Short answer "No" :). Which dependencies do you have and can you provide a small repo?

**Comment by sansjunk** [comment]
Sorry, I wasn't able to get back with a repro. To get on with the project on hand, I just created two separate test projects, one for .NET Framework, and another of .NET 5, instead of multi-targeting.

**Comment by OsirisTerje** [comment]
@sansjunk @Shotem The problem here is the organization of the folders.   The repro project above works if the following is done:
- Ensure you have the correct folder structure, that is, the binaries for the different frameworks must be in separate folders.  So, in the csproj file, these two lines should either be deleted or set to true.
```
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
```
Also set the configuration platform (for the solution) to Any CPU, not Mixed.  The Mixed sets the output to the same folder again. 
A good read for the attributes above is  [this blogpost](https://www.red-gate.com/simple-talk/blogs/careful-net-core-folder-structure/)

If you for some reason need multiple solution platforms, ENSURE you still have separate folders per target framework.

@mikkelbu @SimonCropp I think this issue can be closed.  There is no bug in NUnit nor the adapter here.

**Comment by stevenaw** [comment]
Thanks for digging into this @OsirisTerje
