### ISSUE TITLE
Add .NET7 as a build target for the test suite 

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4170]
.NET7 will be coming out in ~2 months. Once CI supports it, it would be good to add it as a test target to ensure the framework runs as expected on that runtime.

**Comment by KonH** [comment]
I started to dig into this issue, current results in the draft PR above:
- .NET SDK 7.0 RC is used, and should be changed when a stable version is released
- Build is finished successfully
- Found one test which fails on "TestNetFramework on net7.0" but not on "TestNetFramework on net6.0" - https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Assertions/WarningTests.cs#L226
No changes made on the CI side yet, will do it later

**Comment by KonH** [comment]
Considering CI:
- GitHub action now could run but require approval 
- AppVeyor doesn't have VS 2022 preview support - https://www.appveyor.com/docs/windows-images-software/#visual-studio-2022, build fails
- Azure Pipelines - build fails because of new fail test described above

**Comment by KonH** [comment]
Considering test (https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Assertions/WarningTests.cs#L226) failure:
I found that stacktraces are different like this: 
.NET 6.0:
```
at NUnit.TestData.WarningFixture.<>c__DisplayClass95_0.<WarningInThreadPoolQueueUserWorkItem>b__0(Object _) in F:\KonH\Work\Git\nunit\src\NUnitFramework\testdata\WarningFixture.cs:line 665
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
```
.NET 7.0:
```
   at NUnit.TestData.WarningFixture.<>c__DisplayClass95_0.<WarningInThreadPoolQueueUserWorkItem>b__0(Object _) in F:\KonH\Work\Git\nunit\src\NUnitFramework\testdata\WarningFixture.cs:line 665
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
Will investigate it later.

**Comment by KonH** [comment]
Potentially it is related to https://github.com/dotnet/runtime/pull/71719
Now I just use additional define to cover that case
I also found second .NET 7 failing test case - https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite.tests/TextUIReportTests.cs#L111
It looks like a flaky one now

**Comment by KonH** [comment]
Considering https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite.tests/TextUIReportTests.cs#L111 test:
.NET 6:
```
0: Errors, Failures and Warnings
1:
2: 1) Invalid : NUnit.Tests.Assemblies.MockTestFixture.NonPublicTest
3: Method is not public
4:
5: 2) Failed : NUnit.Tests.Assemblies.MockTestFixture.FailingTest
6: Intentional failure
7: at NUnit.Tests.Assemblies.MockTestFixture.FailingTest() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 126
8:
9: 3) Warning : NUnit.Tests.Assemblies.MockTestFixture.WarningTest
10: Warning Message                                                                                                                                                                                                            11: at NUnit.Tests.Assemblies.MockTestFixture.WarningTest() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 132
12:
13: 4) Invalid : NUnit.Tests.Assemblies.MockTestFixture.NotRunnableTest
14: No arguments were provided
15:
16: 5) Error : NUnit.Tests.Assemblies.MockTestFixture.TestWithException
17: System.Exception : Intentional Exception
18: at NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 178
19: at NUnit.Tests.Assemblies.MockTestFixture.TestWithException() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 173
20:
```

.NET 7.0 run 1:
```
0: Errors, Failures and Warnings
1:
2: 1) Invalid : NUnit.Tests.Assemblies.MockTestFixture.NonPublicTest
3: Method is not public
4:
5: 2) Failed : NUnit.Tests.Assemblies.MockTestFixture.FailingTest
6: Intentional failure
7: at NUnit.Tests.Assemblies.MockTestFixture.FailingTest() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 126
8: at InvokeStub_MockTestFixture.FailingTest(Object, Object, IntPtr*) <= new line
9:
10: 3) Warning : NUnit.Tests.Assemblies.MockTestFixture.WarningTest
11: Warning Message
12: at NUnit.Tests.Assemblies.MockTestFixture.WarningTest() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 132
13: at InvokeStub_MockTestFixture.WarningTest(Object, Object, IntPtr*) <= new line
14:
15: 4) Invalid : NUnit.Tests.Assemblies.MockTestFixture.NotRunnableTest
16: No arguments were provided
17:
18: 5) Error : NUnit.Tests.Assemblies.MockTestFixture.TestWithException
19: System.Exception : Intentional Exception
20: at NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 178
21: at NUnit.Tests.Assemblies.MockTestFixture.TestWithException() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 173
22: at InvokeStub_MockTestFixture.TestWithException(Object, Object, IntPtr*) <= new line
23: at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) <= new line
24:
```
.NET 7.0 run 2:
```
0: Errors, Failures and Warnings
1:
2: 1) Invalid : NUnit.Tests.Assemblies.MockTestFixture.NonPublicTest
3: Method is not public
4:
5: 2) Failed : NUnit.Tests.Assemblies.MockTestFixture.FailingTest
6: Intentional failure                                                                                                                                                                                                                    7: at NUnit.Tests.Assemblies.MockTestFixture.FailingTest() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 126
8: <= no new line compare to previous run (!)
9: 3) Warning : NUnit.Tests.Assemblies.MockTestFixture.WarningTest
10: Warning Message
11: at NUnit.Tests.Assemblies.MockTestFixture.WarningTest() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 132
12: at InvokeStub_MockTestFixture.WarningTest(Object, Object, IntPtr*) <= new line
13:
14: 4) Invalid : NUnit.Tests.Assemblies.MockTestFixture.NotRunnableTest
15: No arguments were provided
16:
17: 5) Error : NUnit.Tests.Assemblies.MockTestFixture.TestWithException
18: System.Exception : Intentional Exception
19: at NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 178
20: at NUnit.Tests.Assemblies.MockTestFixture.TestWithException() in F:\KonH\Work\Git\nunit\src\NUnitFramework\mock-assembly\MockAssembly.cs:line 173
21: at InvokeStub_MockTestFixture.TestWithException(Object, Object, IntPtr*) <= new line
22: at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) <= new line
23:
```

It looks pretty strange now

**Comment by KonH** [comment]
I've added a simple workaround, and now 2/3 platforms passed the test suite successfully

**Comment by KonH** [comment]
Now all platforms passed the test suite

**Comment by moh-hassan** [comment]
.Net 7 is released today  and nunit is working fine. It's tested using  NUnit3TestAdapter [v4.3.0](https://www.nuget.org/packages/NUnit3TestAdapter/4.3.0)

**Comment by KonH** [comment]
@stevenaw now PR is ready

**Comment by stevenaw** [comment]
Thanks for the prompt updates @KonH 
The week's been busy but I should be able to take a look this weekend.
