### ISSUE TITLE
The RPC server is unavailable

### ISSUE THREAD

**Issue by imakowski** [nunit/nunit#4173]
I have following error when I execute Nunit console 3.15.2 in windows docker container:
1) Error : 
```
 [exec] NUnit.Engine.NUnitEngineException : The NUnit 3 driver encountered an error while executing reflected code.
                 [exec]   ----> System.InvalidOperationException : The RPC server is unavailable.
                 [exec] --NUnitEngineException
                 [exec] The NUnit 3 driver encountered an error while executing reflected code.
                 [exec] 
                 [exec] Server stack trace: 
                 [exec]    at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
                 [exec]    at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
                 [exec]    at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
                 [exec]    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
                 [exec]    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
                 [exec] 
                 [exec] Exception rethrown at [0]: 
                 [exec]    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
                 [exec]    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
                 [exec]    at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
                 [exec]    at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
                 [exec] --
                 [exec] InvalidOperationException
                 [exec] The RPC server is unavailable.
                 [exec] 
                 [exec]    at System.Environment.get_UserDomainName()
                 [exec]    at NUnit.Framework.Api.FrameworkController.InsertEnvironmentElement(TNode targetNode)
                 [exec]    at NUnit.Framework.Api.FrameworkController.RunTests(ICallbackEventHandler handler, String filter)
                 [exec] 
                 [exec] Test Run Summary
                 [exec]   Overall result: Failed
                 [exec]   Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
                 [exec]   Start time: 2022-08-22 09:48:52Z
                 [exec]     End time: 2022-08-22 09:48:53Z
                 [exec]     Duration: 1.375 seconds
                 [exec] 
```

Command line:
`nunit3-console.exe TestDll.dll" --labels Before --result:"NUnitResults.xml" --where "cat != Database and cat != PUU and cat != Manual and cat != Windows"' in 'C:\src'`

**Comment by rprouse** [comment]
We haven't heard back, so closing. Please comment if you want this re-opened.
