### ISSUE TITLE
 Nunit Test cases from Azure Devops pipeline : Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code 255

### ISSUE THREAD

**Issue by jainnids** [nunit/nunit#4270]
Hi! Im having issue with an unhandled Exception when running tests in TFS Azure Devops pipeline. I should mention that SOMETIMES it works and a test results is published after all tests have been run but most of the time this undhandled exception is thrown and the whole process crashes/closes in the middle of executing the test cases. Any ideas what might cause this?
Here is the whole unhandled exception:
2022-04-20T11:02:16.2968300Z Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code 255
2022-04-20T11:02:16.2969355Z   at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e)
2022-04-20T11:02:16.2971802Z   at System.Diagnostics.Process.OnExited()
2022-04-20T11:02:16.2972479Z   at System.Diagnostics.Process.RaiseOnExited()
2022-04-20T11:02:16.2973291Z   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2022-04-20T11:02:16.2974340Z   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2022-04-20T11:02:16.2975277Z   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
2022-04-20T11:02:18.3016055Z
2022-04-20T11:02:18.3019505Z Errors, Failures and Warnings
2022-04-20T11:02:18.3019751Z
2022-04-20T11:02:18.3097188Z 1) Error :
2022-04-20T11:02:18.3097804Z [System.Net](http://system.net/).Sockets.SocketException : An existing connection was forcibly closed by the remote host
2022-04-20T11:02:18.3098418Z --SocketException
2022-04-20T11:02:18.3098842Z An existing connection was forcibly closed by the remote host
2022-04-20T11:02:18.3099102Z
2022-04-20T11:02:18.3099439Z Server stack trace:
2022-04-20T11:02:18.3099971Z   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
2022-04-20T11:02:18.3100663Z   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
2022-04-20T11:02:18.3101380Z   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
2022-04-20T11:02:18.3102033Z   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
2022-04-20T11:02:18.3102665Z   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
2022-04-20T11:02:18.3103305Z   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
2022-04-20T11:02:18.3103980Z    at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
2022-04-20T11:02:18.3105312Z   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
2022-04-20T11:02:18.3107279Z   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
2022-04-20T11:02:18.3107667Z
2022-04-20T11:02:18.3108095Z Exception rethrown at [0]:
2022-04-20T11:02:18.3108673Z   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
2022-04-20T11:02:18.3109393Z   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
2022-04-20T11:02:18.3110024Z   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
2022-04-20T11:02:18.3110673Z   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
2022-04-20T11:02:18.3111059Z
2022-04-20T11:02:18.3137012Z Test Run Summary
2022-04-20T11:02:18.3138047Z  Overall result: Failed
2022-04-20T11:02:18.3148579Z  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
2022-04-20T11:02:18.3152535Z  Start time: 2022-04-20 11:02:03Z
2022-04-20T11:02:18.3153115Z    End time: 2022-04-20 11:02:16Z
2022-04-20T11:02:18.3154289Z    Duration: 13.150 seconds
2022-04-20T11:02:18.3155121Z
2022-04-20T11:02:18.3292687Z Results (nunit3) saved as C:\vstsagent\A1\_work\r4\a\TestResult.xml
2022-04-20T11:02:18.3293487Z
2022-04-20T11:02:18.3294158Z NUnit.Engine.NUnitEngineUnloadException : Agent Process was terminated successfully after error.
2022-04-20T11:02:18.3295067Z  ----> [System.Net](http://system.net/).Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:60462
2022-04-20T11:02:18.3677154Z ##[error]Process completed with exit code -100.
2022-04-20T11:02:18.3688216Z ##[section]Finishing: Test case execution

**Comment by stevenaw** [comment]
Thanks for filing this @jainnids 
I suspect this may in fact be an issue "higher up" than in the framework. Can you confirm how you are running the tests (`nunitconsole.exe`, `dotnet test`, or something else)? It would also help to understand the versions of the framework is used, as well as the version of the console runner if relevant. Knowing the runtimes targeted by the tests would be helpful too to understand if any differences between .NET Framework and .NET Core/6/etc could factor in

**Comment by rprouse** [comment]
We haven't heard back, so closing. Please comment if you want this re-opened.
