### ISSUE TITLE
AssemblyHelper throws Exception when loading dynamically compiled Assemblies

### ISSUE THREAD

**Issue by rachied** [nunit/nunit#4320]
I am working on a mutation testing playground in which you can (among other things) execute NUnit tests straight from the browser by leveraging WebAssembly, Roslyn and NUnitLite.

I'm using Roslyn to parse user submitted code (containing at least one TestFixture) and create an assembly out of that.
NUnitLite's TextRunner fails to test the resulting assembly, throwing a NullReferenceException. 
See below stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.AssemblyHelper.IsFileUri(String uri)
   at NUnit.Framework.Internal.AssemblyHelper.GetAssemblyPath(Assembly assembly)
   at NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(Assembly assembly, IDictionary`2 options)
   at NUnit.Framework.Api.NUnitTestAssemblyRunner.<>c__DisplayClass34_0.<Load>b__0()
```

This is because `Assembly.Codebase` returns null in my case but it is used in `AssemblyHelper.IsFileUri` without checking for null.
Furthermore, this property is [marked as obsolete](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.codebase?view=net-7.0)

**Comment by mr-russ** [comment]
Thanks @rachied, do you have some minimal reproduction steps that we could use to show the problem without having to replicate your entire environment?

**Comment by OsirisTerje** [comment]
@rachied Does it work as it should when you modify the AssemblyHelper.GetAssemblyPath to use Assembly.Location instead?  

I don't think this is very common, but using an obsolete property (good find! ) is not good, so if that is changed, and also if that fixes your issue, it would be good.

**Comment by rachied** [comment]
@OsirisTerje Assembly.Location returns an empty string in my scenario. This means it does not fail with a NullReferenceException, but down the line when it tries to determine a name for the test suite, it rejects empty strings (rightfully). I was not sure how else to determine a name so like I mentioned, I hardcoded a fallback name.

With those changes, NUnitLite is working great in the browser. Try it out yourself :)
https://rachied.github.io/stryker-playground/

**Comment by OsirisTerje** [comment]
@mr-russ Do you think you have some time to look into this?

**Comment by stevenaw** [comment]
This appears to have been fixed within v4.5 as part of https://github.com/nunit/nunit/pull/5024
I'm assigning to myself to write a test or two for coverage

**Comment by stevenaw** [comment]
I'm putting this into 5.1.
I have found a few edge cases which will require a small code change.

It is possible under different circumstances for `Location` to be: 
- Empty string 
- Throw `NotSupportedException`

It's also possible for `Codebase` to throw `NotSupportedException`.
