### ISSUE TITLE
Assert.Multiple doesn't provide stacktrace for found failures

### ISSUE THREAD

**Issue by jochenwezel** [nunit/nunit#4406]
## Current results
The current output for my test in Visual Studio is as following and is missing the stacktrace line for the indiviual failed assertion:
![image](https://github.com/nunit/nunit/assets/3033827/79dad81e-dc9a-4282-941f-5fd7183d35a0)

The same output is shown at `dotnet test`, except that stack trace lines are not clickable

## Requested results
Each asserition should 
1. show the missing stacktrace (at positions A in screenshot) from the initial stack of the multiple (show in screenshot at position B) to the individual assertion line, something like following   
```text
    HHErgebnisrechnungenBpVsAwpTest.ValidateBunch1() Zeile 304
    HHErgebnisrechnungenBpVsAwpTest.AssertEqualErgebnis.<Multi>b__1_1() Zeile 103
```
2. in Visual Studio window, the stacktrace at positions A should be clickable (as at position B)
![image](https://github.com/nunit/nunit/assets/3033827/6f0f10cc-81dc-4fab-af53-e6b9d3a82710)

## Current code snippets
Assert.Multiple is called as following:
```vb
Public Sub ErgebnisrechnungAWPvsBP(id_planjahr as Int64, id_bereich as Int64) ()
    Assert.Multiple(Sub()
                   ValidateBunch1()
                   ValidateBunch2()
              End Sub)
End Sub

Private Sub ValidateBunch1()
                    '...
                    Assert.AreEqual(Me.SummenTableBP(SumName, "rIstTMinus1"), System.Math.Round(Me.SummenTableAWP(SumName, "IstTMinus1"), 0), "BP vs AWP: " & SumName & " >> IstTMinus1")
                    Assert.AreEqual(Me.SummenTableBP(SumName, "rPlanT"), System.Math.Round(Me.SummenTableAWP(SumName, "PlanT"), 0), "BP vs AWP: " & SumName & " >> PlanT")
                    Assert.AreEqual(Me.SummenTableBP(SumName, "rHrT"), System.Math.Round(Me.SummenTableAWP(SumName, 
                    '...
End Sub

Private Sub ValidateBunch2()
                    '...
                    Assert.AreEqual(1, 2)
                    '...
End Sub

```

PackageReferences are as following:
```xml
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
```

**Comment by stevenaw** [comment]
Thanks for reporting this @jochenwezel 
I haven't had the chance to dig into this myself yet but there may be two separate issues here.

For your first point, I'm reminded on #4242 . Do you feel like that one captures what you're looking for?

For your second point, I suspect that it may actually be an adapter issue.

**Comment by stevenaw** [comment]
Also, thank you for the clean repro and package version info. Can you also please confirm which version of Visual Studio you're using?

**Comment by jochenwezel** [comment]
> For your first point, I'm reminded of #4242 . Do you feel like that one captures what you're looking for?
The ticket of #4242 describes an issue, that stack trace information is available for the multiple assertions, but with wrong line numbers.
In this tickete here, there is no stacktrace at all.

> Can you also please confirm which version of Visual Studio you're using?
Microsoft Visual Studio Community 2022 (64-Bit), v17.6 

Please note for point 2 of my request: the stacktrace line numbers are clickable usually. My intention to write down point 2 is just for presenting a complete "feature request description" ;-) Maybe the code for point 2 is already there and active as soon as the stacktrace (re-)appears in point 1.

**Comment by OsirisTerje** [comment]
The stacktrace is there, but there is something wrong either in the adapter code or in the way that the Test Explorer interprets the stacktrace.  
I have added a repro here:  https://github.com/nunit/nunit.issues/tree/main/Issue4406
and the dump file contains the following block:
```xml
<assertion result='Failed'>
         <message><![CDATA[  Expected: 4
  But was:  42
]]></message>
         <stack-trace><![CDATA[   at Issue4406.Tests.<>c__DisplayClass2_0.<Test1>b__0() in C:\repos\nunit\nunit.issues\Issue4406\UnitTest1.cs:line 29
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Issue4406.Tests.Test1() in C:\repos\nunit\nunit.issues\Issue4406\UnitTest1.cs:line 24
]]></stack-trace>
      </assertion>
```
This comes for each assert that fails.  
But it also outputs a stack trace in the failure section, 
```xml
<failure>
      <message><![CDATA[Multiple failures or warnings in test:
  1)   Expected: 2
  But was:  42

  2)   Expected: 3
  But was:  42

  3)   Expected: 4
  But was:  42

  4)   Expected: 55
  But was:  5

]]></message>
      <stack-trace><![CDATA[   at Issue4406.Tests.Test1() in C:\repos\nunit\nunit.issues\Issue4406\UnitTest1.cs:line 24
]]></stack-trace>
   </failure>
```
It can be that this is what is being sent to the Test Explorer.

So this looks like an adapter bug, and I'll move it there.
