### ISSUE TITLE
Testfixture is silently ignored if exception in constructor and DatapointSource

### ISSUE THREAD

**Issue by gboucher90** [nunit/nunit#4426]
Hi,

It seems test can be silently ignored without any warning or errors if the test fixture constructor throws and there are some usage of non-static DatapointSource.

Here is the repro:
```
namespace TestProject1
{
    [TestFixture]
    public class Tests
    {
        public Tests()
        {
            throw new Exception("Thrown in constructor");
        }

        [DatapointSource]
        private int[] intSource = new int[] { 0, 1, 6, 8, 50 };

        [Test, Theory]
        public async Task Test1(int intVal)
        {
            await Task.Delay(intVal);
            Assert.Pass();
        }
    }
}
```
<img width="343" alt="image" src="https://github.com/nunit/nunit/assets/20612880/4971b390-a1a7-40c7-960c-521c5105acbe">

No test is discovered and there is no error.

Now if we do the same code but with a static datapoint source for example then it does throw and fail:
```
namespace TestProject1
{
    [TestFixture]
    public class Tests
    {
        public Tests()
        {
            throw new Exception("Thrown in constructor");
        }

        [DatapointSource]
        private static int[] intSource = new int[] { 0, 1, 6, 8, 50 };

        [Test, Theory]
        public async Task Test1(int intVal)
        {
            await Task.Delay(intVal);
            Assert.Pass();
        }
    }
}
```
<img width="852" alt="image" src="https://github.com/nunit/nunit/assets/20612880/c282c879-efaf-4dab-ab16-99a97e16189d">

This can lead to test suites being silently ignored in CIs for example and it is not obvious to detect..

**Comment by OsirisTerje** [comment]
Interesting!  
Can you collect the code above into a small repro project and upload it ?

**Comment by gboucher90** [comment]
Hey, 
Sure no problem :)

Here you go:
[TestProject1.zip](https://github.com/nunit/nunit/files/12134126/TestProject1.zip)

**Comment by gboucher90** [comment]
Actually NUnit3TestExecutor does log a warning (strangely I couldn't spot this in my production project and took me hours to debug 😓 )
The failure doesn't show up in the skipped or failed run report though.
``` 
[21/07/2023 9:35:02.708 PM]  NUnit Adapter 4.4.0.0: Test execution started
[21/07/2023 9:35:02.745 PM]  Running selected tests in C:\Users\guill\source\repos\TestProject1\bin\Debug\net7.0\TestProject1.dll
[21/07/2023 9:35:02.927 PM]     NUnit3TestExecutor discovered 6 of 6 NUnit test cases using Current Discovery mode, Non-Explicit run
[21/07/2023 9:35:03.025 PM] [Warning] Setup failed for test fixture TestProject1.TestsWorkingWithStaticDatapointSource
[21/07/2023 9:35:03.027 PM] [Warning] System.Exception : Thrown in constructor
StackTrace:    at TestProject1.TestsWorkingWithStaticDatapointSource..ctor() in C:\Users\guill\source\repos\TestProject1\TestsWorkingWithStaticDatapointSource.cs:line 8
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[21/07/2023 9:35:03.033 PM]  NUnit Adapter 4.4.0.0: Test execution complete
[21/07/2023 9:35:03.374 PM]  Attachments processing not needed
[21/07/2023 9:35:03.406 PM]  ========== Test run finished: 6 Tests (0 Passed, 6 Failed, 0 Skipped) run in 357 ms ==========
[21/07/2023 9:35:03.411 PM]  Update Test run progress to 85/100.
[21/07/2023 9:35:03.411 PM]  Update Test run progress to 100/100.
[21/07/2023 9:35:03.876 PM]  Test run animation has stopped.
[21/07/2023 9:35:04.125 PM]  Test run progress has stopped.
```

**Comment by gboucher90** [comment]
The error seems to print in the `Non-Explicit run` mode when I attempt to run test for the whole projects. If I filter on specific tests then nothing appears. Probably why we would detect in our CI (we filter on some category) or manually during phase as I was trying to run those tests explicitly.

**Comment by OsirisTerje** [comment]
Yes, there are some issues around how to output information from faults in the OneTimeSetup/constructor, since they don't belong to a test.

**Comment by OsirisTerje** [comment]
It seems the crashing constructor in the Non-Discovered case blocks further processing, but there should be some reporting.  I added a dump, and there is nothing coming back.  
If I move the initialization to a OneTimeSetup method (which should be the same as constructor, but ofc is not), then it works. 
So there must be bug somewhere here.

**Comment by manfred-brands** [comment]
@OsirisTerje The `CombiningStratehyAttribute.BuildFrom` calls into `_dataProvider.GetDataFor` but doesn't catch all exceptions.
It catches `InvalidDataSourceException` but that is only thrown by `ValueSourceAttribute`.
Other places catch all exceptions instead of only one.
Any other exception thrown is not caught here is caught in `DefaultTestCaseBuilder.BuildFrom` which marks the `TestMethod` as Invalid. 

P.S. None of the other attributes allow instance methods.

**Comment by stevenaw** [comment]
There's a bit of a discussion here about which forms of which attributes have static or instance forms: https://github.com/nunit/nunit/issues/3537

Charlie mentions there that there is a form of `TestCaseSource` and `TestFixtureSource` which could be tied to an instance method. I'll try and dig into this later tonight to see if it affects them too.
- https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html#form-3---testcasesourcetype-sourcetype
- https://docs.nunit.org/articles/nunit/writing-tests/attributes/testfixturesource.html#form-3---testfixturesourcetype-sourcetype

**Comment by stevenaw** [comment]
Oops, now that I caught up I see we've already discovered that this is a general reporting issue when there's an exception in the constructor, regardless of cause

**Comment by OsirisTerje** [comment]
Fixed in version 4.0.0
