### ISSUE TITLE
Rare registry configurations may cause NUnit to fail

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#454]
Having recently upgraded my NUnit version on one of my old machines I got

```
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment -
   OS Version: Microsoft Windows NT 6.0.6002 Service Pack 2
  CLR Version: 2.0.50727.4253 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
Unhandled Exception:
System.ArgumentException: Version string portion was too short or too long.
   at System.Version..ctor(String version)
   at NUnit.Core.RuntimeFramework.AppendDotNetFrameworks(FrameworkCollection frameworks)
   at NUnit.Core.RuntimeFramework.get_AvailableFrameworks()
   at NUnit.Core.RuntimeFramework.get_IsAvailable()
   at NUnit.Util.RuntimeFrameworkSelector.SelectRuntimeFramework(TestPackage package)
   at NUnit.Util.DefaultTestRunnerFactory.GetTargetProcessModel(TestPackage package)
   at NUnit.Util.DefaultTestRunnerFactory.MakeTestRunner(TestPackage package)
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

Looking through the code and then at the registry, I found that I still had the .net 4 Beta 2 Windows Update Opt-in Key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4B2WU` (see http://www.hanselman.com/blog/FavorHelpUsTestNET4Beta2OnWindowsUpdateWU.aspx).

While this particular case may affect about one other person who forgot to delete this key, it suggests that there may in future be other legitimate instances where keys beginning v may not be followed by a version number; and such keys should be skipped (possibly with a warning logged).

**Comment by CharliePoole** [comment]
I copied this issue from nunit/nunit-console, where it was originally filed by @SteveGilham.

**Comment by CharliePoole** [comment]
We should fix this in 3.0 and also go through the code that accesses the registry and identify any other points where we are making assumptions about the registry content. That entire area of code should be written more defensively.

**Comment by kevingoos** [comment]
I had the same issue in version 3.6.0 when using teamcity.

```
Starting: D:\Ntapps\TeamCity\BuildAgent2\work\5abc171d155702d0\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe D:\Ntapps\TeamCity\BuildAgent2\temp\buildTmp\dppSJMLyACKKGB7l1dAWbvFo9bLR6TcR.nunit --result=D:\Ntapps\TeamCity\BuildAgent2\temp\buildTmp\dppSJMLyACKKGB7l1dAWbvFo9bLR6TcR.nunit.xml --noheader
in directory: D:\Ntapps\TeamCity\BuildAgent2\work\5abc171d155702d0\AMDV\AMDV.App.IntegrationTests\bin\Debug
Runtime Environment
OS Version: Microsoft Windows NT 6.3.9600.0
CLR Version: 4.0.30319.42000

Test Files
D:\Ntapps\TeamCity\BuildAgent2\temp\buildTmp\dppSJMLyACKKGB7l1dAWbvFo9bLR6TcR.nunit

System.ArgumentException: Version string portion was too short or too long.
    at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
    at System.Version.TryParseVersion(String version, VersionResult& result)
    at System.Version.Parse(String input)
    at System.Version..ctor(String version)
    at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
    at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
    at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
    at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(TestPackage package)
    at NUnit.Engine.Runners.MasterTestRunner.InitializePackage()
    at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
    at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
    at NUnit.ConsoleRunner.Program.Main(String[] args)
Process exited with code -100
Publishing artifacts
Process exited with code -100
Step NUnit failed
```

[Link to stackoverflow question.](https://stackoverflow.com/questions/46600567/teamcity-nunit-version-string-portion-was-too-short-or-too-long)

**Comment by rprouse** [comment]
@kevingoos please open a new issue for your problems. They may be related to the original issue, but it has been closed so long that I would prefer to start a new issue with your specific problem. Thanks.
