### ISSUE TITLE
Parameter count mismatch with indexer

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [nunit/nunit#4591]
Hi there,
for code as simple as this I get an error. (see the stacktrace)

```csharp
[Test]
public void Test_Accessor()
{
  var a = new X();
  var b = new X();

  Assert.That( a, Is.Not.EqualTo( b ) );
}
		
public class X
{
  private readonly Guid _ID = Guid.NewGuid();

  public Guid? this[ Guid characteristicUuid ] => _ID;
}
```

*Stack trace*
```
System.Reflection.TargetParameterCountException : Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at NUnit.Framework.Constraints.Comparers.PropertiesComparer.Equal(Object x, Object y, Tolerance& tolerance, ComparisonState state, NUnitEqualityComparer equalityComparer)
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance, ComparisonState state)
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance)
   at NUnit.Framework.Constraints.EqualConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Constraints.NotConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, NUnitString message, String actualExpression, String constraintExpression)
   at My.TestClass.Test_Accessor() in C:\TestClass.cs:line 007
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Is this a bug?

Best regards.

**Comment by manfred-brands** [comment]
Yes it is.
Related to #4572

**Comment by georg-eckert-zeiss** [comment]
Didn't find that one. Thanks. I stumbled upon it using `Is.EquivalentTo` and was able to narrow it down to this example.

**Comment by georg-eckert-zeiss** [comment]
Great. Looking forward to the patch release.

**Comment by OsirisTerje** [comment]
@georg-eckert-zeiss Can you please check this package https://www.myget.org/feed/nunit/package/nuget/NUnit/4.1.0-alpha.0.1
