### ISSUE TITLE
nunit3-console doesn't see nugets from Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by Harmyder** [nunit/nunit#4654]
I have the following project and test

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
</Project>
```

``` csharp
[Test]
public void Test1()
{
    Assembly.Load("Microsoft.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60");
}
```

I can run fine this project from Visual Studio but then I run it from command line with `nunit3-console nunittests.dll` I see the following error

> System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
>    at System.Reflection.Assembly.Load(String assemblyString)
>    at NUnitTests.Tests.Test1() in D:\Yola\Test22\NUnitTests\UnitTest1.cs:line 16
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

If I use `Assembly.LoadFrom` with the full path it is able to load the DLL.

**Comment by OsirisTerje** [comment]
Hi!  

We do have issues with this kind of loading behavior, and we do have multiple attempts at finding the reason.
I made small repro solution, I got a different error from what you have, but I believe it might be about the same bug.  The repro is here:  https://github.com/nunit/nunit.issues/tree/main/Issue4654   . Feel free to change it. 

I do get this error:
![image](https://github.com/nunit/nunit/assets/203432/da75ec8a-0044-4f6f-81dc-bfce37a3bb1e)

We do have multiple similar errors in the console repo, see https://github.com/nunit/nunit-console/issues

I'll move this issue over to that repo.  

You can have a look at https://github.com/nunit/nunit-console/issues/1383  which is a similar reported issue.  

See this comment:  

> The reason is that the nunit-agent only references the Microsoft.NETCore.App runtime in its runtimeconfig.json. Therefore a workaround is to manually add the missing runtimes (Microsoft.WindowsDesktop.App and/or Microsoft.AspNetCore.App) to the runtimeconfig.json.

If you use the latest test.sdk, you should also get the runtimeconfig.json correct, and then you should get the same error as I have above.  See the repro for details.

The failure with loading Microsoft.Extensions.Logging.Abstractions is a bit weird.  It is a framework reference, and you see it in the dependencies list in Visual Studio, but the console runner doesn't find it.

We have to dig a bit deeper to see what this can be.
