### ISSUE TITLE
Regression Bug: Multidimensional arrays not handled as of NUnit 3.13.0

### ISSUE THREAD

**Issue by SpocWeb** [nunit/nunit#4775]
Hi when upgrading from NUnit 3.12.0 to 3.13.0 the following issue arises; 
It also fails with all higher Versions of NUnit 3. 
In NUnit 3.12.0 the tests succeed. 

You can reproduce it by checking out this Branch: 
https://github.com/SpocWiki/QuikGraph/tree/bugfix/nunit-3.13-CollectionAssert 

Switch to the Folder `QuikGraph\tests\QuikGraph.Tests` and execute 
`dotnet test --filter SimpleAssignmentIterations`

 Failed SimpleAssignmentIterations [2 ms]
  Error Message:
   System.ArgumentException : Array was not a one-dimensional array.
  Stack Trace:
     at System.Array.GetValue(Int32 index)
   at System.Array.System.Collections.IStructuralEquatable.Equals(Object other, IEqualityComparer comparer)
   at NUnit.Framework.Constraints.Comparers.StructuralComparer.Equal(Object x, Object y, Tolerance& tolerance, ComparisonState state) in D:\a\1\s\src\NUnitFramework\framework\Constraints\Comparers\StructuralComparer.cs:line 54
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance, ComparisonState state) in D:\a\1\s\src\NUnitFramework\framework\Constraints\NUnitEqualityComparer.cs:line 195
   at NUnit.Framework.Constraints.Comparers.EnumerablesComparer.Equal(Object x, Object y, Tolerance& tolerance, ComparisonState state) in D:\a\1\s\src\NUnitFramework\framework\Constraints\Comparers\EnumerablesComparer.cs:line 60
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance, ComparisonState state) in D:\a\1\s\src\NUnitFramework\framework\Constraints\NUnitEqualityComparer.cs:line 195
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance, Boolean topLevelComparison) in D:\a\1\s\src\NUnitFramework\framework\Constraints\NUnitEqualityComparer.cs:line 170
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance) in D:\a\1\s\src\NUnitFramework\framework\Constraints\NUnitEqualityComparer.cs:line 162
   at NUnit.Framework.Constraints.EqualConstraint.ApplyTo[TActual](TActual actual) in D:\a\1\s\src\NUnitFramework\framework\Constraints\EqualConstraint.cs:line 392
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args) in D:\a\1\s\src\NUnitFramework\framework\Assert.That.cs:line 227
   at NUnit.Framework.CollectionAssert.AreEqual(IEnumerable expected, IEnumerable actual, String message, Object[] args) in D:\a\1\s\src\NUnitFramework\framework\CollectionAssert.cs:line 174
   at NUnit.Framework.CollectionAssert.AreEqual(IEnumerable expected, IEnumerable actual) in D:\a\1\s\src\NUnitFramework\framework\CollectionAssert.cs:line 148
   at QuikGraph.Tests.Algorithms.Assignment.HungarianAlgorithmTests.SimpleAssignmentIterations() in D:\QuikGraph\tests\QuikGraph.Tests\Algorithms\Assigment\HungarianAlgorithmTests.cs:line 125

**Comment by stevenaw** [comment]
Thanks for the report @SpocWeb 
I'm not at a computer to immediately verify, but this may actually be a BCL bug: https://github.com/dotnet/runtime/issues/66472

We could, of course, work around it in NUnit, however it's likely any fix here would stream into an NUnit 4 release. 

I'm going to label this `confirm` for now so that I can look into it in the coming days when I return.

**Comment by stevenaw** [comment]
I can confirm this also happens on latest NUnit (4.1.0 as of this time) on both net472 + net8.0

I've pushed a repro here: https://github.com/nunit/nunit.issues/tree/main/Issue4775


@SpocWeb The workaround for you is quite simple :)

The `CollectionAssert.AreEqual()` method you're calling internally will delegate to our constraint model and append the `AsCollection` comparison modifier (https://github.com/nunit/nunit/blob/v3/src/NUnitFramework/framework/CollectionAssert.cs#L174). Your repro should pass if you switch to using either `Assert.AreEqual(y, x)` or `Assert.That(x, Is.EqualTo(y))` without that modifier, causing them to be compared as arrays rather than collections.

**Comment by stevenaw** [comment]
@nunit/framework-team Having dug into this I am in favor of closing this without fixing as the source of the bug is external, the workarounds are simple, and one would have to go out of their way to encounter this using the constraint model by explicitly applying `AsCollection`. There is also a workaround using the classic asserts too.

Thoughts or objections?

**Comment by manfred-brands** [comment]
@stevenaw I agree.

**Comment by OsirisTerje** [comment]
@stevenaw I agree

**Comment by stevenaw** [comment]
Happy to hear and glad to have helped @SpocWeb
