### ISSUE TITLE
Nunit console doesnt find selenium-manager.exe , works fine from visual studio

### ISSUE THREAD

**Issue by saiparth** [nunit/nunit#4834]
I downloaded nunit3-console.exe zip file and running from my local machine. Problem is seems nunit-console sets some path for execution and wont find already downloaded selenium-manager.
steps
Create nunit project in .net8 or .netcore3.1
add selenium dependency and add basic step to lunch browser like `var driver=new ChromeDriver();`
Run from visual studio and verify it works fine
Open cmd and run dotnet test and observe it works fine
`dotnet test "LoggerDemo/bin/debug/net8.0/LoggerDemo.dll""`
Now run below command and see it throws exception
`C:\softi\nunit-console\bin\net8.0\nunit3-console.exe "LoggerDemo/bin/debug/net8.0/LoggerDemo.dll"`

`System.TypeInitializationException : The type initializer for 'OpenQA.Selenium.SeleniumManager' threw an exception.
  ----> OpenQA.Selenium.WebDriverException : Unable to locate or obtain Selenium Manager binary at C:\softi\nunit-console\bin\net8.0\selenium-manager\windows\selenium-manager.exe
   at OpenQA.Selenium.SeleniumManager.BinaryPaths(String arguments)
   at OpenQA.Selenium.DriverFinder.BinaryPaths()
   at OpenQA.Selenium.DriverFinder.GetDriverPath()
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor()
   at LoggerDemo.UnitTest2.Test1(String adf, String[] dsf) in C:\Repo\LoggerDemo\LoggerDemo\UnitTest2.cs:line 20
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--WebDriverException
   at OpenQA.Selenium.SeleniumManager..cctor()`

I have tried setting below still its not working
` $env:SE_MANAGER_PATH="LoggerDemo\bin\Debug\net8.0\selenium-manager\windows"`

**Comment by OsirisTerje** [comment]
Moving this to the console repo.
