### ISSUE TITLE
Issue: NUnitEngineException with Rerun of Failed Tests in Azure DevOps Pipeline

### ISSUE THREAD

**Issue by Aradhana09aug** [nunit/nunit#4867]
1. NUnit Version: 4.2.2
2. NUnit3TestAdapter Version: 4.6.0

**Issue description**
I am running my tests successfully in the Azure DevOps VSTest task. However, when I attempt to enable the rerun of failed tests within the same VSTest task, I encounter the following error:

Error Message:
   NUnit.Engine.NUnitEngineException: An exception occurred in the driver while loading tests. ---> System.IO.FileNotFoundException: Could not load file or assembly 'nunit.framework, Version=4.2.2.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)

**Comment by OsirisTerje** [comment]
We need some more context and information to help out here.
In general there might be issues due to compatibility and configuration challenges between NUnit and the specific way VSTest manages test state within a single task.

Common causes and workarounds include:

1. **Flaky Test Detection Limitations:** VSTS/Azure DevOps supports flaky test detection, but the rerun behavior may not always work seamlessly with NUnit, especially if using [Retry] attributes in NUnit rather than relying on the VSTest rerun settings.

2. **Isolation Issues:** Some NUnit tests that depend on state or require a fresh environment can fail to reset correctly for reruns. Running the rerun task in isolation can sometimes help.

3. **Alternative Approaches:** Splitting the test task into separate VSTest tasks for initial run and reruns (using conditions) can isolate issues, but it increases complexity.

Assuming you are using the latest version of the test though.
