### ISSUE TITLE
NUnitLite Nuget package is Beta 1a, Framework is Beta 1

### ISSUE THREAD

**Issue by CADbloke** [nunit/nunit#564]
Greetings

Firstly, congratulations on the Beta release. :)

edit: This may have already been solved by https://github.com/nunit/nunit/issues/559

...carry on...

To reproduce - using https://github.com/CADbloke/CADtest - I upgraded the Nuget packages from Alpha 5 to beta 1(a?). NUnlitLite's build version seems to be ahead of the framework version. I got this runtime error in AutoCAD...

````cs
  Application does not support just-in-time (JIT)
debugging. See the end of this message for details.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'nunit.framework, Version=3.0.5563.18085, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
File name: 'nunit.framework, Version=3.0.5563.18085, Culture=neutral, PublicKeyToken=2638cd05610744eb'
   at NUnitLite.Runner.AutoRun.Execute(String[] args)
   at CADTestRunner.NUnitLiteTestRunner.RunCADtests() in c:\Codez\CadBloke\GitHub\CADtest\CADtest-CS\CADtestRunner.cs:line 31
   at Autodesk.AutoCAD.Runtime.CommandClass.InvokeWorker(MethodInfo mi, Object commandObject, Boolean bLispFunction)
   at Autodesk.AutoCAD.Runtime.CommandClass.InvokeWorkerWithExceptionFilter(MethodInfo mi, Object commandObject, Boolean bLispFunction)
   at Autodesk.AutoCAD.Runtime.PerDocumentCommandClass.Invoke(MethodInfo mi, Boolean bLispFunction)
   at Autodesk.AutoCAD.Runtime.CommandClass.CommandThunk.Invoke()
````

Here is the part of the [CSPROJ file](https://github.com/CADbloke/CADtest/blob/master/CADtest-CS/CADtest-CS.csproj) before the upgrade ...

````xml
    </Reference>
    <Reference Include="Microsoft.Threading.Tasks">     <HintPath>..\packages\Microsoft.Bcl.Async.1.0.165\lib\net40\Microsoft.Threading.Tasks.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Threading.Tasks.Extensions">
      <HintPath>..\packages\Microsoft.Bcl.Async.1.0.165\lib\net40\Microsoft.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Threading.Tasks.Extensions.Desktop">
    <HintPath>..\packages\Microsoft.Bcl.Async.1.0.165\lib\net40\Microsoft.Threading.Tasks.Extensions.Desktop.dll</HintPath>
    </Reference>
    <Reference Include="nunit.framework, Version=3.0.5509.17457, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\NUnit.3.0.0-alpha-5\lib\net40\nunit.framework.dll</HintPath>
    </Reference>
    <Reference Include="nunitlite">
      <HintPath>..\packages\NUnitLite.3.0.0-alpha-5\lib\net40\nunitlite.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.IO">
      <HintPath>..\packages\Microsoft.Bcl.1.1.7\lib\net40\System.IO.dll</HintPath>
    </Reference>
    <Reference Include="System.Net" />
    <Reference Include="System.Runtime">
      <HintPath>..\packages\Microsoft.Bcl.1.1.7\lib\net40\System.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.Tasks">
      <HintPath>..\packages\Microsoft.Bcl.1.1.7\lib\net40\System.Threading.Tasks.dll</HintPath>
    </Reference>
````

...and after...

````xml
   <Reference Include="Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Threading.Tasks.Extensions, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Threading.Tasks.Extensions.Desktop, Version=1.0.168.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.Desktop.dll</HintPath>
    </Reference>
    <Reference Include="nunit.framework, Version=3.0.5562.31842, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\NUnit.3.0.0-beta-1\lib\net45\nunit.framework.dll</HintPath>
    </Reference>
    <Reference Include="nunitlite, Version=3.0.5563.18085, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\NUnitLite.3.0.0-beta-1a\lib\net45\nunitlite.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Net" />
````

Note in the first Exception message the `Version` for the framework is wrong, AutoCAD tried to load the framework in the same `Version` as Lite. Note in the upgraded CSPROJ file the different `Version` for Lite vs the framework.

From the Nuget upgrade All dialogue...

````
Attempting to resolve dependency 'AutoCAD.NET.Core (≥ 20.1.0 && < 21.0)'.
Attempting to resolve dependency 'AutoCAD.NET.Model (≥ 20.1.0 && < 21.0)'.
Attempting to resolve dependency 'Microsoft.Bcl.Build (≥ 1.0.14)'.
Attempting to resolve dependency 'NUnit (= 3.0.0-beta-1a)'.
Unable to resolve dependency 'NUnit (= 3.0.0-beta-1a)'.
````

Further weirdness you should ignore (caused by me) ... this in now a .NET 4.5 project but it started as a .NET 4.0 project. I just noticed `lib\net40\` in the original CSPROJ - I am the reason those are  there.

You should be able to build CADtest without AutoCAD but obviously you can't run it. If you ever need to run anything in AutoCAD let me know, I have every version since v2007.

**Comment by CharliePoole** [comment]
We "fixed" this by backing out the beta 1a release and won't be doing any more on it. I'm closing it to avoid clutter.
