### ISSUE TITLE
[NUnit 3.0 beta 1] nunit-console fails when use --output

### ISSUE THREAD

**Issue by melissalina89** [nunit/nunit#622]
When run: nunit-console.exe SomeTestLibrary.dll --output=fileName
It fails with the error
```
System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at NUnit.Common.ExtendedTextWrapper.WriteLine(String value) in c:\Users\123\Downloads\nunit-3.0.0-beta-1\src\Common\nunit\ExtendedTextWrapper.cs:line 67
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter) in c:\Users\123\Downloads\nunit-3.0.0-beta-1\src\NUnitConsole\nunit-console\ConsoleRunner.cs:line 175
   at NUnit.ConsoleRunner.ConsoleRunner.Execute() in c:\Users\123\Downloads\nunit-3.0.0-beta-1\src\NUnitConsole\nunit-console\ConsoleRunner.cs:line 106
   at NUnit.ConsoleRunner.Program.Main(String[] args) in c:\Users\123\Downloads\nunit-3.0.0-beta-1\src\NUnitConsole\nunit-console\Program.cs:line 115
```

**Comment by CharliePoole** [comment]
We need to ascertain the scope of the adjusted _outWriter. That is, when --output is specified, how much of the output is indended to be redirected and how much continues to display on the console.
