### ISSUE TITLE
Add support for microsoft fakes

### ISSUE THREAD

**Issue by faddison** [nunit/nunit#632]
Microsoft Fakes is the free non-invasive mocking framework that uses code instrumentation to enable mocking of non-abstract entities. The paid alternative is this http://www.typemock.com/

As far as I know, the only testing frameworks that support Fakes are mstest and possibly NCrunch.

Is it possible for NUnit to support Fakes, and will it ever happen?

**Comment by rprouse** [comment]
We do support other mocking frameworks like Moq. What doesn't work with Microsoft Fakes?

**Comment by CharliePoole** [comment]
Enlarging on Rob's comment... exactly what would "supporting" mean in this case. NUnit allows you to use any mocking framework without needing to actually know anything about those frameworks. In fact, if the test framework has to know about the mocking framework that would seem to be a design flaw.

That said, it's an important framework and we would consider any issues that you can define for us.

**Comment by faddison** [comment]
I believe it is the code instrumentation aspect. It doesn't work the same as Moq and Rhino.

See these posts:
http://stackoverflow.com/questions/19385037/microsoft-fakes-wont-run-in-normal-unit-test-contexts
https://connect.microsoft.com/VisualStudio/feedback/details/785411/cannot-debug-unit-tests-with-shims-in-vs2012-w-update2

There's plenty more if you google "microsoft fakes nunit"

**Comment by CharliePoole** [comment]
In the second of your two references, the MS guy writes "Shims require special instrumentation at the time a process starts." This would explain why the shim is working under NUnit's console and gui runners. In fact, I have found some references to the fact that they _do_ work with NUnit running under the VS TestExplorer. Clearly, VS provides the necessary initialization.

Several posts I have found have MS representatives stating that you should contact the authors of NUnit in order to make Fakes work - just as you have done. The only problem is that so far I haven't found any published information from Microsoft that would tell us just what sort of secret sauce is needed. This is unsurprising. It's Microsoft after all!

I think we should consider this as a challenge and make it work. I'm pretty sure someone will be able to tell us what is needed. We should make nunit-console work for 3.0 as well as the gui when we get to it.

**Comment by jamiehumphries** [comment]
It may be worth mentioning that NCrunch have made MIcrosoft Fakes and Shims work in their runner, so maybe one of their devs could point you in the right direction for instrumentation? @remcomulder?

**Comment by kevinkuszyk** [comment]
@CharliePoole did you ever find out what's needed to make this work?

**Comment by CharliePoole** [comment]
No... unfortunately, nobody has taken up the challenge of this issue - it remains unassigned.

Going back to Rob's comment 13 months ago... we don't actually know what it is that doesn't work. If somebody were to provide a snippet of code that doesn't work, but should, that would be a start.

Most likely, if somebody working on this project actually used Microsoft Fakes, this problem would have been addressed much quicker. I'm inviting all you folks who do use it to get involved!

**Comment by kevinkuszyk** [comment]
Yes, every other mocking library I've used has just worked too. 

I opened a test project with Microsoft Fakes in yesterday, and when I tried to switch to to NUnit I got this error:

```
Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException : Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables
```` 

> Going back to Rob's comment 13 months ago... we don't actually know what it is that doesn't work. If somebody were to provide a snippet of code that doesn't work, but should, that would be a start.

I'll try and push sample repro this afternoon.

@davidebbo any chance you can loop someone in from MSTest who can give us a steer on what environment variables Microsoft Fakes is expecting to see?

**Comment by kevinkuszyk** [comment]
The sample repro is here: https://github.com/kevinkuszyk/nunit-ms-fakes-demo.

And this is the output when a test using MS fakes is run:

```
NUnit Console Runner 3.4.1
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10240.0
  CLR Version: 4.0.30319.42000

Test Files
    src\TestProject\bin\Debug\TestProject.dll


Errors and Failures

1) Error : TestProject.TestClass.Test
Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException : Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables.
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.ResolveProfilerPath()
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.Initialize()
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationRuntime.InitializeUnitTestIsolationInstrumentationProvider()
   at Microsoft.QualityTools.Testing.Fakes.Shims.ShimRuntime.CreateContext()
   at TestProject.TestClass.Test() in c:\projects\github\NUnit MS Fakes Demo\src\TestProject\TestClass.cs:line 13

Run Settings
    WorkDirectory: c:\projects\github\NUnit MS Fakes Demo
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5.2
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 2

Test Run Summary
  Overall result: Failed
  Test Count: 1, Passed: 0, Failed: 1, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2016-07-01 11:38:20Z
    End time: 2016-07-01 11:38:21Z
    Duration: 0.323 seconds

Results (nunit3) saved as TestResult.xml
```

**Comment by CharliePoole** [comment]
Thanks for that. I've also done some research so now I understand it better.

Fakes is based on Moles, which was a Microsoft Research project. Because it was a research project, there's a pdf available about it's implementation. Because Fakes is the commercial, proprietary spin-off, there is no info out there beyond the very general about how it works or how to make it work when running under other executables that don't belong to MS. This shouldn't be surprising, since companies develop features like this in order to make their products better than those belonging to other people. :-)

What we are doing here - or what I'm doing - is trying to clarify the scope of this whole thing in order to decide whether we want to work on it. What we know so far seems to be...

* Fakes work based on instrumentation injected into the IL of the test assembly. This means you are not testing your actual assembly, but another assembly created from it. I mention this because I've worked in application areas - like medical equipment - where that would not be acceptable. Heck, some reviewers won't even except jitted code!

* They don't work running native NUnit. That's completely unsurprising, since NUnit doesn't modify the assembly in any way.

* Based on some SO posts, I got the impression that it might work using one or both of the NUnit adapters under VS. It would be helpful if somebody participating in this thread could find out whether that's so. I'm suspicious of it - I think if I were working on the VS team I'd argue that it's the job of the particular test framework.

* There is an Open Source app called Prig that claims to do what Fakes do. There may be some info to be found in their code if somebody wants to read it.

This issue has probably been placed on our Backlog and classified as a Feature prematurely. Both those things mean we intend to accept this and get it done. Really, as can be seen in this conversation, the issue should be considered an "Idea" - that is, something that would be a feature if we ever decided to do it. Just sayin' folks!

Just so you know, 100 people who wish we have this feature won't advance it as much as one who understands how to do it and wants to actually put in the time. Again, I'm just sayin' :-)

I won't jinx things by changing the issue labels right now. :-)

**Comment by frankshearar** [comment]
The magic required is that nunit3-console has to somehow configure the IntelliTrace instrument provider. This I know from nothing, but I'm digging around a bit to see if I can find out what needs doing. (That's not a promise to implement the feature: I will share what I learn, and if I can spare the cycles would love to take a run at the issue.)

**Comment by CharliePoole** [comment]
@frankshearar Thanks for your support. We'll be glad for anything you can dig up.

**Comment by AlexanderPetrusenkoAurea** [comment]
Hi,
What is the progress on this issue? R# test runner is so much better than that of MSVS (2017).

**Comment by frankshearar** [comment]
I've regrettably had no time to investigate. To be clear, the issue is not so much with NUnit, but with NUnit.ConsoleRunner. R#'s test runner would also have to be changed to hook in the IntelliTrace stuff.

**Comment by CharliePoole** [comment]
@frankshearar Have you found any other open source code that does whatever is needed?

**Comment by frankshearar** [comment]
https://github.com/Microsoft/vstest is the codebase for vstest.console.exe. I scratched around in there to no avail. For instance, according to my reading, you need to use an environment variable COR_PROFILER; this is not referenced at all in the vstest codebase.

**Comment by frankshearar** [comment]
I stumbled across a possible clue - OpenCover supports Fakes, and does so here: https://github.com/OpenCover/opencover/blob/df7728194c378a5fa06bce4b02c1c321b0b65432/main/OpenCover.Support/Fakes/FakesHelper.cs

You can see they kind've "shadow" an existing profiler with their own profiler.

**Comment by mikkelbu** [comment]
@frankshearar This probably explains why you could not find anything relating to fakes in the codebase for vstest - https://github.com/Microsoft/vstest/issues/1071#issuecomment-329265008

**Comment by frankshearar** [comment]
Fakes doesn't inject IL. That CLR profiling API is more akin to a collection of callbacks that get invoked on every method entry/exit. It does literally allow you to change out a base library method with whatever you want. That's not EXACTLY like Javascript/Ruby monkey patching but it's practically indistinguishable.

https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/profiling-overview#profiling_api explains how you _could_ use the profiling API to measure performance, but really, it's a much more generic facility than that.

You hook up your profiler into the API through the COR_PROFILER environment variable, but that's all I know - I haven't had the cycles to find out how exactly to do that.

**Comment by ericnewton76** [comment]
Excellent, thats exactly how to achieve having the Fakes and Shims work.  Then you can literally override DateTime.Now and return a specific datetime within the scope of a ShimContext.

How exciting for Unit testing if we can get this... the Dependency Injection crowd will finally have to go suck it!  (Me included)

**Comment by brian-reichle** [comment]
@frankshearar 
> Fakes doesn't inject IL. That CLR profiling API is more akin to a collection of callbacks that get invoked on every method entry/exit.

The ELT callbacks (enter/leave/tailcall) are not permitted to call back into managed code, nor are any of the other profiler callbacks. Fakes would almost certainly be using IL rewriting (modifying the IL at JIT time).

> You hook up your profiler into the API through the COR_PROFILER environment variable, but that's all I know - I haven't had the cycles to find out how exactly to do that.

* `COR_ENABLE_PROFILING` needs to be set to `1`
* `COR_PROFILER` needs to be set to the CLSID or ProgID of the profiler COM object.
* If the profiler COM object is not registered, then you also need `COR_PROFILER_PATH` (or `COR_PROFILER_PATH_32`/`COR_PROFILER_PATH_64`) to specify the location of the dll containing the COM object.

(I believe each of these has a `CORECLR_*` variant for .Net Core, but I don't have experience with that)

The profiler itself may require further configuration beyond what the runtime requires, but if it comes down to just setting environment variables to predictable values, then _maybe_ NUnit only really needs to provide an extension point to control how the agent process is started.

@ericnewton76 

> I think beyond the performance cost, there's another cost in that some assemblies might not be "allowed" to run like that or something, probably related to Code Access Security? (Although I believe Code Profiling flag relaxes that as well!)

I assume you are referring to `COR_PRF_DISABLE_TRANSPARENCY_CHECKS_UNDER_FULL_TRUST`, this is something for Fakes to worry about, shouldn't be a concern for NUnit.

> Like I mentioned before, Code Profiling API turned on has a cost in slower execution, so you wouldn't normally turn it on

I think you might be getting ahead of yourself :). With the ReJIT support introduced in .Net 4.5, I expect it would only need to instrument methods as needed and reverted when done, so the cost should be fairly minimal (assuming the cost of loosing ngen'ed images is spread across enough tests) ... but, to be measured.

**Comment by brian-reichle** [comment]
The minimal set of environment variables seems to be:

```
COR_PROFILER={9317ae81-bcd8-47b7-aaa1-a28062e41c71}
COR_ENABLE_PROFILING=1
VSTS_PROFILER_NOT_CLEAR_ENVVARS=1
INTELLITRACE_PROFILER_DIRECTORY=[Path-To-VS]\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace
VSLOGGER_CPLAN=[Path-To-Generated-IntelliTrace-Collection-Plan]
```

The first 4 shouldn't pose too much of a problem, generating the collection plan from the fakes configuration might be an issue though. Running the tests through `vstest.console.exe` in [Microsoft.TestPlatform](https://www.nuget.org/packages/Microsoft.TestPlatform/) seems to be an easier alternative (though the output isn't as nice).
