### ISSUE TITLE
Failing Tests in TeamCity Build

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [nunit/nunit#670]
2 tests are currently failing the TeamCity build

https://teamcity.jetbrains.com/project.html?projectId=NUnit_NUnit3_BuildAndTest

NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoEqual
NUnit.Framework.Constraints.EqualityComparerTests.SameDirectoriesAreEqual 

```cs
System.ArgumentException : The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoEqual()
```

I believe this happens because the teamcity agent running the test is a service account with no My Documents folder.

**Comment by CharliePoole** [comment]
We should probably create a temp directory for this test.

**Comment by michal-franc** [comment]
Is this acceptable or do we need to try harder ? 

```      
        [Test]
        public void SameDirectoriesAreEqual()
        {
            using (var tempDir = new TestDirectory())
            {
                var one = new DirectoryInfo(tempDir.Directory.FullName);
                var two = new DirectoryInfo(tempDir.Directory.FullName);
                Assert.That(comparer.AreEqual(one, two, ref tolerance));
            }
        }

        [Test]
        public void DirectoryInfoEqual()
        {
            using (var tempDir = new TestDirectory())
            {
                var one = new DirectoryInfo(tempDir.Directory.FullName);
                var two = new DirectoryInfo(tempDir.Directory.FullName);
                Assert.AreEqual(one, two);
            }
        }
```

**Comment by CharliePoole** [comment]
It looks fine to me. It's a simple test, so simple code makes sense. :-)
