### ISSUE TITLE
Nunit Hangs with a message box

### ISSUE THREAD

**Issue by omer727** [nunit/nunit#717]
Hi,
I'm running my tests on a separate process using nunit-console-x86. 
Sometimes the test throws an exception, the nunit-agent catch this exception display a message box on the screen and hangs.

Is there any way to tell nunit to skip this message box, write an error to the log and continue to the next test (for example the /stoponerror flag)?

Thanks,
          Omer

**Comment by rprouse** [comment]
What is displayed in the message box? What type of exception is being thrown and from where (conftructor, setup,  test, etc?) 

Displaying a message box isn't normal. Is a Windows debug message box?

**Comment by omer727** [comment]
Here is the message box I'm getting:
![nunit-agent](https://cloud.githubusercontent.com/assets/1544215/8549936/2762f210-24d6-11e5-8d58-3d3e96837ff4.png)
I can also see the following log in event viewer under .NET framework :

`
Application: nunit-agent-x86.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
Stack:
   at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods+IOleInPlaceObject.InPlaceDeactivate()
   at System.Windows.Forms.AxHost.InPlaceDeactivate()
   at System.Windows.Forms.AxHost.TransitionDownTo(Int32)
`
It's important to mention it only happens on Windows 8.1

**Comment by rprouse** [comment]
This is an NUnit 2.6.x issue. Without more information, we can't verify if it is still happening in NUnit 3. Can you provide a minimal example that reproduces the problem?

**Comment by rprouse** [comment]
@omer727, we haven't heard back from you so we are closing this issue. If you haven't solved your problem, feel free to ask us here to reopen the issue.
