### ISSUE TITLE
Custom Attributes cause error when running tests using NUnit-console.

### ISSUE THREAD

**Issue by pollyfahey** [nunit/nunit#838]
We created a custom attribute for our tests that inherits from NUnit.Framework.PropertyAttribute and called the base constructor "protected PropertyAttribute(object propertyValue)" passing an enum value.
Using the PropertyAttribute directly using the "public PropertyAttribute(string propertyName, string propertyValue)" did not cause an error.
Using NUnit 2.6.4, we saw the following error when running the tests using nunit-console.exe:

NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment -
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 2.0.50727.5466 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
Unhandled Exception:
System.Runtime.Serialization.SerializationException: Unable to find assembly '<My assembly>, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Server stack trace:
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(MemoryStream stm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.FixupForNewAppDomain()
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Core.TestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Core.TestRunner.get_Test()
   at NUnit.Core.ProxyTestRunner.get_Test()
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)

We also get similar errors when using the NUnit GUI and using the TeamCity NUnit runner. However the Resharper unit test runner does not error.

**Comment by rprouse** [comment]
This is an NUnit 2.6.4 issue and we will not be releasing an update to 2.6. The code is very different in 3.0, but we would still like to confirm that it is fixed. Can you provide a minimum working sample for us to test?

**Comment by rprouse** [comment]
@pollyfahey, we need more information to reproduce this issue. If we can't confirm that it is still an issue in 3.0, we will close. Thanks.

**Comment by pollyfahey** [comment]
The code below reproduces the error.

using NUnit.Framework;

[TestFixture]
public class Test
{
    [CustomProperty(CustomPropertyType.First)]
    [Test]
    public void MinimumWorkingTest()
    {
    }
}

public enum CustomPropertyType
{
    First,
    Second
}

public class CustomPropertyAttribute : PropertyAttribute
{
    public CustomPropertyAttribute(CustomPropertyType type)
        : base(type)
    {
    }
}

**Comment by pollyfahey** [comment]
Accidentally closed and reopened.

**Comment by rprouse** [comment]
Thanks, that worked great. I can confirm that this is a bug in 2.6.4, but it is fixed in 3.0. As I said before, we won't be releasing an update to 2.6, so I am going to close this issue as fixed in 3.0.

Thanks for your help.
