### ISSUE TITLE
Test runner fails if test name contains invalid xml characters

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#850]
If a test name contains invalid xml characters the test runner fails. 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: '☺', hexadecimal
 value 0x01, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.WriteTo(XmlWriter writer)
   at NUnit.Framework.Interfaces.TNode.get_OuterXml()
   at NUnit.Framework.Api.FrameworkController.RunTests(ICallbackEventHandler handler, String filter)

```csharp
public static IEnumerable<char> InvalidCharacters
{
    get
    {
       return Path.GetInvalidFileNameChars();
    }
}

[Test]
public void HandleInvalidCharacters([ValueSource("InvalidCharacters")] char invalidCharacter)
{
}
```
It fails for any character c that is ```!XmlCharType.IsSurrogate(c) && (c < 127 || c >= 65534)``` from what I can tell.

https://msdn.microsoft.com/en-us/library/system.xml.xmlwritersettings.checkcharacters%28v=vs.110%29.aspx

**Comment by rprouse** [comment]
I have confirmed this issue. It would likely be an easy fix to set `XmlWriterSettings.CheckCharacters  = false` but I am not sure we want to do this. Another option would be to convert invalid characters to a valid placeholder character, but this might create more duplicate test names.

What do other team members think about the priority, milestone and possible fixes for this? I have set it for 3.0 RC, but we could probably push it. @appel1, is this a blocker for you?

**Comment by CharliePoole** [comment]
Let's make sure we didn't drop some check we were doing in NUnit 2.x. What makes me wonder about that is the fact that nobody has run into this before.

**Comment by appel1** [comment]
Not a blocker. Was fairly easy to work around either by inlining the test cases or wrapping the invalid characters in an object that outputs the integer value in ToString. A bit more difficult to figure out than I'd like because of no context in the test runner output, had to resort to building nunit framework myself to be able to debug.

**Comment by CharliePoole** [comment]
There is already code in TestResult.cs that solves this problem for user-created messages. We need to do the same thing for the test name and for anything else that is subject to having invalid chars.
