### ISSUE TITLE
NUnit Engine Tests fail if not run from test directory

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#938]
Run the engine tests from the root of the solution with the following command line,

```
.\bin\Debug\nunit-console.exe .\bin\Debug\nunit.engine.tests.dll
```

5 tests fail. They pass if run from the bin\Debug directory. Probably an easy fix, but I think it is the tests themselves that are broken, not the engine itself. We should confirm that, then maybe move out to 3.2?

The failure are;

```
1) Error : NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed("EngineTests.nunit",null,NUnit.Engine.Runners.ProcessRunner)
System.IO.FileNotFoundException : Could not find file 'C:\src\github\nunit\EngineTests.nunit'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at NUnit.Engine.Services.ProjectLoaders.NUnitProject.Load(String filename) in C:\src\github\nunit\src\NUnitEngine\Addins\nunit-project-loader\NUnitProject.cs:line 127
   at NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom(String path) in C:\src\github\nunit\src\NUnitEngine\Addins\nunit-project-loader\NUnitProjectLoader.cs:line 45
   at NUnit.Engine.Services.ProjectService.LoadFrom(String path) in C:\src\github\nunit\src\NUnitEngine\nunit.engine\Services\ProjectService.cs:line 131
   at NUnit.Engine.Services.ProjectService.ExpandProjectPackage(TestPackage package) in C:\src\github\nunit\src\NUnitEngine\nunit.engine\Services\ProjectService.cs:line 67
   at NUnit.Engine.Services.DefaultTestRunnerFactory.MakeTestRunner(TestPackage package) in C:\src\github\nunit\src\NUnitEngine\nunit.engine\Services\DefaultTestRunnerFactory.cs:line 93
   at NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(String files, String processModel, Type expectedType) in C:\src\github\nunit\src\NUnitEngine\nunit.engine.tests\Services\DefaultTestRunnerFactoryTests.cs:line 94

2) Error : NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed("EngineTests.nunit","Single",NUnit.Engine.Runners.TestDomainRunner)
System.IO.FileNotFoundException : Could not find file 'C:\src\github\nunit\EngineTests.nunit'.
   <SNIP>
   at NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(String files, String processModel, Type expectedType) in C:\src\github\nunit\src\NUnitEngine\nunit.engine.tests\Services\DefaultTestRunnerFactoryTests.cs:line 94

3) Error : NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed("EngineTests.nunit","Separate",NUnit.Engine.Runners.ProcessRunner)
System.IO.FileNotFoundException : Could not find file 'C:\src\github\nunit\EngineTests.nunit'.
   <SNIP>
C:\src\github\nunit\src\NUnitEngine\nunit.engine\Services\DefaultTestRunnerFactory.cs:line 93
   at NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(String files, String processModel, Type expectedType) in C:\src\github\nunit\src\NUnitEngine\nunit.engine.tests\Services\DefaultTestRunnerFactoryTests.cs:line 94

4) Error : NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed("EngineTests.nunit","Multiple",NUnit.Engine.Runners.MultipleTestProcessRunner)
System.IO.FileNotFoundException : Could not find file 'C:\src\github\nunit\EngineTests.nunit'.
   <SNIP>
C:\src\github\nunit\src\NUnitEngine\nunit.engine\Services\DefaultTestRunnerFactory.cs:line 93
   at NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(String files, String processModel, Type expectedType) in C:\src\github\nunit\src\NUnitEngine\nunit.engine.tests\Services\DefaultTestRunnerFactoryTests.cs:line 94

5) Error : NUnit.Engine.Services.Tests.ResultServiceTests.CanGetWriter("user",System.Object[])
System.ArgumentException : Unable to load transform TextSummary.xslt
   at NUnit.Engine.Services.XmlTransformResultWriter..ctor(Object[] args) in C:\src\github\nunit\src\NUnitEngine\nunit.engine\Services\ResultWriters\XmlTransformResultWriter.cs:line 56
   at NUnit.Engine.Services.ResultService.GetResultWriter(String format, Object[] args) in C:\src\github\nunit\src\NUnitEngine\nunit.engine\Services\ResultService.cs:line 74
   at NUnit.Engine.Services.Tests.ResultServiceTests.CanGetWriter(String format, Object[] args) in C:\src\github\nunit\src\NUnitEngine\nunit.engine.tests\Services\ResultServiceTests.cs:line 65
```

**Comment by CharliePoole** [comment]
I agree with your assessment.

**Comment by CharliePoole** [comment]
@rprouse I think this is fixed with RC3. Can you confirm?

**Comment by rprouse** [comment]
Tested and this is not fixed with RC 3.

**Comment by CharliePoole** [comment]
OK. They seemed fixed for me, but I may not have run them in exactly the same way. We have a number of tests that depend on finding files in the right  directory but they should be fixable.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #16](https://github.com/nunit/nunit-console/issues/16) via [**ZenHub**](https://www.zenhub.com/)
