### ISSUE TITLE
System.NullReferenceException Writing Results to File with Named Ignore in TestCase

### ISSUE THREAD

**Issue by ashes999** [nunit/nunit#980]
Environment: NUnit 2.6.4 (GUI and command-line)

We recently added a named-ignore to a test-case attribute. We changed `[TestCase("C1")]` to `[TestCase("C1", Ignore = true)]`

We also run NUnit with command-line parameters to write out the results to an XML file. This change resulted in this exception stack:

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at NUnit.Util.XmlResultWriter.WriteCData(String text)
  at NUnit.Util.XmlResultWriter.WriteReasonElement(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteChildResults(TestResult result)
  at NUnit.Util.XmlResultWriter.WriteResultElement(TestResult result)
  at NUnit.Util.XmlResultWriter.SaveTestResult(TestResult result)
  at NUnit.ConsoleRunner.ConsoleUi.CreateXmlOutput(TestResult result)
  at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
  at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

This behaviour occurs both with the GUI client and with running from the command-line.

**Comment by CharliePoole** [comment]
It definitely looks like a bug. As a workaround, use 
    [TestCase("C1", Ignore=true, Reason="something")] 
or more simply
    [TestCase("C1", IgnoreReason="something")]

I'm marking this as "won't fix" because we are no longer maintaining NUnit 2.6.4. The problem cannot arise in NUnit 3.0 because it's no longer possible to use Ignore without a reason. In 3.0, you write
    [TestCase("C1", Ignore="something")]
