### ISSUE TITLE
NUnit Engine 3 beta5 fails for parallel IO read

### ISSUE THREAD

**Issue by Guson** [nunit/nunit#989]
### Background
I'm trying to run all test in parallel, after tip from @CharliePoole. We have some tests that’s reads XML-files from disk. First I thought it was the test code, using a `StringBuilder` to combine the filename parts, so I changed to `Path.Combine`, but still IO exception, in `XmlDocument.Load`.

### Tests
The test is using several `TestCase`, and in Visual Studio we still use NUnit 2.6.3 Nuget package. I guess using the `[Parallelizable(ParallelScope.Self)]` attribute is only available in NUnit 3?

### Failure
In the log you can see that the path to the file is corrupted, i.e. `ace\DailyEyeDoc\Forms\trunk\EyeDoc.Forms.Tests\` is missing. When only runing this test-dll, the path is correct from `var xmlPath = Path.Combine(baseDirectory, SettingsXmlBaseDirectory, xmlFileName);`.

```
39) Error : EyeDoc.Forms.Tests.FormSettings.ConditionsTest.TestConditionsFromSettingsXml("ConditionsSignedAndSent.xml",30,4400,True)
System.IO.DirectoryNotFoundException : Could not find a part of the path 'd:\jenkins\worksp\FormSettings\SettingsXml\ConditionsSignedAndSent.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at EyeDoc.Forms.Tests.FormSettings.Helper.GetSettingsXml(String xmlFileName) in d:\jenkins\workspace\DailyEyeDoc\Forms\trunk\EyeDoc.Forms.Tests\FormSettings\Helper.cs:line 50
   at EyeDoc.Forms.Tests.FormSettings.ConditionsTest.TestConditionsFromSettingsXml(String xmlFileName, Int32 caseStatus, Int64 bitStatus, Boolean expectedResult) in d:\jenkins\workspace\DailyEyeDoc\Forms\trunk\EyeDoc.Forms.Tests\FormSettings\ConditionsTest.cs:line 36
```

After adding `File.Exists(xmlPath)`, in my test code, with a `FileNotFoundException` exception.
```
39) Error : EyeDoc.Forms.Tests.FormSettings.ConditionsTest.TestConditionsFromSettingsXml("ConditionsSignedAndSent.xml",30,4400,True)
System.IO.FileNotFoundException : The settings XML is missing. (d:\jenkins\worksp\FormSettings\SettingsXml\ConditionsSignedAndSent.xml)
   at EyeDoc.Forms.Tests.FormSettings.Helper.GetSettingsXml(String xmlFileName) in d:\jenkins\workspace\DailyEyeDoc\Forms\trunk\EyeDoc.Forms.Tests\FormSettings\Helper.cs:line 50
   at EyeDoc.Forms.Tests.FormSettings.ConditionsTest.TestConditionsFromSettingsXml(String xmlFileName, Int32 caseStatus, Int64 bitStatus, Boolean expectedResult) in d:\jenkins\workspace\DailyEyeDoc\Forms\trunk\EyeDoc.Forms.Tests\FormSettings\ConditionsTest.cs:line 37
```

### Workaround
Remove the test-dll from the `nunit`-file, and run it separately.

### Relates to
* [NUnit Engine Tests fail if not run from test directory #938](https://github.com/nunit/nunit/issues/938)
* [Cannot run NUnit Console from another directory #853](https://github.com/nunit/nunit/issues/853)
* [Run the tests parallel #985](https://github.com/nunit/nunit/issues/985)
* [ParallelizableAttribute - NUnit](http://nunit.org/index.php?p=parallelizable&r=3.0)

**Comment by CharliePoole** [comment]
I need a few more bits of information.

1. You mention NUnit 2.6.3. Are you running 2.6.3 tests under 3.0?

2. What is the command line you are running? I guess it involves an nunit project file?

3. How do you construct the path to the file you want to load? I see the Path.Combine call above but where do you get the arguments?

From your workaround, I am guessing that you are locating the file relative to the ApplicationBase. That's not a good practice in NUnit tests, since the tests can be executed with a number of different possible base directories. In particular, the default base directory for assemblies in an nunit project file is the directory of the project file.

You may find that it also works correctly if you simply list all your assemblies on the command line, but this is just a guess right now. :-)

**Comment by rprouse** [comment]
@Guson are you still seeing this? I would like to close confirm issues that don't have any progress.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
